### ISSUE TITLE
ComponentStatus API is being deprecated

### ISSUE THREAD

**Issue by hakman** [kubernetes/kops#10057]
kops uses ComponentStatus API which was deprecated by https://github.com/kubernetes/kubernetes/pull/93570:
https://github.com/kubernetes/kops/blob/5d9822dedb3cc1e8d093c33d6b81cccdaf8a5df2/pkg/validation/validate_cluster.go#L183

This results in the following warning printed during validation:
```
W1014 13:16:53.072300    6628 warnings.go:67] v1 ComponentStatus is deprecated in v1.19+
```

**Comment by bharath-123** [comment]
In validate_cluster, In collect pod failures we already check whether kube-apiserver, kube-controller-manager and kube-scheduler are present in the cluster. 
https://github.com/kubernetes/kops/blob/master/pkg/validation/validate_cluster.go#L235
I think we can remove component status and also check for health of the pods right here. Since ComponentStatus checked for the status of etcd(done thru kube-apiserver), kube-controller-manager and kube-scheduler, we would be covering all the ground ComponentStatus is covering. What do you think? @hakman @johngmyers
