### ISSUE TITLE
[Question] Node reboot after initial setup

### ISSUE THREAD

**Issue by dene14** [kubernetes/kops#10184]
We run our clusters in AWS, as a part of node initialization we set up extra software and perform distro update.
kops scripts also perform modifications to systems sometimes that require reboot.

On every node that was provisioned you may see "Reboot required" message in terminal.

So question: what is recommended way to reboot the node right after initialization?

**Comment by olemarkus** [comment]
In short, we don't support this. We expect that the image used is reasonably up to date and just perform a normal unattended upgrade to update packages updated since the last ubuntu AMI release.

That being said, we don't necessarily have timely updates of the ubuntu AMIs. So if you see reboot required messages, then most likely we are missing an AMI update and would appreciate a PR to the channels files.

**Comment by olemarkus** [comment]
Think there is nothing more to do here.

/remove-lifecycle stale
/close
