### ISSUE TITLE
Optimized AMIs for Ubuntu 20.04

### ISSUE THREAD

**Issue by valouille** [kubernetes/kops#10350]
Hello Kops team,

Starting Kops 1.18, [Ubuntu 20.04 official images](https://github.com/kubernetes/kops/blob/master/docs/operations/images.md#images) are used instead of Debian optimized images. Using Ubuntu 20.04 is a great change as it comes with a recent kernel fixing some issues like CPU throttling related issues. 

However, as they're official images, they tend to take much more time to startup and become part of the K8S cluster than older Debian 9 _Kubernetes Optimized_ images. We noticed an average of 1m30s with Debian 9 optimized images, but it can take up to 7 minutes with Ubuntu 20.04 official images using m5a.xlarge instances, leading to longer cluster rollout times and less reactive defensive autoscaling. 

What it the reason of dropping optimized images ? Do you plan to propose Ubuntu optimized images at some point ?

Thanks

**Comment by olemarkus** [comment]
The gist of it is that we don't have enough manpower to build our own images anymore.
It is something we may revisit later on if anyone is willing to set this up.

**Comment by hakman** [comment]
Could you check if by any chance you bumped into this?
https://github.com/kubernetes/kops/issues/10206#issuecomment-726237618

**Comment by ReillyTevera** [comment]
We're building and using custom Debian 10 images with a 5.4 kernel and everything pre-installed and it works well. I haven't timed it but I believe it's around 45s until a new node is fully functioning. 

We use Packer to build the images.

**Comment by MichaelJDrK** [comment]
Have you tried using just the Ubuntu minimal images instead of the default server images?

**Comment by hakman** [comment]
> Have you tried using just the Ubuntu minimal images instead of the default server images?

How would that change anything, except maybe make things slower?

**Comment by valouille** [comment]
@hakman I'll do some tests in the upcoming days to ascertain this.

@ReillyTevera Do you happen to have published your Packer files on GitHub somewhere so that we can eventually reuse some part for Ubuntu 20.04 ?

**Comment by ReillyTevera** [comment]
@valouille Unfortunately our Packer build scripts do a lot of company-specific things like security hardening and setting up users and are generally unsuitable for being posted on GitHub. 

For the most part though SSH into a running kops node and look at `/var/log/apt/history.log` (might be different on Ubuntu) to see what nodeup installs. Have your Packer script install those packages during the build process. You will need to preinstall your container runtime as well and then check out the Kops docs to see what cluster setting you need to modify to disable trying to install that during nodeup (for Docker it's `.spec.docker.skipInstall = true`). `.spec.updatePolicy` should be set to `external` as well so that nodes don't waste time trying to update packages during nodeup.

Also, protip, if you throw the following into a bash script it'll allow you to write your Packer scripts in YAML (so you can have comments!) and generally save you a bunch of headache:
```
python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < $1 | packer build -
```

**Comment by valouille** [comment]
@hakman, it seems I bumped into the issue you mentioned indeed. Right now every startup is quite quick, using kubernetes-optimized Debian AMIs or Ubuntu Server ones.

I tried to create a custom Ubuntu AMI based on [this configuration file](https://github.com/kubernetes-sigs/image-builder/blob/54c102628f5dc59c730bcf665cc32b6bcbd1e472/images/kube-deploy/imagebuilder/templates/1.18-stretch.yml), and I can still gain approximately 30s in startup time compared to the normal Ubuntu server AMI, but it doesn't make a big difference as most time during rollouts isn't startup time, but everything else (drain, cluster validation, instance creation by the ASG, etc...). A rollout of three nodes takes ~14m in my configuration and approximately 12m with optimized images.

**Comment by hakman** [comment]
That's good news @valouille. Thanks for the update. Based on https://github.com/kubernetes/kops/issues/10206#issuecomment-744372627 seems that the fix will be part of the official ubuntu images soon.
The rollout is a bit slower without optimized images, but using https://kops.sigs.k8s.io/operations/rolling-update/#maxsurge should help.
