### ISSUE TITLE
Remaining work for Azure support

### ISSUE THREAD

**Issue by kenji-cloudnatix** [kubernetes/kops#10412]
This issues track the remaining TODOs from https://github.com/kubernetes/kops/issues/3957 (Azure support)

- [ ] Be able to configure some more parameters for VM Scale Set such as Windows
- [ ] Be able to configure some more parameters for Azure Disks such as zone
- [ ] Be able to configure some more parameters for subnets such as security groups
- [ ] Support DNS
- [ ] Support tag update of virtual networks
- [ ] Support ACL for Azure blob VFSImplement
- [x] Implement `azureCloudImplementation.GetApiIngressStatus`. Currently we don't create any resources for ingress to the API server.
- [x] ~Be able to mount etcd volumes from protokube. Currently we rely on etcd-manager for volume mount~
- [ ] Populate node labels from `nodeIdentifier.IdentifyNodeChange`.
- [ ] Implement `azureCloudImplementation.buildCloudInstanceGroup` so that kops can correclty tell whether a VM is up-to-date or not.

**Comment by Aut0R3V** [comment]
anything I can do here?

**Comment by olemarkus** [comment]
Any of these are up for grabs, I would think.

**Comment by rifelpet** [comment]
I think we can remove `Be able to mount etcd volumes from protokube. Currently we rely on etcd-manager for volume mount` from the list. That is only needed for the "legacy" etcd option before etcd-manager. Given that it will eventually go away, I don't see a need to add support for it in Azure.

**Comment by ngalantowicz** [comment]
Not sure how tasks are divided up for an issue like this or if work started needs to be reported, but folks I work with and myself are interested in starting

> Implement azureCloudImplementation.GetApiIngressStatus. Currently we don't create any resources for ingress to the API server.

Will be first time kops contributors, so any pertinent info to contributing that may be omitted from relevant docs is much appreciated

**Comment by rifelpet** [comment]
@ngalantowicz thanks for stepping up! [here](https://github.com/kubernetes/kops/blob/9bc1c0ed7743eb387d14f2649b2a3cc39cfc56fa/upup/pkg/fi/cloudup/azure/azure_cloud.go#L130) is the function that needs implementing. you'll see the return type contains either an IP or Hostname. For clusters that use api load balancers with hostnames we specify the hostname, otherwise use the api load balancer's IP(s). For clusters that don't use api load balancers we return a list of the master instances' IPs. A good example of this is the [openstack implementation](https://github.com/kubernetes/kops/blob/fb0fbb528074a9bf4d9d6e9edbaf869b9db3095d/upup/pkg/fi/cloudup/openstack/cloud.go#L655-L743).

For Azure, we don't yet support API load balancers so you'll only need to handle getting the master VMs' IPs. 

Unfortunately we dont yet have azure code for listing VMs, only [VMScaleSets](https://github.com/kubernetes/kops/blob/9bc1c0ed7743eb387d14f2649b2a3cc39cfc56fa/upup/pkg/fi/cloudup/azure/vmscaleset.go). You'll likely need to add a new file and client for VMs (it only needs to support listing them, not create / update / delete) and add the client to the [AzureCloud](https://github.com/kubernetes/kops/blob/9bc1c0ed7743eb387d14f2649b2a3cc39cfc56fa/upup/pkg/fi/cloudup/azure/azure_cloud.go#L39) interface.

With the VM listing functionality you'll be able to list them all and filter for the VMs that are associated with the cluster and that have the master role tag.

I hope this helps, let me know if you need any additional assistance

**Comment by kenji-cloudnatix** [comment]
Thanks, @ngalantowicz , @rifelpet ! Just wanted to make a quick comment for listing VMs. I hink we can reuse the code in etcd-manager like [this](https://github.com/kopeio/etcd-manager/blob/master/pkg/volumes/azure/discovery.go#L48).

**Comment by NickSchleicher** [comment]
is there any additional information in regards to
`Populate node labels from nodeIdentifier.IdentifyNodeChange`?

i assume it might just mean labeling the nodes with the labels that can be specified in the instance group as seen below, by grabbing the tags from the cloud, but want to be sure i cover the whole depth of it
```
  nodeLabels:
    tier: web
    ...
```

i was going to start work on that, but it looks like there might be an existing error in this domain
```
I0120 18:14:43.199009       1 node_controller.go:144] sending patch for node "web000001": "{\"metadata\":{\"labels\":{\"\":\"web\"}}}"
W0120 18:14:43.204913       1 node_controller.go:110] failed to patch node labels on web000001: error applying patch to node: Node "web000001" is invalid: [metadata.labels: Invalid value: "": name part must be non-empty, metadata.labels: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
```

https://github.com/kubernetes/kops/blob/309dc9fc26a5eb65614c3961239fd102f272ace5/pkg/nodeidentity/azure/identify.go#L35
https://github.com/kubernetes/kops/blob/309dc9fc26a5eb65614c3961239fd102f272ace5/pkg/nodeidentity/azure/identify.go#L111
![Screen Shot 2021-01-20 at 1 47 30 PM](https://user-images.githubusercontent.com/20826205/105220665-0bd00880-5b26-11eb-97cb-34b09bef16f4.png)

the tag that is in the cloud for the VMSS is also the "prefix" so the key is left as an empty string. Do we need this label and if so, what should the key be?


Also partially related, I noticed an instance group is required to have the label `kops.k8s.io/cluster` or else you'll get the error
`error: must specify "kops.k8s.io/cluster" label with cluster name to create instanceGroup`
is it an issue that this label has a `/` in it and never makes it to the cloud as a tag

**Comment by kenji-cloudnatix** [comment]
Thanks for looking into, @NickSchleicher ! This looks like a bug in my original code. I believe we need to trim with `clusterNodeTemplateLabel` defined in https://github.com/kubernetes/kops/blob/309dc9fc26a5eb65614c3961239fd102f272ace5/pkg/model/azuremodel/context.go#L74.

You're right on the label `kops.k8s.io/cluster` as well. Currently `CloudTagsForInstanceGroup` has a logic to replace all occurrences of `"/"` to `"_"`. I believe we need to convert `"_"` back to `"/"` in https://github.com/kubernetes/kops/blob/309dc9fc26a5eb65614c3961239fd102f272ace5/pkg/nodeidentity/azure/identify.go#L111.

**Comment by ngalantowicz** [comment]
Reaching out with for more info
`Support tag update of virtual networks`

Seeing
https://github.com/kubernetes/kops/blob/309dc9fc26a5eb65614c3961239fd102f272ace5/upup/pkg/fi/cloudup/azuretasks/virtualnetwork.go#L114-L121

An interesting behavior to note regarding route tables (which task and client files seem to be a mirror of the vnet files):
When creating a cluster with existing route table no new route table is created however the inUseError does occur and cluster delete fails due to such.  If I manually remove the tags from the route table and run delete again no issues.

Are these two things similar and is there any vision/insight on how youd go about implementing tag update support?
Im thinking the work is to update tags when using pre-existing resources and remove tags when pre-existing resource was used is the goal?  

@kenji-cloudnatix

**Comment by kenji-cloudnatix** [comment]
> Im thinking the work is to update tags when using pre-existing resources and remove tags when pre-existing resource was used is the goal?

Yes, I think so, but I'm not certain if removing the tag is what kops does for other CSPs. I think other people can chime-in.

The issues with updating a tag of vnet was that it causes an `InUseSubnetCannotBeDeleted` error. I haven't fully figured out a cause, but my guess is that we need to set the `Subnet` field of `VirtualNetworkPropertiesFormat`. 

https://raw.githubusercontent.com/Azure/azure-sdk-for-go/master/services/network/mgmt/2020-06-01/network/models.go

Otherwise, the update request attempts to delete an existing subnet (and then the request fails).

**Comment by rifelpet** [comment]
FWIW, based on the code in pkg/resources it doesn't seem that Kops removes any tags on shared resources when a cluster is deleted.

**Comment by NickSchleicher** [comment]
From a glance it looks like we don't have support yet for multi AZ instances
https://github.com/kubernetes/kops/blob/master/pkg/model/azuremodel/vmscaleset.go#L68

Coming from an AWS background where the subnets are zonal, but from looking at the other models, it looks like to go about implementing this it would more closely track the GCE model?

**Comment by olemarkus** [comment]
Is the CSI driver used for Azure Disks?
K8s is looking to disable the in-tree disk plugins as of kubernetes 1.22 and we need to be ready for that. See #10777

**Comment by kenji-cloudnatix** [comment]
@olemarkus , I see. No, the CSI driver is not used for Azure Disks. Thanks!

**Comment by hakman** [comment]
kOps v1.20.0-beta.1 was just released today. The plan is to have another beta in 1-2 weeks and  the final release in in 3-4 weeks.
Please test the new Azure support as much as possible and report any issues you find.

**Comment by rifelpet** [comment]
Would folks find terraform support for azure clusters useful? If someone is interested in implementing it I can provide assistance.

**Comment by ngalantowicz** [comment]
> I wanted to test out kOps in azure. Where can I get the `kops` binary that supports the `--azure` args?

@finnje can build from master branch and or kops release v1.20.0-beta.1 supports azure features.

**Comment by hakman** [comment]
@kenji-cloudnatix Do you think we could also add an entry with recommended image in the channels file for Azure?
I guess the URN would be something like `Canonical:0001-com-ubuntu-server-focal:20_04-lts:20.04.20210315` and the entry would be similar to the GCE one:
https://github.com/kubernetes/kops/blob/5bb54a3d5ecdde86851993c8e823ba886cfcae75/channels/alpha#L77-L80

**Comment by kenji-cloudnatix** [comment]
I see. @hakman , let me take a look!

**Comment by alexivanoff** [comment]
Is it possible to configure **Availability zone** for master and node **Scale Sets**?
It tried to use "--zones eastus-1, eastus-2, eastus-3" but kops just created 3 Scale Sets without "Availability zone" settings.

**Comment by johngmyers** [comment]
Would it be possible for Azure to implement a `fi.Authenticator`/`fi.Verifier` pair so that instances can authenticate bootstrap requests to kops-controller using cloud-provided instance credentials?
