### ISSUE TITLE
Automate rotation of cluster secrets

### ISSUE THREAD

**Issue by yannh** [kubernetes/kops#10498]
This is a follow-up to https://github.com/kubernetes/kops/issues/8919

Kops clusters have an admin account - the credentials, stored in S3, can be exported with kops export kubecfg.
These credentials are not automatically rotated - the following procedure  describes how to do this manually https://kops.sigs.k8s.io/rotate-secrets/

This however requires running commands via SSH on every node, and is a "disruptive procedure".
Rotating secrets an employee has had access to when that employee leaves the company seems important, especially if those might give admin access to Kubernetes clusters. The current way to do so however, is quite inconvenient.

Could there be a kops command to automate this - ideally in a way that would not disrupt workloads running on the cluster? Or a CronJob that would rotate secrets regularly (every few weeks/months)?
I do appreciate this might be a pretty large undertaking.. is this automatable at all? Many thanks!

**Comment by olemarkus** [comment]
The steps involved to achieve this is documented here: https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

It is not that trivial to automate this, but at least it may be we can help facilitate the rotation.

**Comment by olemarkus** [comment]
One idea on how to go about this:
* make nodeup check a secret `old-ca`.
* If it exists, write the individual CAs + a bundle to the kubernetes cert location. If it doesn't, just write the regular CA to the bundle file.
* Use the bundle file for kube-apiserver, kube-scheduler etc

The above will ensure that stuff signed by both the old and the new CA works.

In addition, one would need a `kops toobox` command that would
* move existing CA to `old-ca`
* update service account tokens 
* rotate the entire cluster
* export a new `.kube/config` if applicable
* remove the old CA secret
* rotate again

The ordering above is quite different than the kubernetes docs, but that is primarily because they restart individual components, not roll the entire control plane. I think the ordering above should work.

**Comment by olemarkus** [comment]
Something like #10516

**Comment by johngmyers** [comment]
CA rotation is functional and documented in 1.22. The remaining work is to get rolling update to mark worker nodes as NeedsUpdate in all cases following the promotion of a new CA.

Rotating the symmetric secrets is still mostly manual.

**Comment by johngmyers** [comment]
CA and service account signer rotation automated in 1.22.

Automating rotation of the symmetric secrets would require kOps to manage individual Cilium and encryptionconfig keys instead of merely allowing the admin to upload the entire set as a single secret. I know of no current plans to do this.

Automating rotation of the docker pull secret is not possible as kOps is not the thing provisioning the credential into the docker registry.

Automating the Weave secret is not possible as Weave does not support graceful rotation of its secret.
