### ISSUE TITLE
Change networking option after cluster is built

### ISSUE THREAD

**Issue by cdelpinogeo** [kubernetes/kops#1071]
I wanted to change the networking option from kubenet to weave, I modified the cluster config using the `kops edit cluster` command and changed:

    networking:
     kubenet: {}

to

    networking:
     weave: {}

The changes are saved. When I run either `kops rolling-update cluster` or `kops update cluster` the change doesn't go into effect and the cluster config reverts to kubenet.

Thanks.

**Comment by chrislovecnm** [comment]
@cdelpinogeo so this is actually trick.  I am not sure that we can actually perform this task w/o some testing.  This is not implemented or tested from my knowledge, and we are dropping in more e2e tests that can help validate this.

Happy to get contributions always!

**Comment by justinsb** [comment]
So I think you're actually hitting https://github.com/kubernetes/kops/issues/123 - the symptom of that is fields 'reverting'.

I did run a test myself though, switching from `weave` to `kopeio` and it did work, except that I had to delete the weave daemonset first.   So it is possible, but we definitely have to fix some things.

Idea: have all our curated networking plugins use the same label, so that installing a new one will remove the previous plugin.

**Comment by vpm-bradleyhession** [comment]
Is there now an official process to change the networking driver on a cluster that is already built? Any supporting documentation around that?

Thanks,

**Comment by chrislovecnm** [comment]
I think we have another issue open about a fix that worked. We need it documented :(

**Comment by thomasjungblut** [comment]
@chrislovecnm can you point us to the issue? would be of great help :)

**Comment by merlineus** [comment]
@chrislovecnm is there any documentation about this now? Want to know how stable network switching now.

**Comment by 0verc1ocker** [comment]
@merlineus , still not very stable in `kops 1.10.0` . It worked for me in one cluster but then failed in the other. Potentially this could work flawlessly in staging but fail in production...

@chrislovecnm what is the other issue, can you link us to it?

**Comment by azelezni** [comment]
I just changed from calico to weave, half the pods couldn't start because ALL the nodes were `out of disk space` for some reason (but checking the nodes and they have 95% free space)
tried to change back to calico and ended up with an unusable cluster, had to destroy the entire cluster.

If changing network options after cluster creation is unsupported it should be removed from cluster spec and be made clear to only change network setting before cluster creation.

**Comment by 0verc1ocker** [comment]
@azelezni I did the same a few months ago. Moved from calico to weave-net.

Did you follow the migration procedures from switching from calico to weave-net?

**Comment by 0verc1ocker** [comment]
Basically if you create your cluster before kops 1.7 you need to reassign the pods and migrate their already assigned CIDR range before you can switch CNI.

These are the actual documented steps: 
https://github.com/kubernetes/kops/blob/af4df08b694e2a1f8814a7b3649060477be67c86/docs/upgrade_from_kops_1.6_to_1.7_calico_cidr_migration.md

**Comment by dobesv** [comment]
I've been searching around to figure out if this is possible.  Can I switch from kubenet to calico on a running cluster?

**Comment by Cryptophobia** [comment]
@dobesv , have you checked these instructions in the kops documentation: https://github.com/kubernetes/kops/blob/master/docs/networking.md#switching-between-networking-providers

That whole document has lots of information. I have switched from kubenet to weave to calico on a single cluster deployed by kops. The main thing to know is that there is a way to do it gracefully. For example, calico works with a separate component that is deployed on each node that updates iptables rules on each node. Sometimes you need to make sure manually that those rules are deleted before switching to another CNI. It is possible to have two CNIs with active components on a cluster, this is where major issue happen and downtime. (this must be avoided for graceful migration).

Calico also reserves an internal CIDR for pod IPs. 

It should be easier to switch FROM kubenet or weave TO calico because of this daemonset takes over iptables on each node. It will be a little harder to switch FROM calico TO kubenet or weave.

**Comment by dobesv** [comment]
Wow, thanks, I don't know how I missed that section!

**Comment by dobesv** [comment]
It does say "Switching from kubenet to a CNI network provider has not been tested at this time." but I guess I could test it myself.

**Comment by seilerre** [comment]
I still don't feel safe migrating the CNI. I want to change from Calico to Cilium. Of course I could deactivate the CNI managed by kOps altogether and install a vanilla Cilium, but I would have to manually ensure that Cilium requirements are met by the kOps created cluster.

It would be much better to keep the CNI management to kOps, especially as Cilium is now the default CNI. What is meant by "It is also possible to switch between CNI providers, but this usually is a disruptive change. kOps will also not clean up any resources left behind by the previous CNI, including the CNI daemonset." Does disruption mean a short downtime but the change is usually safe? Will kOps in a running cluster handle all needed config changes, like mounting epbf? 

Would it also be possible to follow the Cilium migration guide (https://docs.cilium.io/en/latest/installation/k8s-install-migration.html) node-by-node (tried this out already on a non kOps cluster)? What would happen if I then set "networking: cilium: {}"? Would a second Cilium version be deployed or could I deploy my first installation in a way understood and recognized by kOps?

**Comment by seilerre** [comment]
I still don't feel safe migrating the CNI. I want to change from Calico to Cilium. Of course I could deactivate the CNI managed by kOps altogether and install a vanilla Cilium, but I would have to manually ensure that Cilium requirements are met by the kOps created cluster.

It would be much better to keep the CNI management to kOps, especially as Cilium is now the default CNI. What is meant by "It is also possible to switch between CNI providers, but this usually is a disruptive change. kOps will also not clean up any resources left behind by the previous CNI, including the CNI daemonset." Does disruption mean a short downtime but the change is usually safe? Will kOps in a running cluster handle all needed config changes, like mounting epbf? 

Would it also be possible to follow the Cilium migration guide (https://docs.cilium.io/en/latest/installation/k8s-install-migration.html) node-by-node (tried this out already on a non kOps cluster)? What would happen if I then set "networking: cilium: {}"? Would a second Cilium version be deployed or could I deploy my first installation in a way understood and recognized by kOps?
