### ISSUE TITLE
Bump stable version of kubernetes - 1.4.7?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1150]
We probably should bump the kubernetes version recommended in stable to 1.4.7, or maybe 1.5.1

**Comment by chrislovecnm** [comment]
1.4.7 - we need to burn in 1.5.1 a touch

**Comment by Dmitry1987** [comment]
Hi, just to avoid creating new ticket - I edited my config with "kops edit cluster" and put a 1.5.1 instead 1.4.7  then applied changes, but it didn't work, i still had 1.4 version of k8s :(  ,  how is it possible to do proper upgrade with kops?  do I need to create manually some initial master AMI image, and then can swap it with old master? (i'm on aws)

thanks

**Comment by chrislovecnm** [comment]
Can I get the exact process that you followed?  Also need to be on master or the last release of `kops`.

**Comment by Dmitry1987** [comment]
Hi,
I created S3 bucket for kops, following official procedure. Then run "kops create cluster  clustername",
then used the cluster for few weeks or so (testing). Then tried to upgrade to 1.5.1 (I had 1.4.7 or something, don't remember exactly, already deleted all), so edited "kops edit cluster ${NAME}" , found there version number and changed it to 1.5.1 hoping that when "applied" it will upgrade cluster :) . But kops recreated my AWS autoscaling groups configs (because last time it created master and nodes with "launch configurations" of EC2, that had some settings for new nodes), I guessed that I need to re-launch EC2 instances with those new configs (because still had old cluster, nothing changed), deleted instances and "scaled" groups to get new ones.  But new EC2 master and nodes were same 1.4.7 (or was it 1.4.6 not sure.. I deleted all items related to it now, and created 1.5.1 cluster with "kubeadm", seems to be ok, but still, it's good to know how to use kops for cluster management, it's a nice tool).

How would you "officially" upgrade your production k8s cluster created with kops?   "kops update cluster ${NAME} --yes"   is what I did, but it didn't work.

Thanks

**Comment by chrislovecnm** [comment]
So a few notes

1. 1.5.x is supported in the latest release, but we have pending items such as docker support
2. We don't recommend running it in production yet, until we go through more of our certification process.
3. The upgrade cli changes the version of k8s to the version in our stable channel, we have a pending PR  docuemting this
4. Changing the version of k8s follows - edit, update, rolling-update. If this is confusing in the docs then we need to fix the docs

Thanks - appreciate the feedback

**Comment by justinsb** [comment]
Bumped to 1.4.7.

@Dmitry1987 no reason to avoid creating a separate issue for a distinct issue.

kops 1.5.0 (coming v soon) will support k8s 1.5.  kops 1.4.4 also supports 1.5, but doesn't have all the latest 1.5 settings.  At this point, I'd wait for kops 1.5
