### ISSUE TITLE
uniq tag name for nodes and masters using EC2 ?

### ISSUE THREAD

**Issue by fmedery** [kubernetes/kops#1184]
Hello, 
I would like to auto register my cluster nodes and masters with route53. As far as I know, Kops creates all the nodes with same tag name. Masters can also have tag if I have more then 1 master in a AZ.
Perhaps, Using the  instance group + uniq EC2 ID inside user data ?

Regards,

**Comment by chrislovecnm** [comment]
We already have some of the capability in dns-controller to set DNS. This has basic questions of maintain ability:

- what happens when something fails
- what happens when a new node is added
- what happens when a node fails
- what happens with a rolling update 

I understand the need. Can you fill in more details? Would u be able to assist?

**Comment by fmedery** [comment]
Something I like to achieve in general in AWS EC2 is the idea that TAG NAME = Server Hostname = DNS hostname. So I also know how to connect to a server if needed
I achieved this goal using tools like terraform, saltstack and cli53 (or lambda function at the moment).

With Kops When creating the cluster all the nodes have the same tag NAME and the hostname is the private IP. So my idea of being able to connect to any servers just by have its tag NAME is broken. Also tools like datadog, ... use the hostname of the node when sending metrics. So it is the unfriendly public IP hostname at the moment.

I hope this comment helps.

**Comment by chrislovecnm** [comment]
The comment helps, we still need to have the nodes tag themselves since the ASG cannot do it for them.  We always appreciate contributions!  If you are able to help out, would be much appreciated.
