### ISSUE TITLE
Terraform target doesn't work with Azure provider (--target terraform --out terraform )

### ISSUE THREAD

**Issue by alexivanoff** [kubernetes/kops#11951]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
I0708 11:55:36.732986   14963 featureflag.go:165] FeatureFlag "Azure"=true
Version 1.21.0 (git-a5bdc3359e544b314d5695b3ed596829313fc6e3)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 10.7.32.4:443: connect: network is unreachable

**3. What cloud provider are you using?**
Azure

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster --cloud azure --name test-1.k8s.local --zones eastus-1 --networking calico --azure-subscription-id "${AZURE_SUBSCRIPTION_ID}" --azure-tenant-id "${AZURE_TENANT_ID}" --azure-resource-group-name test-rg --azure-route-table-name test-route-table --azure-admin-user admin  --network-cidr 10.0.0.0/16 --target terraform --out terraform/kubernetes

**5. What happened after the commands executed?**
W0708 12:00:02.510285   14992 executor.go:139] error running task "ResourceGroup/test-rg" (9m56s remaining to succeed): could not find Render method on type *azuretasks.ResourceGroup (target *terraform.TerraformTarget)
I0708 12:00:02.510327   14992 executor.go:111] Tasks: 38 done / 51 total; 1 can run
I0708 12:00:02.510371   14992 executor.go:186] Executing task "ResourceGroup/test-rg": *azuretasks.ResourceGroup {"Name":"test-rg","Lifecycle":"Sync","Tags":{"KubernetesCluster":"test-1.k8s.local"},"Shared":true}
W0708 12:00:02.510505   14992 executor.go:139] error running task "ResourceGroup/test-rg" (9m56s remaining to succeed): could not find Render method on type *azuretasks.ResourceGroup (target *terraform.TerraformTarget)
I0708 12:00:02.510529   14992 executor.go:155] No progress made, sleeping before retrying 1 task(s)
I0708 12:00:12.513005   14992 executor.go:111] Tasks: 38 done / 51 total; 1 can run
I0708 12:00:12.513084   14992 executor.go:186] Executing task "ResourceGroup/test-rg": *azuretasks.ResourceGroup {"Name":"test-rg","Lifecycle":"Sync","Tags":{"KubernetesCluster":"test-1.k8s.local"},"Shared":true}
W0708 12:00:12.513216   14992 executor.go:139] error running task "ResourceGroup/test-rg" (9m46s remaining to succeed): could not find Render method on type *azuretasks.ResourceGroup (target *terraform.TerraformTarget)
I0708 12:00:12.513286   14992 executor.go:155] No progress made, sleeping before retrying 1 task(s)
I0708 12:00:22.515302   14992 executor.go:111] Tasks: 38 done / 51 total; 1 can run

**6. What did you expect to happen?**
terraform should be exported to terraform/kubernetes

**Comment by alexivanoff** [comment]
As far as I understand Azure is an unsupported provider for Terraform output. Do we have some tasks, maybe ETA to enable the support?

**Comment by rifelpet** [comment]
That is correct, the Terraform target for Azure has not yet been implemented. I don't know of anyone working on it at the moment, but PRs would be welcome. It should be pretty straight forward, just tedious due to the amount of changes needed.

Adding support should be as simple as:
* Adding a provider definition with version requirements [here](https://github.com/kubernetes/kops/blob/283080bc305a05870a832150231dc1505578dfe6/upup/pkg/fi/cloudup/terraform/target_hcl2.go#L104-L120) and [here](https://github.com/kubernetes/kops/blob/283080bc305a05870a832150231dc1505578dfe6/upup/pkg/fi/cloudup/terraform/target_json.go#L33-L99)
* Adding Azure to the list of supported providers [here](https://github.com/kubernetes/kops/blob/283080bc305a05870a832150231dc1505578dfe6/upup/pkg/fi/cloudup/apply_cluster.go#L90)
* For every [azuretask](https://github.com/kubernetes/kops/tree/master/upup/pkg/fi/cloudup/azuretasks) defining the structs that represent the terraform resource associated with the task, and implementing a RenderTerraform function that instantiates the struct and populates it with the desired values. [Examples](https://github.com/kubernetes/kops/blob/283080bc305a05870a832150231dc1505578dfe6/upup/pkg/fi/cloudup/awstasks/network_load_balancer.go#L663-L760) can be found in the other providers' tasks.

We use the terraform support in the other clouds to provide integration testing which could be its own task once initial terraform support for Azure has been implemented.
