### ISSUE TITLE
 Don't add basic auth creds if TLS data present

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1196]
https://github.com/kubernetes/kops/pull/1129

@amitkgupta was kind enough to add the above PR.  Tracking to ensure the work is done.

**Comment by justinsb** [comment]
This is where we store the username & password that can be used with the dashboard.  I agree it's silly, but it's the kube-up way.

**Comment by amitkgupta** [comment]
The generated kubeconfig has *two* users, one that has both TLS and basic
auth info, and the other has just basic auth info.

The basic auth info (for dashboard, etc) is duplicated. I'm suggesting it
should only be there once, and specifically suggesting to keep it on the
"xxxx-basic-auth" user entry in the kubeconfig, and removing it from the
main user entry since that already has TLS info (and is confusing because I
don't know if I'm authenticating as the basic auth user or the common name
in the cert).

If you see the function I'm modifying in the PR, the basic auth creds are
preserved by the stuff near the bottom of the function.
