### ISSUE TITLE
IAM policies and permission for KOPS Kubernetes cluster

### ISSUE THREAD

**Issue by ambar-centric** [kubernetes/kops#12037]
I have created kubernetes cluster in AWS using kOPs. I had given the following permissions to the kOPs user:
•	AmazonEC2FullAccess
•	AmazonRoute53FullAccess
•	AmazonS3FullAccess
•	IAMFullAccess
•	AmazonVPCFullAccess
Now the cluster is created, microservices are deployed and things are in steady state condition. Now what are the IAM roles / users and policies I need to create to manage the cluster. The kOPs user is having too much privileges almost akin to that of an administrator and that is a security risk it seems. Please provide some guidance.

**Comment by allen-mun** [comment]
You can find more restrictive IAM roles are found here
https://github.com/kubernetes/kops/tree/master/pkg/model/iam/tests
if you want to lock down the roles/policies more.

more notably 
https://github.com/kubernetes/kops/blob/master/pkg/model/iam/tests/iam_builder_master_strict.json
https://github.com/kubernetes/kops/blob/master/pkg/model/iam/tests/iam_builder_node_strict.json

There's also a doc on this here: https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md

**Comment by txsutton** [comment]
I have used the policy https://github.com/kubernetes/kops/blob/master/pkg/model/iam/tests/iam_builder_master_strict.json but it fails to start the services on the EC2 instances - if I allow kops to create the master instance-profile it is considerably larger.

I haven't taken them apart specifically to find out the exact differences but am I missing a stage - in my script I do a wget of the json file, create a policy using the json, create a role and attach the policy and then create the instance profile using that role.

Am I missing a step?

**Comment by olemarkus** [comment]
So you cannot directly take that json and apply it. For once, it is based on a specific kops spec and would not contain the permission to run certain addons or CNIs. It also contains specifics about where content is storered and the name of the cluster.

Now, the OP, I believe, is asking about the permissions needed for a kops (human) operator. Which, due to the need to be able to manage IAM, is close to a full operator.

This is different from the permissions that kops itself needs to operate (specifically the master/control plane nodes).

We are working in tightening the necessary AWS permissions for a kops cluster (specifically with running key components with specific IAM roles), which may be the reason why the _master_ branch policy is widely different from a cluster created with a released kops version.

**Comment by txsutton** [comment]
Thanks for the response.  Happy to add a new issue as I have just jumped on this one :) and I am new to kops so be gentle ;-)

To provide some context as suggested by https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md - I need to create specific named roles with a certain permission boundary due to restrictions imposed by our Enterprise Security Team for kops to operate.  Is there a method/doc I should be using to get the actions required for the master "kops-custom-node-role"

In an ideal world I would like to be able to dump the kops policies via a flag on kops create cluster which I can use to create/tweak my own custom roles and then use them as part of the kops update

**Comment by olemarkus** [comment]
The best way of doing this now would be to run  `kops update cluster --terraform` and look in the `out/data` folder.
