### ISSUE TITLE
Make static UIDs in wellknownusers.go configurable

### ISSUE THREAD

**Issue by wesselvdv** [kubernetes/kops#12041]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

I'd like the capability to change the static UIDs defined in https://github.com/kubernetes/kops/blob/e014fce41de10cf285c083a4e107caa4b75fa8eb/pkg/wellknownusers/wellknownusers.go#L22-L47 to be configurable. I am working in a large organisation that's using `ldap-sssd` to provide ssh access, unfortunately it's not possible for us to change the uid range of sssd, so we're getting conflicts on these static uids.

**Comment by johngmyers** [comment]
I think it's extremely unlikely we'd make this configurable. It would be a significant increase in complexity.

**Comment by ArchangelX360** [comment]
+1, we are having the same issue for a similar reason.

The significant increase in complexity is probably required here.
`kops` shouldn't just "hope" that there will be no conflicts with the users of the nodes.

Is there any workaround you would suggest @johngmyers?

**Comment by ArchangelX360** [comment]
> I don't believe that Debian, for example, lets you change the static UIDs of its system processes

I am not sure I understand. This issue is about making `kops` hardcoded UIDs configurable, especially because some environments where `kops`'s `nodeup.sh` would run will have those UIDs already taken.
Making `kops` hardcoded UID configurable would fix the problem.

---

In both @wesselvdv and my case, it seems that it is related to our company's LDAP having users of those UID.
A workaround I applied on the master nodes was to run the same `useradd` command with a `--non-unique` flag, creating a local user despite the LDAP existing one (I discourage this workaround as it enters the realm of unknown behaviour).

It worked but had to be applied manually, ssh-ing to the master nodes, and would have to be applied every time an EC2 instance is replaced. That is sub-optimal.

To automate this, I thought about using `kops` [`additionalUserData`](https://kops.sigs.k8s.io/instance_groups/#additionaluserdata), like that:
```
additionalUserData:
    # FIXME: this would only work if it was executed after `nodeup.sh`
    - name: useradd_workaround.sh
      type: text/x-shellscript
      content: |
        #!/bin/bash
        set -o errexit
        set -o nounset
        set -o pipefail

        # Context: https://booking.slack.com/archives/C022EK8N1L5/p1629710094173500

        # `kops` assumes those users are not existing and `kops-configuration.service` will fail with both:
        #  - "useradd: UID 10011 is not unique"
        #  - "useradd: UID 10012 is not unique"
        # Those two UIDs are already attached to some users in our setup.
        # So we are forcing a local user creation with `--non-unique`, so that `kops` does not try to create them
        echo "Applying 'kops' UID workaround"
        sudo /usr/sbin/useradd --non-unique -u 10011 -s /sbin/nologin -o kops-controller
        sudo /usr/sbin/useradd --non-unique -u 10012 -s /sbin/nologin -d /etc/kubernetes/kube-apiserver-healthcheck/secrets kube-apiserver-healthcheck
```

But `kops` appends `additionalUserData` scripts to the existing userdata, so, in practise those scripts run **after** `nodeup.sh`.
However, in this case we want them to run **before**, because `nodeup.sh` is the one needing this workaround.

I have a draft of an implementation to allow users of `kops` to prepend the custom userdata script **before** `nodeup.sh` userdata script here: https://github.com/kubernetes/kops/pull/12217, but I still think that `kops` should instead not hardcode those UIDs and make them configurable by the operators instead.

**Comment by ArchangelX360** [comment]
A working workaround: https://github.com/kubernetes/kops/pull/12217#issuecomment-931325705
