### ISSUE TITLE
Tagging Instance Profile isn't supported in all AWS Regions and blocks cluster update to 1.21

### ISSUE THREAD

**Issue by guydog28** [kubernetes/kops#12184]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.21.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.4

**3. What cloud provider are you using?**

AWS (Isolated Region)

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Trying to update a cluster from 1.20 to 1.21 fails (it was successful in 1.20) as 1.21 attempts to tag the instance profiles, and this feature is not support yet in this AWS region whose capabilities lag those of commercially available regions.

**5. What happened after the commands executed?**

invalid / operation not permitted, cluster update is blocked and cannot complete.

**6. What did you expect to happen?**

Successful cluster update.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

(nothing special here - same yaml as is working in 1.20 - just 1.21 is tagging where it didnt used to tag.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by guydog28** [comment]
@rifelpet I don't have access to it right now.  In the meantime, I'm pretty sure its happening [here](https://github.com/kubernetes/kops/blob/874d476cc4b9e376d488ba23ce0e60abd12937bc/upup/pkg/fi/cloudup/awstasks/iaminstanceprofile.go#L154), so maybe catching UnsupportedOperation and squashing it here would work.  I _think_ that is the exception that was thrown, but I can't verify for sure until I can try again.

**Comment by rifelpet** [comment]
That could work. I don't see an UnsupportedOperation error type in the IAM API (though I do see it in the SQS and KMS APIs) if you have a chance it would be useful to see the exact error message being returned by IAM. Based on [these docs](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/handling-errors.html), If we have a `Code` or `Message` to look for, that would help. Even the output of `aws --debug iam tag-instance-profile --instance-profile-name foo --tags "Key=foo,Value=bar"` would be sufficient.

I checked govcloud and it does support tagging instance profiles. I don't know about aws-cn, but it might also be worth asking support if they have a timeline for adding tagging support to the iso partitions. Maybe its not worth adding a temporary workaround.

**Comment by guydog28** [comment]
Will do.  I should be able to get you that data tomorrow.

**Comment by guydog28** [comment]
@rifelpet Was the error info I provided sufficient?  Checking in on this ticket.

**Comment by rifelpet** [comment]
@guydog28 gentle ping on https://github.com/kubernetes/kops/pull/12629#issuecomment-954268547

**Comment by mikeinton** [comment]
We are having a similar issue but in our case, IAM instance profile tagging is not allowed by our company's governance policies as they are reserving it for a future based access control feature.  During cluster updates, we get AccessDenied errors when performing `iam:TagRole` and our only workaround for it has been to self manage IAM via `spec.iam.profile` on our instance groups and using --lifecycle-overrides during updates.

Are the instance profile tags here required?  Could there be a way to turn them off so that we can have kops manage IAM for us once again vs trying to keep roles/policies updated manually?

**Comment by rifelpet** [comment]
@mikeinton if you're able to check out this comment: https://github.com/kubernetes/kops/pull/12629#issuecomment-954268547 we have a potential fix but need someone with access to the iso regions to confirm it works.

**Comment by guydog28** [comment]
@rifelpet i haven’t had a chance to test it yet, but I hope to next week.

**Comment by rifelpet** [comment]
Great, thank you.

If you wouldn't mind, we're also curious if the DescribeAutoScalingGroups API supports the recently-introduced tag filtering in the iso regions too (https://github.com/kubernetes/kops/pull/12659).

`aws autoscaling describe-auto-scaling-groups --filters Name=tag-key,Values=KubernetesCluster` would confirm/deny for us.

**Comment by guydog28** [comment]
@rifelpet `Unknown Option --filters Name=tag-key,Values=KubernetesCluster`

**Comment by rifelpet** [comment]
oh, you may need to upgrade your aws cli to a more recent version with the filter support.

**Comment by guydog28** [comment]
@rifelpet I receive the following errors:
```
error running task "SecurityGroup/api-elb.<clustername>": "Invalid Action: The action DescribeSecurityGroupRules is not valid for this web service.  status code: 400" (repeated for 2 elbs and 6 igs)
error running task "VPCAmazonIPv6CIDRBlock/AmazonIPv6": error associating Amazon IPv6 provided CIDR block to VPC: MissingParameter: the request must contain the parameter cidrBlock"  status code: 400
error running task "IAMRolePolicy/masters.<clustername>": "error creating/updating IAMRolePolicy: MalformedPolicyDocument: Partition "aws <- wrong partition" is not valid for resource "arn:aws:ec2:*:*:volume/*""  status code: 400
error running task "NetworkLoadBalancer/api-<clustername>": error creating NLB listener: InvalidConfigurationRequest: Target group 'arn:<partition>:elasticloadbalancing:<region>:<account>:targetgroup/tcp-<clustername>-<generated>/<generated>' is in a different VPC than load balancer 'arn:<samepartition>:elasticloadbalancing:<sameregion>:<sameaccount>:loadbalancer/net/api-<clustername>-<generated>/<generated>'  status code: 400
error running task: "Route/::/0": error creating Route: missing mandatory parameter: destination-cidr-block or destination-prefix-list-id

```

**Comment by guydog28** [comment]
As for the aws cli command, I reran with newer cli and received:
```
An error occurred (ValidationError) when calling the DescribeAutoScalingGroups operation: The Filters parameter isn't supported. Removed this parameter from your request and try again.
```

**Comment by guydog28** [comment]
@rifelpet gentle ping on https://github.com/kubernetes/kops/issues/12184#issuecomment-973016504.

**Comment by rifelpet** [comment]
Hi @guydog28 apologies for the delay. After some deliberation we decided that if kops uses any networking functionality not supported in the iso partitions, the path forward will be to use externally-managed networking resources. For example, create the VPC, subnets, route tables and routes outside of kops and add their IDs to the ClusterSpec as mentioned in the [docs](https://kops.sigs.k8s.io/run_in_existing_vpc/#shared-subnets).

This case will address the `VPCAmazonIPv6CIDRBlock` and `Route` errors you're receiving.

The `IAMRolePolicy` should be fixed in a more recent kops build. 

The `NetworkLoadBalancer` error sounds like kops could ignore the `InvalidConfigurationRequest` error which would only happen on the iso partition.

The `SecurityGroup` error is unfortunate and we'll have to think about how to handle this. You may be able to create your own security groups similar to the other networking resources and add them to the various `SecurityGroupOverride` fields in the cluster spec. I'm not sure if that will be sufficient though.

If you're not receiving any error on the InstanceProfile tasks, then I think we can go ahead and merge https://github.com/kubernetes/kops/pull/12629
