### ISSUE TITLE
Instruct users to create NS records when fully within AWS

### ISSUE THREAD

**Issue by matthewadams** [kubernetes/kops#1227]
https://github.com/kubernetes/kops/blob/master/docs/aws.md#a-setting-up-dns-for-your-cluster-with-aws-as-your-registrar says just to create a hosted zone.  That's not enough.  You also have to perform in AWS what you describe in the last bullet point in step https://github.com/kubernetes/kops/blob/master/docs/aws.md#c-setting-up-a-subdomain-for-clusters-with-another-registrar-while-keeping-your-top-level-domain-the-same

**Comment by chrislovecnm** [comment]
👍 

Thanks.  If you want to take a stab at updating the document that would be much appreciated.

**Comment by kris-nova** [comment]
Quick question @matthewadams 

The last bullet point in https://github.com/kubernetes/kops/blob/master/docs/aws.md#c-setting-up-a-subdomain-for-clusters-with-another-registrar-while-keeping-your-top-level-domain-the-same reads

```
You will now go to your registrars page and log in. You will need to create a new subdomain, and use the 4 NS records listed above for the new subdomain. This MUST be done in order to use your cluster. Do NOT change your top level NS record, or you might take your site offline.
```

Is this what you are referring to? Because logging into another registrar's page doesn't make very much sense if you are using AWS as your registrar 😉

**Comment by matthewadams** [comment]
Yes, that's what I was referring to, but it's under section (C), not
section (A).  So on first read, it's easy to miss.

**Comment by matthewadams** [comment]
We started to craft a PR containing a second command line to execute the NS record creation for the subdomain in the root domain's DNS entries (similar to the shell command already given at https://github.com/kubernetes/kops/blob/master/docs/aws.md#a-setting-up-dns-for-your-cluster-with-aws-as-your-registrar), but ended up spending too much time on it & gave up.  It might need a script instead of a single `aws route53` command line invocation.

**Comment by bellkev** [comment]
I had some related confusion, I think due to the "registrar" terminology. Say I registered example.com with GoDaddy and set it up to use route53 nameservers. Now I want to use k8s.example.com for my cluster. The docs lead me to believe that I need to follow the steps in option (C) because I have a non-AWS registrar, but I actually do need to create a new hosted zone in Route53. (And I can't change add the NS record in GoDaddy, because it says "your nameservers aren't managed by us.")

Shouldn't "registrar" be replaced with "nameservers" in a few places?

**Comment by kris-nova** [comment]
I think it's a great idea. We originally wrote these very one sided so any feedback and improvement we can get on making this easy is greatly appreciated.

This is by far our most viewed piece of documentation. @bellkev would you be interested in opening a PR with your suggested changes? Or anyone for that matter?

If not I will open something up shortly to tidy some of this up.

**Comment by bellkev** [comment]
I can try to make a PR soon. If I don't open it within 2-3 days though, please don't wait for me.
