### ISSUE TITLE
Validate that we create a bastion IG when we do `kops create cluster --topology private`

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1232]
Reports that we don't.  Ensure we have test coverage.

**Comment by justinsb** [comment]
We do, but only if we specify `-bastion`.  I believe that's right, right @kris-nova ?

Tests in #1271

**Comment by brunowoo** [comment]
Either option seems fine, as long as it works as expected. Currently both the docs here in Github as  in the CLI help state that a bastion will be created by default for a private topology (as mentioned in https://github.com/kubernetes/kops/issues/1276), which is not the case.

**Comment by kris-nova** [comment]
So the original discussions are here https://github.com/kubernetes/kops/pull/906#issuecomment-264214092 and here https://github.com/kubernetes/kops/issues/1030

Basically we had discovered we had 3 uses cases with `--bastion`.. and though it was a good idea to make the `--bastion` flag accept a signed integer value. See the following use cases:

### 1 No IG

We completely ignore all bastion, and bastion related infrastructure. Do not create an instance group.

```
--bastion -1
```

### 2 Define an IG, but do not launch anything.

Create the instance group, but set the node counts to 0. We want it there so we can flip the bastion on/off.

```
--bastion 0
```

### 3 Define an IG, and launch some number of servers. Default:`--bastion 1`

Create the instance group, and set the node counts greater than 0. Default to `--bastion 1` if the user decides not to pass the `--bastion` flag

```
--bastion >0
```


Yes. We really do need to update the docs, whenever and however we implement this.

What are your thoughts?

**Comment by zmerlynn** [comment]
In general, I'm not a huge fan of negative flag values for something like
this. They're sometimes too subtle and have people glancing at docs to
remember. I'd rather have split flags, e.g  --bastion={true, false} and
--bastion-ig-size=N

My bikeshed colors / $0.02.

On Dec 28, 2016 4:33 AM, "Kris Nova" <notifications@github.com> wrote:

So the original discussions are here #906 (comment)
<https://github.com/kubernetes/kops/pull/906#issuecomment-264214092> and
here #1030 <https://github.com/kubernetes/kops/issues/1030>

Basically we had discovered we had 3 uses cases with --bastion.. and though
it was a good idea to make the --bastion flag accept a signed integer
value. See the following use cases:
1 No IG

We completely ignore all bastion, and bastion related infrastructure. Do
not create an instance group.

--bastion -1

2 Define an IG, but do not launch anything.

Create the instance group, but set the node counts to 0. We want it there
so we can flip the bastion on/off.

--bastion 0

3 Define an IG, and launch some number of servers. Default:--bastion 1

Create the instance group, and set the node counts greater than 0. Default
to --bastion 1 if the user decides not to pass the --bastion flag

--bastion >0

Yes. We really do need to update the docs, whenever and however we
implement this.

What are your thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kops/issues/1232#issuecomment-269471116>,
or mute
the thread

**Comment by kris-nova** [comment]
@zmerlynn 

It just seemed like easier logic to implement, and the `-1` use case seems like a bit of a one-off, so anyone using it, will know very well what they want.

Personally, I am not attached to any implementation means, I just wanted to voice the 3 use cases I knew about. Your example seems fine, although I would probably just say that the user can use `--bastion` to turn the instance group on/off and then edit the cluster spec if needed to change the count..

**Comment by justinsb** [comment]
So our current logic is:

* we don't create a bastion by default, even with `--topology private`.  Many people running this topology have a VPN and don't need/want a bastion
* --bastion is a boolean flag that creates an instance group.  The instance group can easily be edited just like any instance group.

I think this is reasonable.  Creating a bastion by default would be handy for me as a developer, but I think it is an easy option, easy to type `kops create ig bastion --role bastion` if I forget, and many of the real-world users of private topologies won't want a bastion.
