### ISSUE TITLE
Cluster does not validate after distrusting old keypair

### ISSUE THREAD

**Issue by rahulshinde11** [kubernetes/kops#12343]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
1.22.0-beta.1
 ```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
 ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"} 
```
**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops distrust keypair all
kops update cluster --yes
kops export kubecfg --admin
kops rolling-update cluster --yes
```
Following instructions from [here](https://kops.sigs.k8s.io/operations/rotate-secrets/)

**5. What happened after the commands executed?**
when running kops rolling-update cluster --yes 
Cluster did not validate within 15m0s

**6. What did you expect to happen?**
Cluster to be validated and the old keys to stop working.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:

spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-south-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.18.20
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-south-1a
    type: Public
    zone: ap-south-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
  name: master-ap-south-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-ap-south-1a
  role: Master
  subnets:
  - ap-south-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210720
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-ap-south-1a
  role: Node
  subnets:
  - ap-south-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
The dns is not updated in route53 when I manually changed the A records the API starts working. 
But still unable to get the other instance group.

**Comment by rahulshinde11** [comment]
when the old kubernetes-ca is distrusted, the node do not join the cluster.
kube-proxy in nodes fails with unauthorized,

**Comment by ederst** [comment]
I have experienced the same, after I tried to get rid of the keypair update showing up for `kubelet` and `kube-proxy`:

```
Will modify resources:
  Keypair/kube-proxy
        Signer                   id:cn=kubernetes -> name:kubernetes-ca id:cn=kubernetes-ca
        LegacyFormat             false -> false

  Keypair/kubelet
        Signer                   id:cn=kubernetes -> name:kubernetes-ca id:cn=kubernetes-ca
        LegacyFormat             false -> false
```

This is currently showing up on clusters we updated from kops 1.20 to 1.22, and I tried to rotate the secrets to get rid of this. But by the looks of it, the keypairs for `kubelet` and `kube-proxy` are not updated (https://github.com/kubernetes/kops/blob/0bc00046adc71b0166c4ebd93503ee83ab9c9bbb/upup/pkg/fi/fitasks/keypair.go#L180):

```
W1119 09:48:20.550670    4804 keypair.go:180] Ignoring changes in key: {"Name":null,"alternateNames":null,"Lifecycle":"","Signer":{"Name":"kubernetes-ca","alternateNames":null,"Lifecycle":"Sync","Signer":null,"subject":"cn=kubernetes-ca","type":"ca","oldFormat":false},"subject":"","type":"","oldFormat":false}
W1119 09:48:20.587201    4804 keypair.go:180] Ignoring changes in key: {"Name":null,"alternateNames":null,"Lifecycle":"","Signer":{"Name":"kubernetes-ca","alternateNames":null,"Lifecycle":"Sync","Signer":null,"subject":"cn=kubernetes-ca","type":"ca","oldFormat":false},"subject":"","type":"","oldFormat":false}
```

It seems that creating/adding keypairs for `kubelet` and `kube-proxy` it is not supported (this also does not work on clusters freshly created with 1.22):

```
❯ kops create keypair kubelet                                                                                        
Error: adding keypair to "kubelet" is not supported
```

@zetaab  also started a discussion on slack (https://kubernetes.slack.com/archives/C8MKE2G5P/p1636736319138200).

So the keypairs probably need to be deleted (maybe manually since there is no `kops delete keypair`)?

**Comment by ederst** [comment]
So I tried to follow through the instructions of https://kops.sigs.k8s.io/operations/rotate-secrets/ on a kops clusters created with 1.22.1 and kubernetes 1.21.5 on Openstack, and it did not really work:

* When doing step 1 I had to wait a bit for kops recognizing that a `rolling-update` is necessary (which is ok, because the state store is polled every now and then)
* When doing step 3, there were no changes detected by kops for doing the rolling update, so I proceeded to step 4 and 5 which resulted in the rolling update not being able to be carried out b/c the newly promoted cert was still not recognized I guess and i got a `Unable to connect to the server: x509: certificate signed by unknown authority` response.
* Then I tried to `--force` a rolling update, but the first control plane instance which was taken down, was not able to join.
* This is when I decided to roll back the changes of step 5 and then I needed to recreate the cluster without validation (`--cloudonly`), it was not possible any other way. Then the cluster came up again.
* After this, which I think was essentially step 3 with `--force --cloudonly` I did step 4 and 5 again, now the old kubeconfig does not work and the new one does (as expected). However, the `rolling-update` still does not show anything in `NEEDUPDATE`, thus no rolling update was executed.

I still have to try what happens now, when I try to force a rolling update...

But, at least for me, the documentation does not work as expected.

**Comment by johngmyers** [comment]
I think it only works for AWS and Kubernetes >= 1.19

**Comment by ederst** [comment]
I might have a graceful solution (no cluster downtime) which involves deleting the kubelet and kube-proxy keypair from the state store (unfortunately there is no `kops delete keypair`), distrusting the old kubernetes-ca, updating the cluster, and first rolling out the workers/nodes and then the control plane (both with `--force`). Unfortunately this will lead to kops trying to update the kubelet and kube-proxy keypairs like this:

```
Will modify resources:
  Keypair/kube-proxy
        Signer                   id:cn=kubernetes-ca,serial=7032212538987717337648076037 -> name:kubernetes-ca id:cn=kubernetes-ca
        LegacyFormat             false -> false

  Keypair/kubelet
        Signer                   id:cn=kubernetes-ca,serial=7032212538987717337648076037 -> name:kubernetes-ca id:cn=kubernetes-ca
        LegacyFormat             false -> false

Must specify --yes to apply changes
```

This annoys me. :|

Anyhow, I'll provide details after the weekend, when I have time to test my procedure again.

**Comment by ederst** [comment]
Thx @johngmyers, will test this ASAP.

**Comment by ederst** [comment]
Tested this with a cluster which we updated from kops 1.20 to 1.22, and now kops does not want to modify the "ca" -> "kubernetes-ca"  and/or the "kubernetes-ca,serial=... -> kubernetes-ca" of the "kube-proxy" and "kubelet" keypairs anymore. Yay!

However, following the instructions of https://kops.sigs.k8s.io/operations/rotate-secrets/ I was not able to get past step 3), since the first control plane instance which was replaces was not able to join the cluster (have not found an error other than "context deadline exceeded" in the api container, which was not able to start due to this).

Then I was not able to roll back the changes, becaue promoting the old "kubelet" and "kube-proxy" secret was not possible ("Promoting not supported").

Also, I had to use "--force" for "kops rolling-update" otherwise nothing would have been rolled out (no changes detected).

Rolling everything out with "--force --cloudonly" however seems to do the trick. Although, this is not really graceful. ;)

Might try this again with another of our updated clusters, when I have time. Maybe I did something wrong.

**Comment by johngmyers** [comment]
When rolling back, running an update after demoting kubernetes-ca should cause kubelet and kube-proxy to be reissued from the old CA. It's not intended that you demote the client certs directly.

**Comment by ederst** [comment]
> When rolling back, running an update after demoting kubernetes-ca should cause kubelet and kube-proxy to be reissued from the old CA. It's not intended that you demote the client certs directly.

Yeah, figured this out after I wrote my comment -.- sry about that
