### ISSUE TITLE
Heapster dies after being created

### ISSUE THREAD

**Issue by osxi** [kubernetes/kops#13]
After using `wget` to save upup/addons/monitoring-standalone/heapster-controller.yaml and using `kubectl create -f heapster-controller.yaml`, Heapster will run for a while and then disappear without any errors from `kubectl logs`.

I ssh'd into the master node and noticed that there wasn't an /etc/kubernetes/addons/cluster-monitoring dir before, during, or after doing the above steps.

**Comment by justinsb** [comment]
OK I believe I have figured this out now....

The kube-addons manager will "manage" anything that is:

1. in the kube-system namespace
2. has the `kubernetes.io/cluster-service: "true"` label

It synchronizes with /etc/kubernetes/addons.

So if you `kubectl create` something matching 1 and 2, but it is in not in /etc/kubernetes/addons, then it will be deleted.

The trick is to delete the cluster-service label, from both the controller & the service, e.g.

```
--- a/upup/addons/monitoring-standalone/heapster-controller.yaml
+++ b/upup/addons/monitoring-standalone/heapster-controller.yaml
@@ -5,7 +5,6 @@ metadata:
   namespace: kube-system
   labels:
     k8s-app: heapster
-    kubernetes.io/cluster-service: "true"
     version: v1.1.0.beta2
 spec:
   replicas: 1
diff --git a/upup/addons/monitoring-standalone/heapster-service.yaml b/upup/addons/monitoring-standalone/heapster-service.yaml
index 31e8b96..8c793a4 100644
--- a/upup/addons/monitoring-standalone/heapster-service.yaml
+++ b/upup/addons/monitoring-standalone/heapster-service.yaml
@@ -4,7 +4,6 @@ metadata:
   name: heapster
   namespace: kube-system
   labels: 
-    kubernetes.io/cluster-service: "true"
     kubernetes.io/name: "Heapster"
 spec: 
   ports: 
~/k8s/src/k8s.io/kops/upup/addons/monitoring-standalone  (master) > 
```

That's a workaround and I'm going to figure out a better way to manage these addons.  We don't really want to be putting them in a directory on "the master" - it doesn't make sense with HA master, and it doesn't really make sense because we have a reliable data store in the api server anyway.

**Comment by justinsb** [comment]
We have docs for the new recommend way now: https://github.com/kubernetes/kops/blob/master/docs/addons.md

We're also curating some addons with the cluster-service annotation removed.

Please do try it out and let me know if any problems!

Going to close; please reopen if problems continue.

**Comment by bboreham** [comment]
Just to note that I had a very similar symptom today; had `kubernetes.io/cluster-service: "true"` but did not have `namespace: kube-system`.  Removing the `cluster-service` label made it work.
