### ISSUE TITLE
Add hubble-ui as an option for cilium when installing hubble

### ISSUE THREAD

**Issue by allen-mun** [kubernetes/kops#13025]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
With hubble-ui v0.8.0+, it seems like hubble-ui now supports TLS (from [this PR](https://github.com/cilium/hubble-ui/pull/151/files), release link: [here](https://github.com/cilium/hubble-ui/releases/tag/v0.8.0).  It looks like the reason for not installing hubble-ui was for a fix in the v0.7.7 hubble-ui image (from [this](https://github.com/kubernetes/kops/pull/11314#issuecomment-830113766)).

For us, hubble-ui would provide an easier and more visible solution than using hubble-cli to debug network issues.
**2. Feel free to provide a design supporting your feature request.**

**Comment by olemarkus** [comment]
The reason we don't support hubble-ui is because webapps are a bit tricky. They don't belong in kube-system, they tend to be exposed outside of the cluster and thus has a different security profile. They require external TLS, DNS, and they perhaps should use an Ingress. They perhaps need an authenticating/authorizing proxy.

Luckily it is now easy to install the hubble ui alone using the cilium helm chart.

**Comment by allen-mun** [comment]
Alright, without adding hubble-ui to kops, is it possible to change hubble-relay to toggle TLS since hubble-ui now supports it?

Line referenced here: https://github.com/kubernetes/kops/blob/3245c6d817399fb5b63efa575e1004719dcb19fe/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12-v1.9.yaml.template#L269

**Comment by olemarkus** [comment]
Yes. kOps 1.24 will probably switch this one to enable TLS.

**Comment by olemarkus** [comment]
I think it is quite safe to say we won't support this as an addon.
We have also added docs on how to install hubble on kops. See https://kops.sigs.k8s.io/networking/cilium/#hubble-ui

/close
