### ISSUE TITLE
Digital ocean should have the CSI plugin installed and managed by kops

### ISSUE THREAD

**Issue by zak905** [kubernetes/kops#13480]
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Digital Ocean installation comes without CSI plugin which makes it somehow not production ready. The CSI plugin installation is straightforward but can be tricky because it needs a CA to generate a certifcate to be used by the `ValidatingWebhookConfiguration`

More details in the official repo: https://github.com/digitalocean/csi-digitalocean

**2. Feel free to provide a design supporting your feature request.**

the CSI plugin should be installed at cluster creation time, and also should be part the kops managed cluster addons.

**Comment by hakman** [comment]
@srikiz Is this something planned?

**Comment by hakman** [comment]
That would be really nice. Thanks @srikiz! :)

**Comment by timoreimann** [comment]
A quick thought:

The validating web hook is needed to validate snapshots only and otherwise does not impact the functionality of the CSI driver. In a first step, we could consider doing without the web hook and document the constraints clearly so that we can ship an initial version of the CSI driver more quickly.

Afterwards, we could bundle cert-manager along the CSI driver to provision and manage the necessary certificates for the web hook.

**Comment by hakman** [comment]
That's a great plan.
BTW, kOps already bundles cert-manager for this kind of thing. https://github.com/kubernetes/kops/pull/10545 should give you an idea on how it is used for metrics-server.
