### ISSUE TITLE
Unable to update to kops 1.23.2 from 1.22 due to private registry configuration

### ISSUE THREAD

**Issue by ryan-dyer-sp** [kubernetes/kops#13681]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.23.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.21

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops replace -f cluster.yaml
kops get assets --copy
kops update cluster --yes
kops rolling-update cluster --yes

**5. What happened after the commands executed?**
First master terminated.  New master starts but is unable to start any pods as containerd does not have permissions to pull the private/pause:3.6 image (unauthorized)

**6. What did you expect to happen?**
Works as before

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
I believe the key here is in that we use a private registry and copy assets from the public to our private registry.  With kops 1.22, the pause image is not listed as an asset.  I'm assuming this means that with these clusters we still pull the pause image from (whichever) public registry instead of our private one.  With 1.23, the pause image now shows up as an asset and gets copied to our registry.  
```yaml
  assets:
    containerRegistry: private.domain:5555
```

**Comment by olemarkus** [comment]
I think after we have moved to the new host containerd format, we should parse the docker secret and write the credentials to the host file instead of writing out the docker.json. Kubelet has the code for this as that is basically what it does when passing the credentials over CRI. So those interested in this can take a look at the [k/k credentialsprovider package](https://github.com/kubernetes/kubernetes/tree/master/pkg/credentialprovider), which contains the code for parsing docker files (docker.go) and passing it on to containerd over CRI. Then see how this can be ported to nodeup.
