### ISSUE TITLE
Remove --networking=cni suggestion for private topologies

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1373]
`Invalid networking option kubenet. Currently only '--networking cni', '--networking kopeio-vxlan', '--networking weave', '--networking calico' are supported for private topologies`

One of those is a _lot_ more work than the others ;-)

**Comment by adamperelman** [comment]
@justinsb is there any documentation to help pick between these different options? I've found https://kubernetes.io/docs/admin/networking/#weave-net-from-weaveworks but haven't been able to figure out which options might be best for different use cases. 

For example, in my case I want to pick the simplest possible option so that I can set up a k8s cluster using `kops` with a `private` topology. Any advice?
