### ISSUE TITLE
Allow to configure placement groups for kops managed ASGs

### ISSUE THREAD

**Issue by minkimipt** [kubernetes/kops#14162]
/kind feature

There are cases when some k8s nodes belonging to the same ASG are dedicated to a specific task.

For instance an ASG of 3 nodes, each running a copy of a critical application. Kubernetes gives us full control of instance placement to those nodes by means of anti affinity rules. But what if those 3 nodes happen to be on the same rack in the AZ and there's a power outage. Those nodes would be impacted all at once in that case.

AWS supports placement groups, [spread placement groups](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html#placement-groups-spread) being exactly the solution for the example I've given. Placement groups can be also configured in ASGs and it would be useful to be able pointing kops managed ASGs to user-configured placement groups. 

Kops could accept a flag that would allow it to refer to a placement group at time of IG creation.

Something similar was already discussed in https://github.com/kubernetes/kops/issues/367

**Comment by olemarkus** [comment]
What's the reason for not relying on topology spread constraints (or even anti affinity) for these cases?

**Comment by hakman** [comment]
I think we had this discussion before and the main concern was the limitation at 7 instances / AZ for a spread placement group. If added, there should be at least a validation that max IG instances <= 7.

**Comment by minkimipt** [comment]
> What's the reason for not relying on topology spread constraints (or even anti affinity) for these cases?

Anti affinity would guaranty that pods are not scheduled on the same nodes. Topology spread constraints could help to guaranty that those pods are scheduled in different AZs. In our use case we'd like to have the pods to be scheduled in the same AZ. And we have no way to determine whether k8s nodes belonging to the same AZ are running in the same rack or not. 

Valid point from @hakman that it would be not more than 7 instances in such case. But it could still be a useful feature even with that constraint.

**Comment by olemarkus** [comment]
I am a little bit concerned that you'll architect yourself into a corner here. You can definitely do affinity to ensure you are running in the same AZ but on different instances. These instances may be in the same rack or even the same instance but:
* in the case of scheduled downtime, node termination handler will ensure graceful migration
* in the case of non-graceful downtime of the instance, it varies:
  * You could be lucky and get a shut-down that allows pods to move anyway using the graceful ndoe shutdown functionality.
  * You could not be lucky and your pods are stuck until they get rescheduled
  * The problem is not isolated to the rack, but larger portions of the AZ

All non-graceful EC2 incidents I've experienced have affected more than one rack. So it's mainly graceful/scheduled downtime where placement groups have had good effect. But in these cases, the K8s mechanisms we already have provide graceful migration of pods well before the instances are shut down.

**Comment by minkimipt** [comment]
@olemarkus thanks for you detailed reply. It really makes sense for the hosts that are used to host some workloads.

I'll elaborate more about our usecase. Because I find my first description is incomplete. I tried to compose the feature request so, that it would be applicable to a wider range of use-cases, but it appears that my description didn't include our own use case for which I'm requesting it.

We are using some k8s nodes not to run workloads per se, but rather to work as dedicated targets for traffic hitting NodePort services. We are using NodePorts quite extensively. We expose pods that are running customer databases via NodePort services and to allow customers to reach their services, we create route records in Route53 that point to a fraction of k8s nodes (not to bloat the number of hosts in a resource record we limited the number of nodes to 5).

Some time ago when we introduced multi-az support to our cloud, which revealed one issue. When users are accessing their databases via a NodePort service, they will likely hit a node in a different AZ, and traffic will go inter-az, incurring unnecessary cost. That's why we decided to set aside a number of small profile hosts, which are going to be used only to forward traffic - 2 such hosts per AZ. Those dedicated hosts are being managed as a different IG. Those hosts are totally sufficient to forward all of the traffic they need to deal with. But we have no way of making sure that they don't accidentally land on the same AWS host, hence we are at risk of losing them all at once if some rack-level outage is going to happen.

**Comment by olemarkus** [comment]
I have a project with a somewhat similar problem, and we are looking at topology aware hints as a solution rather than your AZ-specfic IGs: https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/
Since kube-proxy is the consumer of the hints, this should work for NodePort services as well.

Where I am at at the moment is to determine how the hints affect these flows and how effective this really is.

It may be we'll accept a PR for placement groups though, but I suspect none of the maintainers will have the time to actively work on it themselves.

**Comment by minkimipt** [comment]
I looked at that feature and as I understood, it's primarily intended for traffic flows that stay within the cluster. Our services usually have only one endpoint (which is a single pod running postgre database). So topology aware hints aren't going to help in our case.

**Comment by olemarkus** [comment]
As I understand it, this will happen:

Something connects to the local kube-proxy, either by NodePort (external load balancers uses NodePort too) or by ClusterIP. KubeProxy then fetches a list of endpoints and filters endpoints by _its own zone_. 

So given that it is actually kube-proxy that tries to avoid the inter-AZ traffic, it should work regardless of how the traffic hits kube-proxy.
