### ISSUE TITLE
Some bastion resources left behind after cluster delete

### ISSUE THREAD

**Issue by AlexLast** [kubernetes/kops#1427]
When creating a cluster with the following options:

--topology=private --bastion=true --networking=weave

The following bastion resources are not removed by a delete cluster:

- DNS record in R53 for bastion that points to the bastion ELB (e.g bastion-cluster-name.domain.com)
- IAM role for bastions (bastions.cluster-name.domain.com)
- In some cases unattached elastic IP's are not released (not sure on what this case is)

**Comment by justinsb** [comment]
Thanks for the bug report - you're absolutely right.

I'm going to open a separate issue for the elastic IPs, as I think it's a little different.  Because we can't tag elastic IPs, it's pretty difficult to make sure we never leak them.  I suspect we're actually leaking elastic ips sometimes if bringup fails.

**Comment by sstarcher** [comment]
@chrislovecnm we are still seeing bastion-CLUSTER DNS entries after a cluster deletion with kops 1.5.0-beta1
