### ISSUE TITLE
kops cluster status was reported incorrectly 

### ISSUE THREAD

**Issue by devzer01** [kubernetes/kops#14428]
/kind bug

**1 Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)

**2 Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4"

**3.AWS

**4. kops get instances

**5. ![detached-state](https://user-images.githubusercontent.com/4328569/196339601-7abbf223-8b5a-4935-8bfd-77384be228fc.png)

**6. all instances to be attached and instance groups reflected here are what's on the config
![kops-status](https://user-images.githubusercontent.com/4328569/196339796-0073c722-b2df-4895-b44b-a95018b2723b.png)

## AWS instance type availability
this is the c3.4xlarge 
![unavailable](https://user-images.githubusercontent.com/4328569/196339829-df971110-a154-4242-8d09-d7b80d0f32ea.png)

### notes
- the instance type requested was not available in ap-southeast-1c but kops never reported this error when cluster node was upgraded 7 days ago, and as you can see from the above image it reports the instance type c3.4xlarge 

But in reality that instance never got upgraded but was not reported 

now i have adjusted the settings to a type that is available and the cluster is back to healthy state

![new-status](https://user-images.githubusercontent.com/4328569/196340312-7e96f3bd-637f-4c48-846e-b693e6c160c9.png)

**Comment by olemarkus** [comment]
`kops get instances` reports what the AWS API reports. The condition for `detached` is that the instance exists, but is not a part of the ASG.

The detached instance lives until the rolling upgrade is completed, and only then is terminated. I.e it will continue to be detached until the replacement instance has been provisioned. In your case that probably didn't happen because the ASG could never spin up new instances.

What instance types are available in the various AZs varies. kOps does check for instance type availability when the IGs change instance types, but it can't know about this during rolling update (except indirectly due to the rolling update timing out because the replacement node never appears).
