### ISSUE TITLE
Upgrade making downgrade

### ISSUE THREAD

**Issue by gullitmiranda** [kubernetes/kops#1451]
```sh
$ kops upgrade cluster $NAME --yes
ITEM	PROPERTY		OLD	NEW
Cluster	KubernetesVersion	v1.5.1	v1.4.7
```

```sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-22T13:59:22Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

kops version=1.5.0-alpha3

**Comment by chrislovecnm** [comment]
Need more information on how you are doing this.

**Comment by vinayagg** [comment]
I am also able to reproduce this. Use following commands

kops create cluster --kubernetes-version=v1.5.1
kops upgrade cluster

**Comment by vinayagg** [comment]
I found how to upgrade. Here are my commands

---------------------------------------------------
kops edit cluster
# edit kubernetesVersion: v1.5.2
kops update cluster --yes
kops rolling-update cluster <cluster name>
--------------------------------------------------

basically, instead of upgrading cluster, update the cluster.

**Comment by chrislovecnm** [comment]
Closing
