### ISSUE TITLE
Default AWS instances for master (m3.medium) is not available in all aws regions.

### ISSUE THREAD

**Issue by idyll** [kubernetes/kops#1455]
In newer regions, for example `ca-central-1`, there are no options for m3 instances.
In fact the only medium instance that you can request is a `t2.medium`.

If `t2.medium` is acceptable it should be the default. If not I think you need to move to an `m4.large`

Or at the very least add a warning to the readme...

**Comment by justinsb** [comment]
Thanks idyll - you're right.  We already have an exception for us-east-2, but it looks like I need to apply it to ca-north-1 and eu-west-2 as well.

The default we use is c4.large, because we try to avoid the burstable instances for the master, and this is the cheapest non-burstable instance.  You can specify `--master-size` if you'd rather use the (cheaper) t2 instances.
