### ISSUE TITLE
drive synthesis of necessary ssh public/private keys from prior successful AWS login

### ISSUE THREAD

**Issue by scottstensland** [kubernetes/kops#1470]
```
kops create cluster --zones=us-east-1c mandatoryfreedom.com
I0113 19:36:46.561048   14236 create_cluster.go:331] Inferred --cloud=aws from zone "us-east-1c"

error reading SSH key file "/home/stens/.ssh/id_rsa.pub": open /home/stens/.ssh/id_rsa.pub: no such file or directory
```

I am migrating off kube-up.sh onto kops ... above I attempt to cut a fresh cluster

beautiful thing about kube-up.sh is that once a successful login to AWS has happened using

```
export      AWS_ACCESS_KEY_ID=$(cat ${AWS_ACCOUNT_CONFIGDIR}/id)
export  AWS_SECRET_ACCESS_KEY=$(cat ${AWS_ACCOUNT_CONFIGDIR}/key)

aws ecr get-login --region ${AWS_REGION} 
```

later when calling kube-up.sh it will automatically deal with creating public/private ssh keys as per

```
kube-up.sh
...
STATEMENT   sts:AssumeRole  Allow
PRINCIPAL   ec2.amazonaws.com
INSTANCEPROFILE arn:aws:iam::064066309977:instance-profile/kubernetes-minion    2016-07-06T15:46:02Z    AIPAJY6ROOGM4OX4MIBUC                               kubernetes-minion   /
ROLES   arn:aws:iam::064066309977:role/kubernetes-minion    2016-07-06T15:46:01Z    /   AROAJJSIGFI2UHIZBUL5S   kubernetes-minion
ASSUMEROLEPOLICYDOCUMENT    2012-10-17
STATEMENT   sts:AssumeRole  Allow
PRINCIPAL   ec2.amazonaws.com
Generating public/private rsa key pair.
Your identification has been saved in /home/stens/.ssh/kube_aws_rsa.
Your public key has been saved in /home/stens/.ssh/kube_aws_rsa.pub.
The key fingerprint is:
SHA256:vMrnyJe4B6Hf9p/uvqxD521pVs4cB2zYOgRPljt7M4Q stens@mail.emptyadjacentpossible.com
The key's randomart image is:
+---[RSA 2048]----+
|             .   |
|          . +    |
|           = *   |
|      ..    E *  |
|     . .S  . * . |
|    . .  .. = +.o|
|     . +.o o + Oo|
|     oooB ....* +|
|      *B..oBO=   |
+----[SHA256]-----+
Using SSH key with (AWS) fingerprint: SHA256:vMrnyJe4B6Hf9p/uvqxD521pVs4cB2zYOgRPljt7M4Q
Creating vpc.
```

NOTICE - I never had to deal with supplying my own /home/stens/.ssh/kube_aws_rsa.*

It would be very nice if as people migrate off kube-up.sh and onto kops this leveraging of a successful AWS login to dynamically spin up necessary ssh public/private keys was again the default behaviour. In the past we did not have to mention anything about ssh public/private keys when spinning up an AWS cluster using kube-up.sh

**Comment by kris-nova** [comment]
So my summary of the feature being requested (@scottstensland  correct me if I am wrong)

If a user does **not** supply the `--ssh-public-key` flag.. then (because of the **kube-up.sh** behavior) we think `kops` should generate a **new** SSH key (other than `~/.ssh/id_rsa`) 

Am I reading this correctly?

**Comment by scottstensland** [comment]
Because login to AWS was successful

```
export      AWS_ACCESS_KEY_ID=$(cat ${AWS_ACCOUNT_CONFIGDIR}/id)
export  AWS_SECRET_ACCESS_KEY=$(cat ${AWS_ACCOUNT_CONFIGDIR}/key)

aws ecr get-login --region ${AWS_REGION} 
```
I have proven I have credentials so kubernetes ( kops ) should recognize this fact and avoid demanding SSH keys ... specifically  kops should auto synthesize them if it needs them just like kube-up.sh  does when I make subsequent call to

```
kops create cluster   --cloud=aws  --zones=us-east-1c   mandatoryfreedom.com

```

**Comment by justinsb** [comment]
kube-up generates a new SSH key, but this is surprising to users, particularly as `~/.ssh/kube_aws_rsa` is not passed by default.  I think most people ended up overriding it to be `~/.ssh/id_rsa`, and that is what kops defaults to.  The issue isn't creating the key (we could easily do that), so much as it is using the right default key.

The kops philosophy therefore is:

* default to the most common key (`~/.ssh/id_rsa.pub`), which most people will have
* make it easy to change the SSH key before cluster creation (by passing the flag)
* make it easy to change the SSH key _after_ cluster creation using https://github.com/kubernetes/kops/blob/master/docs/security.md#ssh-access

I do think this is a strict improvement over kube-up, based on my experience helping users with both.  The only axis in which we are worse is that if you don't have a ~/.ssh/id_rsa we ask you to create one first (or specify the path to a key), but this is because my expectation is that most AWS users have an SSH public key and don't want us to generate another.

By way of compensation, you don't have to pass `--cloud=aws` as long as we recognize the `--zones`.  So you can just do `kops create cluster --zones us-east-1c mandatoryfreedom.com`

**Comment by chrislovecnm** [comment]
What is the status on this?
