### ISSUE TITLE
karpenter-controller CPU request is way too high and not spread across nodes

### ISSUE THREAD

**Issue by andsens** [kubernetes/kops#15046]
In the addon, karpenter-controller reserves [half a CPU](https://github.com/kubernetes/kops/blob/3bafdc414288b7525bbdf67e93d6ccfa5bde091d/upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template#L883). Looking at my own stats, it barely needs more than 2%.  

![image](https://user-images.githubusercontent.com/342823/214046958-46f958a2-e4f9-42f7-877e-f331c1a2cad4.png)

Additionally the controller deployment is using the wrong `topologySpreadConstraint` key (`webhook` instead of `controller`): https://github.com/kubernetes/kops/blob/3bafdc414288b7525bbdf67e93d6ccfa5bde091d/upup/models/cloudup/resources/addons/karpenter.sh/k8s-1.19.yaml.template#L948-L960

**Comment by andsens** [comment]
/remove-lifecycle stale

Just checked. Still a relevant in master.

**Comment by danports** [comment]
Yeah, I'd like to see an option to configure this too. We could probably add some settings to `KarpenterConfig` as is done with many of the other addons. In the meantime, I manually edited the deployment, but if/when kOps upgrades Karpenter, I'll have to reapply that hack.

**Comment by danports** [comment]
I believe #15916 addresses the CPU request aspect of this issue (at least in so far as you can easily override the default CPU request now - it doesn't change the default CPU request), but I just realized that you also pointed out an issue with the controller deployment's `topologySpreadConstraints`. I opened #15959 so that we can follow up on that problem separately.
