### ISSUE TITLE
Kubectl times out to server

### ISSUE THREAD

**Issue by Marklon** [kubernetes/kops#1526]
Hi All,

I'm receiving the below error. I've seen similar tickets  on the issues thread but none with the i/o timeout error. Any ideas around this issue? 

[kopsuser@kops-demo ~]$ kubectl get nodes
Unable to connect to the server: dial tcp IP:443: i/o timeout

kubectl version v1.5.2
kops Version 1.4.4
@kris-nova

**Comment by chrislovecnm** [comment]
What happens when you do the same command on a master?

**Comment by justinsb** [comment]
Yes, also it isn't clear if this is something that spontaneously happened, or whether this is a new cluster.  Also, is the IP `203.0.113.123` ?  

Most commonly this happens when you have not set up the NS records for your hosted zone, so if you `dig NS example.com` you will not get the NS records as listed in route53.  We definitely need better docs on this, BTW.

**Comment by Marklon** [comment]
Thanks for the feedback guys.
I realized  in my kops create cluster command I included the --admin-access=172.30.0.0/16 flag.

The solution to reaching my instance was to then add my external IP to the inbound traffic rule which then allowed me access to my  cluster. 

Moving forward if I leave that flag out I realize I can access my cluster from any IP.

**Comment by justinsb** [comment]
Glad you figured it out :+1:
