### ISSUE TITLE
Kops 1.5.0-alpha4 Is not working with --dns=private

### ISSUE THREAD

**Issue by waldman** [kubernetes/kops#1610]
Hi,

I'm trying to create a cluster that will use an Internal Hosted Zone but it's failing with the following error:
>W0124 16:33:10.711723   67910 executor.go:109] error running task "DNSZone/ops-platform" (6m40s remaining to succeed): error creating DNS HostedZone "": InvalidParameter: 1 validation error(s) found.
>- missing required field, CreateHostedZoneInput.Name.

My version: `Version 1.5.0-alpha4 (git-a60d798)`

The command that I'm trying to run is the following:
>AWS_PROFILE=[redacted>] /[redacted]/bin/kops create cluster \
>     --name=vpc-test.ops-platform \
>     --network-cidr 10.200.0.0/24  \
>     --cloud=aws \
>     --dns=private \
>     --master-size=m4.large \
>     --master-zones=us-east-1b,us-east-1c,us-east-1d \
>     --node-count=1 \
>     --node-size=c4.8xlarge \
>     --zones=us-east-1b,us-east-1c,us-east-1d \
>     --dns-zone ops-platform \
>     --state=s3://[redacted].k8s-state \
>     --yes

I tried to run the command pré-creating the zone, and also without pré-creating it.

**Comment by justinsb** [comment]
I think this is the problem:

`--dns-zone ops-platform`

`dns-zone` can either be a hosted zone ID, or a hosted zone name.  _but_ we use a heuristic to tell them apart: if it has a `.` in it we consider it a name, otherwise it's an ID.

We could improve this heuristic, except:

* you probably don't need to specify `--dns-zone` at all.  We default to the hosted zone with longest matching suffix of the cluster name.
* is ops-platform a valid (private) hostedzone?  (I did not know that!)
* if you pre-create the hosted zone ops-platform, but don't specify `--dns-zone`, I think it should work

**Comment by chrislovecnm** [comment]
Can we close?

**Comment by waldman** [comment]
Yes, we can close it.
