### ISSUE TITLE
License Scan and Findings

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kops#16366]
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/errwrap/LICENSE](http://github.com/hashicorp/errwrap/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-cleanhttp/LICENSE](http://github.com/hashicorp/go-cleanhttp/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-immutable-radix/LICENSE](http://github.com/hashicorp/go-immutable-radix/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-multierror/LICENSE](http://github.com/hashicorp/go-multierror/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-retryablehttp/LICENSE](http://github.com/hashicorp/go-retryablehttp/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-retryablehttp/client.go](http://github.com/hashicorp/go-retryablehttp/client.go)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-retryablehttp/roundtripper.go](http://github.com/hashicorp/go-retryablehttp/roundtripper.go)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/go-sockaddr/LICENSE](http://github.com/hashicorp/go-sockaddr/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/golang-lru/LICENSE](http://github.com/hashicorp/golang-lru/LICENSE)
- [x] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/hcl/LICENSE](http://github.com/hashicorp/hcl/LICENSE)
- [ ] - kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/memberlist/LICENSE](http://github.com/hashicorp/memberlist/LICENSE)

This code is under the MPL-2.0 license which is weak copyleft. Be sure that it is used only as dynamic libraries, to be safe if it's not required remove it from your repo.

Like https://github.com/kubernetes/kubernetes/blob/master/hack/unwanted-dependencies.json

**Comment by jeffcshapiro** [comment]
Per Bob Killen @mrbobbytables
All of these EXCEPT kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/memberlist/LICENSE](https://github.com/hashicorp/memberlist/LICENSE)
have been granted a license exception approval:

[cncf-exceptions-2019-11-01.spdx ](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2019-11-01.spdx)
[github.com/hashicorp/errwrap](http://github.com/hashicorp/errwrap) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2019-03-11
[github.com/hashicopr/go-cleanhttp](http://github.com/hashicopr/go-cleanhttp) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2019-03-11
[github.com/hashicopr/go-multierror](http://github.com/hashicopr/go-multierror) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2019-03-11
[github.com/hashicopr/golang-lru](http://github.com/hashicopr/golang-lru) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2019-03-11
[github.com/hashicopr/hcl](http://github.com/hashicopr/hcl) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2019-03-11

[cncf-exceptions-2021-07-19.spdx](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2021-07-19.spdx)
[github.com/hashicopr/go-retryablehttp](http://github.com/hashicopr/go-retryablehttp) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2021-07-19

[cncf-exceptions-2023-06-27.spdx](https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2023-06-27.spdx)
[github.com/hashicopr/go-sockaddr](http://github.com/hashicopr/go-sockaddr) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2023-06-27
[github.com/hashicopr/go-immutable-radix](http://github.com/hashicopr/go-immutable-radix) - PackageComment: not auto-allowlist because: Non-allowlist license(s); approved by GB exception 2023-06-27

You should request an exception for memberlist or remove the code.

**Comment by pacoxu** [comment]
- [ ] kubernetes-2024-01-03.zip/kops/vendor/[github.com/hashicorp/memberlist/LICENSE](https://github.com/hashicorp/memberlist/LICENSE)

update the todo list

**Comment by pacoxu** [comment]
This is used in
https://github.com/kubernetes/kops/blob/68c500cf83241c08e8226e7476c7448f724cfb83/protokube/pkg/gossip/memberlist/gossip.go#L27-L28
```
	cluster "github.com/jacksontj/memberlistmesh"
```

`github.com/jacksontj/memberlistmesh` used `github.com/hashicorp/memberlist`.

/cc @jacksontj @justinsb

**Comment by hakman** [comment]
@pacoxu `memberlistmesh` is an important piece of the Gossip implementation in kOps at the moment. There is a plan to remove it in a year or so, but not immediate.
How can we obtain an exception for now?

**Comment by mrbobbytables** [comment]
@hakman there is a license exception request issue template in the cncf/foundation repo: https://github.com/cncf/foundation/issues/new/choose

It'll need review from the legal committee and approval from the GB to be added as an exception.

**Comment by hakman** [comment]
Thanks @mrbobbytables & @pacoxu. I created a new request for `github.com/hashicorp/memberlist`:
https://github.com/cncf/foundation/issues/741
