### ISSUE TITLE
Improve subnet calculations to match cloud vendor limits

### ISSUE THREAD

**Issue by chrisz100** [kubernetes/kops#1640]
After using kops create cluster with an already existent VPC (CIDR: 10.0.0.0/26) kops generated a subnet size that was too small for AWS to get created - so the cluster generation failed. 

Looking into kops edit cluster it created a zone for 10.0.0.8 
Changing the netmask to 10.0.0.8/28 (to match AWS smallest network for subnet specs) made the cluster get booted up. 

We then created a second subnet 10.0.0.32/28 for databases in the free address range. 

Updating the cluster a second time results in an error, that CIDR 10.0.0.8/28 is invalid, even though kops did create 10.0.0.0/28 already and uses this to run the cluster. 

Running kops edit cluster again and changing the netmask to 10.0.0.0/28 results in a successful run with no triggered changes.

**Comment by ChrJantz** [comment]
While discussing the issue with @justinsb  we found the following: 

By kops method to slice the vpc by 8 the possibe netmask was /29 which is not in range for AWS. 
After editing this to /27 the generation worked. 

Owed the history of kops being a step forward from kube-up it was developed to skip the first slice in the VPC to not interfere with possible kube-up cluster installations and this resulted in netmask 10.0.0.8/29. 

For 10.0.0.8/27 the network is 10.0.0.0/27 which explains why aws generated the subnet on 10.0.0.0 instead of 10.0.0.8. 

For the future it might be better if kops checks the network for the first address range the cluster could work in - also taking needed nodes for the network and AWS netmask limits - into account and generate a better and more intelligent network layout.

**Comment by justinsb** [comment]
I'd like to improve the subnet calculation generally, but I think it will have to wait till 1.5.1 to do it right.

**Comment by cove** [comment]
@justinsb are you able to elaborate on the improvements you have in mind? or have a doc? I'm not quite following the difference between "big" and "little" subnets and what the intention is in the current code for example. thx!
