### ISSUE TITLE
Kops CLI Container

### ISSUE THREAD

**Issue by stealthybox** [kubernetes/kops#1687]
As an operator new to kops, I'd like to be able to install and use kops with a `docker run`.
The image should be up to date and bundle kubectl.

This is useful for:
- evaluating kops
- using kops on Windows
- using kops as a central, shared tool with a persistent volume
- using kops with secrets
- using multiple versions of kops

**Comment by chrislovecnm** [comment]
> using kops on Windows

^ that I like .. ALOT

**Comment by justinsb** [comment]
I think this would be great.

The biggest challenge that I can see will be figuring out how to get the AWS credentials into the container.

I don't think there's anything stopping us from supporting kops on Windows, directly, BTW.  There may be some filesystem separator issues but I don't think they will be widespread - most of the work happens in the VFS layer.  We mostly don't build for windows because we don't have an easy way to test it if problems arise.  But if someone runs Windows day-to-day, fixing any bugs that block it working initially and tracking down anything that comes up later would be very welcome.

**Comment by chrislovecnm** [comment]
Here are some notes:

1. `kubectl` in the container - may require a library
1. mount the users `$HOME/.kube/`
1. mount or inject aws credentials into the container

**Comment by dennis-bsi** [comment]
I searched and found where a Dockerfile for this with detailed instructions was merged months ago, https://github.com/kubernetes/kops/pull/314, but removed later on in #475.

**Comment by chrislovecnm** [comment]
@dennis-bsi hrmmm ... now where is the darn sha

**Comment by chrislovecnm** [comment]
@stealthybox you may want to look in the jenkins or test folder.  @zmerlynn how can we dig this up?

**Comment by dennis-bsi** [comment]
@chrislovecnm I pulled the files from the commit and am testing now.  It's not building correctly so I'm fixing that and might optimize it a little for a smaller image.

**Comment by zmerlynn** [comment]
Yeah, I used the docker image for a little while. It wouldn't be too hard for us to publish an image tar along with the CI builds, too. (I just don't want to do the actual push.)

**Comment by chrislovecnm** [comment]
Yah we need to automate our build

**Comment by chrislovecnm** [comment]
just merged #1727
