### ISSUE TITLE
Support MFA authentication in ~/.aws/config / credentials

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1723]
Users that use MFA in their ~/.aws config/credentials files have reported that while the AWS CLI works, kops does not.

**Comment by justinsb** [comment]
Example:

```
[profile production-kops]
source_profile = main
mfa_serial = CENSORED
role_arn = CENSORED
```

**Comment by ahawkins** [comment]
The example in https://github.com/kubernetes/kops/issues/1723#issuecomment-276388555 is mine. Let me share more information about our use case.

We have multiple aws accounts. All our engineers have IAM accounts in the `main` account (referenced with `source_profile main in the example). Each engineer has access to role in multiple other accounts. The `production-kops` profile includes the `role_arn` and associated `mfa_serial` used to provide the MFA code required for the `sts assume-role` command. tl;dr: we have `main` account, `production`, and `non-production` accounts. People switch into the account via roles and some require MFA.

I think kops is suffering from a few different issues to support our use case.

1. kops does not work on profiles directly with `mfa_serial`
2. kops does not work on profiles with `source_profile`
3. kops does not work on profiles with `role_arn`
4. (and permutations of the above)

This is probably not `kops` problem but rather a misconfiguration in the go SDK or not using a proper authentication provider chain the in SDK.

I suggest each issue be investigated separately.

Ultimately kops should support MFA authentication because cluster infra tends to be business critical. It's a great way to guard against mistakes as well.

**Comment by ahawkins** [comment]
@justinsb I think you can close this in favor of #226

**Comment by zmerlynn** [comment]
Closing and commenting on #226
