### ISSUE TITLE
1.4 image does not have ethtool?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1725]
sstarchers on slack reported that the 12-04-2016 AMI does not have ethtool.  Is there an image with 1.4 available?

**Comment by itskingori** [comment]
@justinsb I can confirm that `ami-4bb3e05c` (`k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21`) doesn't have it installed.

I've been struggling with hairpin issue for a while now and it turns out it's caused by lack of `ethtool`.. 😰. Related:

* Weave errors AWS K8s TCP socket connection issues - https://github.com/weaveworks/weave/issues/2731
* Never set hairpin mode on every interface #36990 - https://github.com/kubernetes/kubernetes/pull/36990
* Automated cherry pick of #36990  into 1.4 - https://github.com/kubernetes/kubernetes/issues/40816
* Automated cherry pick of #36990  into 1.5 - https://github.com/kubernetes/kubernetes/pull/40993

Is `apt-get install ethtool` the solution?

**Comment by itskingori** [comment]
I think this issue is superseded by https://github.com/kubernetes/kops/issues/1830 (created by you yesterday).

**Comment by chrislovecnm** [comment]
Fixed - closing
