### ISSUE TITLE
Can we preinstall / prebuild CUDA drivers?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1726]
Unclear from a licensing point of view

**Comment by brandoncole** [comment]
@aki5 is an expert in this area.  I will chime in with what I know from request of @chrislovecnm.  Basically this is mostly an AMI or Docker issue.  The trick is here is that the drivers need to match the hardware as mixing and matching isn't always a good thing to do.  If the AMI comes pre-installed with the drivers, then the Docker Containers should use those but that imposes a tool chain on the C++ code the Docker Containers use to match those drivers.  If developers want to use a version and toolchain of their choice, then the AMI should not include the GPU drivers and the Docker Container should, but then the developer is not guaranteed it will work on the hardware that is supporting it.

**Comment by diwu1989** [comment]
is it possible to just specify the nodes to use the official nvidia linux AMI?
https://aws.amazon.com/marketplace/pp/B00FYCDDTE
Would that work? since the AMI should come with the correct drivers already.

**Comment by aki5** [comment]
Jumping in a bit out of context here. No matter how you install the nvidia
drivers, you are stuck with the problem of potentially having the
driver-related shared libraries inside your docker image being out of sync
with the host side kernel module.

What I did in the past was have kubernetes copy the shared libraries from
the host into the docker when nvidia device was needed.

There is no perfect solution to this. The nvidia shared libs are an
extension of the kernel module, and so rather than risk breaking their
driver into incompatible halves, it seems mote reasonable to risk breaking
between an app and the nvidia driver (shlib+module).

Nvidia-docker might be worth looking at, on guthub....

...2 cents etc.


On Mar 21, 2017 2:26 AM, "Di Wu" <notifications@github.com> wrote:

is it possible to just specify the nodes to use the official nvidia linux
AMI?
https://aws.amazon.com/marketplace/pp/B00FYCDDTE
Would that work? since the AMI should come with the correct drivers already.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kops/issues/1726#issuecomment-288021495>,
or mute
the thread

**Comment by justinsb** [comment]
Put together a PoC of how to install the nvidia drivers using the new (proposed) hook mechanism: https://github.com/kubernetes/kops/pull/2298

To be honest I'm not entirely clear on exactly which libs are dependent on the machine and which are not.  Eliminating the libcuda download / install would be a big win IMO, because it is distributed in a massive (2GB) download.  And it _seemed_ like it was also a more liberal license.

**Comment by flx42** [comment]
I just saw this thread, I might be able to answer a few questions since I'm the maintainer of `nvidia-docker`. In nvidia-docker we find the user driver libraries, we create a volume with all these libraries and we inject this volume at runtime. But this thread is not about runtime but installation, right? It's a different discussion.

If you want a lightweight driver download:
```
http://us.download.nvidia.com/XFree86/Linux-x86_64/${VERSION}/NVIDIA-Linux-x86_64-${VERSION}.run
```
e.g.:
```
$ wget http://us.download.nvidia.com/XFree86/Linux-x86_64/375.51/NVIDIA-Linux-x86_64-375.51.run 
$ ./NVIDIA-Linux-x86_64-375.51.run --no-opengl-files
```

**Comment by flx42** [comment]
But if your host is ubuntu, I would recommend that you use the official drivers packages, we have an example [here](https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2):
```
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
sudo apt-get update && sudo apt-get install -y --no-install-recommends linux-headers-generic dkms cuda-drivers
```

**Comment by diwu1989** [comment]
@flx42 the official AMI images that kops uses seem to be debian, what would be the suggested way to install on debian? The ubuntu debs wouldn't work correctly on debian right?

**Comment by diwu1989** [comment]
I was able to use the generic linux driver install run file on debian. It worked fine and I just had to add a few lines to `rc.local` to run `nvidia-smi ...` and `nvidia-modprobe ...` initially to get all the correct devices loaded.

**Comment by flx42** [comment]
Only `nvidia-modprobe` is really needed here.

**Comment by sjezewski** [comment]
Thanks @diwu1989 !

FWIW @flx42 I tried only doing the modprobe in rc.local, but k8s still didn't recognize the GPU. However after adding those 5 lines to rc.local, it worked.

Working in this case means I see the 'Found Nvidia GPU' sys log, k8s sets the `alpha.k8s.io/nvidia-gpu:1` resource properly, and my pods get scheduled properly.

**Comment by bhack** [comment]
@flx42 Can we find any solution for the next imminent k8 1.8 release?

**Comment by bhack** [comment]
The Debian image can be builded installing [Nvidia debian packages](https://wiki.debian.org/it/NvidiaGraphicsDrivers). Is it legal to distribute this AMI?

**Comment by flx42** [comment]
@bhack sorry, I'm not a lawyer so I can't answer that.
In the future, driver installation should be solved using the new feature called [Device Plugin](https://github.com/kubernetes/community/blob/bf6057138c12a427fb0fecf71b74025f6b0bb9b6/contributors/design-proposals/device-plugin.md)

**Comment by bhack** [comment]
Just for reference https://github.com/kubernetes/kubernetes/issues/54011

**Comment by bhack** [comment]
There is some recent upstream activity in https://github.com/kubernetes/kubernetes/issues/54011.

**Comment by bhack** [comment]
The new K8 doc was merged in https://github.com/kubernetes/website/pull/6736

**Comment by bhack** [comment]
There is a new PR at https://github.com/kubernetes/kops/pull/4971

**Comment by bhack** [comment]
Do we want to close this and use https://github.com/kubernetes/kops/issues/4591?
