### ISSUE TITLE
Unit testing for rolling-update

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1761]
It would be good to have some tests :)

**Comment by andrewsykim** [comment]
Having unit/integration tests for rolling updates would help move forward with https://github.com/kubernetes/kops/pull/1774 and https://github.com/kubernetes/kops/pull/1134 with more confidence, I could work on this in my spare time. Splitting the work into separate PRs would make sense so that any changes conflicting with the currently open PRs can be done last. 

Three PRs would be:
- [ ] Add mock autoscaling client
- [ ] Add fake k8s client (I think we can import/copy from kubernetes repo)
- [ ] Add unit/integration tests (will probably conflict with the work thats already done but I think its a good tradeoff, ideally those PRs will be merged before this is started)
