### ISSUE TITLE
when kube-proxy crashes or restarts logs are overwritten

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1775]
Would be good to send logs to disk and to docker, also we cannot overwrite them.

**Comment by justinsb** [comment]
The logs should be appended to  `/var/log/kube-proxy.log` because of ` 1>>/var/log/kube-proxy.log `:

https://github.com/kubernetes/kops/blob/master/upup/models/nodeup/_kubernetes_pool/kube-proxy/files/etc/kubernetes/manifests/kube-proxy.manifest.template#L20

Can you clarify what you are asking for?

**Comment by justinsb** [comment]
In particular, is this a dup of https://github.com/kubernetes/kops/issues/1637 ?

**Comment by chrislovecnm** [comment]
closing
