### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1779]
@justinsb talked about on the open office hours that it would be good to have an automated release process.

**Comment by justinsb** [comment]
Yes, it would be great to have our releases built from CI.

@zmerlynn do you know if we tag something whether it will be built as a "named build".  I think it is fine to manually publish the release from that point, particularly if it should be an exact copy of the version built by CI.

**Comment by zmerlynn** [comment]
@justinsb: The problem is that the CI version is effectively `git-$(git describe --always)`. I can push you closer to the k8s model, if you want, which involves tagging the main branch with the alpha version at the branch point (i.e. we'd tag `v1.6.0-alpha.0` onto `master` in kops), and creates a side `release-1.5` branch with a single commit that can be tagged with `v1.5.0`. We can then remove the logic in the Makefile that's building a static version unless it's CI and drop the `git-` part.

**Comment by zmerlynn** [comment]
But at that point, the problem really is that we need a build job to pick up the `release-1.5` branch as well (which is something we do in k8s as well). The first build out of the gate for that job would be the release.

**Comment by chrislovecnm** [comment]
This may be a duplicate but not certain

/lifecycle frozen

**Comment by rifelpet** [comment]
This is a duplicate of #2955

/close
