### ISSUE TITLE
kops 1.5.0-beta2 breaks RHEL support

### ISSUE THREAD

**Issue by weaseal** [kubernetes/kops#1781]
I started a new kops cluster based on kops-1.5.0-beta2.  I use a CentOS 7 based AMI which worked well with kops-1.5.0-beta1.  Now I get this error in /var/log/cloud-init.log when my nodes start:

> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.615481    4336 executor.go:91] Tasks: 49 done / 51 total; 1 can run
> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.615519    4336 executor.go:157] Executing task "Service/docker.service": Service: docker.service
> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.615665    4336 service.go:119] querying state of service "docker.service"
> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.632558    4336 changes.go:80] Field changed "Running" actual="false" expected="true"
> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.632575    4336 changes.go:80] Field changed "Enabled" actual="false" expected="true"
> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.632622    4336 service.go:333] Restarting service "docker.service"
> Feb  3 18:30:31 ip-10-0-0-61 cloud-init[3548]: W0203 18:30:31.646856    4336 executor.go:109] error running task "Service/docker.service" (8759h52m57s remaining to succeed): error doing systemd restart docker.service: exit status 5

I found that this is caused by "docker.socket" systemd file is missing, exactly like in this issue: https://github.com/docker/docker/issues/25136

I created docker.socket file as suggested [in this comment](https://github.com/docker/docker/issues/25136#issuecomment-235670071), issued `systemctl daemon-reload` and then the cloud-init script was able to progress and succeed.

**Comment by justinsb** [comment]
I'll take a look. Which Ami are you using?

On Feb 3, 2017 6:34 PM, "weaseal" <notifications@github.com> wrote:

I started a new kops cluster based on kops-1.5.0-beta2. I use a CentOS 7
based AMI which worked well with kops-1.5.0-beta1. Now I get this error in
/var/log/cloud-init.log when my nodes start:

Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.615481 4336
executor.go:91] Tasks: 49 done / 51 total; 1 can run
Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.615519 4336
executor.go:157] Executing task "Service/docker.service": Service:
docker.service
Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.615665 4336
service.go:119] querying state of service "docker.service"
Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.632558 4336
changes.go:80] Field changed "Running" actual="false" expected="true"
Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.632575 4336
changes.go:80] Field changed "Enabled" actual="false" expected="true"
Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: I0203 18:30:31.632622 4336
service.go:333] Restarting service "docker.service"
Feb 3 18:30:31 ip-10-0-0-61 cloud-init[3548]: W0203 18:30:31.646856 4336
executor.go:109] error running task "Service/docker.service" (8759h52m57s
remaining to succeed): error doing systemd restart docker.service: exit
status 5

I found that this is caused by "docket.socket" systemd file is missing,
exactly like in this issue: docker/docker#25136
<https://github.com/docker/docker/issues/25136>

I created docker.socket file as suggested in this comment
<https://github.com/docker/docker/issues/25136#issuecomment-235670071>,
issued systemctl daemon-reload and then the cloud-init script was able to
progress and succeed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kops/issues/1781>, or mute the thread

**Comment by weaseal** [comment]
@justinsb I can't share my exact AMI with you but it's barely changed from the one provided by CentOS: "CentOS Linux 7 x86_64 HVM EBS 1602-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d7e1d2bd.3 (ami-af4333cf)" (us-west-1)

Our custom one only has a couple minor changes like separating /var/log to its own volume.

**Comment by weaseal** [comment]
@justinsb just tested reverting to 1.5.0-beta1 and it's working again
