### ISSUE TITLE
Weave issue with duplicate ip addresses

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1819]
I am filing this bug here, to let kops users know that I am working with the weave team to diagnosis this.  Just want to make this searchable in the kops issue list as well.

Here is the issue: 

https://github.com/weaveworks/weave/issues/2768

Symptom, is that the host will take a long time to route from the host network to pod network:

For instance, if you have a pod on a node call mynode, and a pod with the ip 10.0.0.4. 
```
mynode - $ traceroute 10.0.0.4 
```

This will take up to 20 seconds to route, and may cause health checks to fail.

Running:

`admin@ip-172-20-81-117:~$ ip addr show dev weave`

Will show the weave bridge

And if you get results like this:

```
admin@ip-172-20-81-117:~$ ip addr show dev weave
6: weave: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default qlen 1000
    link/ether 5a:a4:1d:20:42:c0 brd ff:ff:ff:ff:ff:ff
    inet 10.43.128.0/12 scope global weave
       valid_lft forever preferred_lft forever
    inet 10.43.128.2/12 scope global secondary weave
       valid_lft forever preferred_lft forever
    inet6 fe80::58a4:1dff:fe20:42c0/64 scope link
       valid_lft forever preferred_lft forever
```

You have issues.  We are working on a migitation plan, but intial thoughts are to roll the node.

**Comment by bboreham** [comment]
Multiple IPs on the bridge is not specifically a problem; what went wrong is that a pod had the same IP as one of the bridge IPs.  I suspect because the weave pods were all deleted and the code to recover from that has a race condition.

With a duplicate IP you get two interfaces answering arp requests, TCP conversations with three endpoints, and so on.  That gives the "20 seconds to route" symptom.

**Comment by chrislovecnm** [comment]
@bboreham thanks for the update!

**Comment by chrislovecnm** [comment]
This is fixed
