### ISSUE TITLE
Support adding etcd encrypted volumes to existing cluster

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#1845]
Our current etcd encrypted volume support is limited to initial cluster setup. However, some users may have an existing cluster that they want to encrypt etcd volumes for. We should support this use-case.

AWS does not support in-place encryption of unencrypted volumes, so it seems like we would have to do the following:

1. Take a snapshot of the unencrypted volume
2. Copy the snapshot and encrypt
3. Restore a new volume from the encrypted snapshot

We would have to asses impact on cluster availability (both for HA and non-HA setups).

**Comment by bcorijn** [comment]
/reopen
/remove-lifecycle rotten

I believe this would still be a valuable addition?

**Comment by arzavj** [comment]
@yissachar did you end up following your steps listed above? We need to do the same thing and I'm wondering whether detaching and attaching a new etcd volume is safe.

**Comment by yissachar** [comment]
@arzavj No, I never followed those steps. This was just a thought process of what would potentially be involved, so I have no idea if it is feasible or not.

**Comment by ravvereddy** [comment]
Hi All,

Any updates on this issue " encrypting etcd ebs volumes for existing kops cluster"

As encryption of etcd state store ebs volume is currently not supported for the existing cluster are there any updates for the newer version of kops K8S Cluster  v1.12.8 or v1.12.9.

Any other alternate way for encrypting the etcd state store ebs volumes for existing kops K8S Cluster while upgrading it from K8S Version 1.10.11 to 1.12.9.

Thanks

**Comment by cjbehm** [comment]
I just did this process manually in a kops 1.18.0 cluster and it is possible, but it's certainly error-prone due to the number of steps.
(Assuming an HA etcd cluster)

1. Pause ASG scaling actions for one master
2. Stop the corresponding instance
3. Use AWS Console Snapshots UI pane to create a snapshot of the volumes
     1. Select instance
     2. Don't include the root volume
     3. Select the "Copy tags" option
4. After snapshots created, terminate the stopped instance
5. Delete the volumes it was using
     1. Alternatively, change the tags so they aren't mounted by the kops master nodes. This is one more manual step to get right, but might save you headaches if you run into trouble.
6. Create volumes from your snapshots
     1. Be sure they are in the right AZ
     2. Be sure to enable Encryption
7. Manually copy the tags from the Snapshots to the new Volumes
8. Unpause the ASG scaling actions
9. Wait for the new instance to launch and become ready
10. Go to 1 until you have have updated all the volumes
11. Copy the config and cluster.spec files from the kops state store (e.g. S3)
     1. Be sure to create a backup of these files
12. Edit the etcd blocks to add `encryptedVolume: true` to each etcd instance and cluster type
13. Copy the config and cluster.spec files back to S3
14. Validate that `kops edit | update | rolling-update` all work as you'd expect.

The etcd cluster remains available, so long as no other etcd nodes are disrupted of course. You also need to complete this fairly quickly so that you are able to use kops again, without running into potential discrepancies between the actual volume states and what's in the configuration.

Most of the pain is tied to juggling the AWS tags

**Comment by djerraballi** [comment]
@cjbehm manual encryption process was successful. Thanks for posting detailed steps!
