### ISSUE TITLE
Double check NAT gateway delete code

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1846]
This was reported in slack:

```
kops delete cluster foobar --yes
inserting nat-... to be deleted
inserting nat-... to be deleted
inserting nat-... to be deleted

error from DescribeNatGateways: NatGatewayNotFound: NAT gateway nat-.... was not found
        status code: 400, request id: 6....
```

**Comment by gauravarora** [comment]
I'm stuck at this step too. I deleted the NAT gateway by mistake and now I can't delete the cluster because kops errors out. Perhaps a `--force` flag would help.

**Comment by chrislovecnm** [comment]
@gauravarora if you do an update, it should recreate the NAT gateways, then do a delete.  As always please test before running in production.  What version of kops are you using?

**Comment by lleszczu** [comment]
I just hit this issue with kops 1.7.1. I wasn't able to neither update cluster nor delete. After manual removal of entries related to nat gateway in VPCs route tables I was able to succesfully delete cluster.

**Comment by krogon-dp** [comment]
NAT Gateways are not tagged. That's why NATs are detected via existing [private route](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/natgateway.go#L125) or via [subnet](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/natgateway.go#L136).

Not sure it was historically impossible, but now it is available (checked at AWS): http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html#nat-gateway-tagging

This could solve some problems seen here.

**Comment by pulpbill** [comment]
Hi, I'm having this issue:

`W0107 14:22:17.467080    1362 executor.go:130] error running task "ElasticIP/us-east-1a.my.domain" (9m55s remaining to succeed): error finding AssociatedNatGatewayRouteTable: error listing NatGateway %!q(*string=0xc420c7f108): NatGatewayNotFound: NAT gateway nat-083300682d9a0fa74 was not found
	status code: 400, request id: 168747d0-8681-4370-b8bb-58a4568ab432
`
Kops version:
`Version 1.10.0 (git-8b52ea6d1)`

Can't delete nor update the cluster.
