### ISSUE TITLE
API on not-443, Ingress on 443 Hostport

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1847]
From Slack:

> how do i move api from port 443
...
> We have a system which can't use ELBs because they require pre-warming and our traffic is super-bursty. So I'm investigating what'd be required to have an ingress (Traefik) on port 443 and 80 without interfering with the API

**Comment by yissachar** [comment]
In a normal setup where masters are not schedulable, this shouldn't be a problem, right?

API traffic would go to 80/443 on the master, and Ingress traffic would go to 80/443 on the nodes.

**Comment by hollowimage** [comment]
but if you're exposing it over a load balancer, why take up such a common port and take over the function on the host, partially removing the option of making them schedulable at all. 

plus havint it *sit* on that port is potentially a risk as its a commonly scanned port.

**Comment by oskarpearson** [comment]
A few notes on this, since I actually raised it in Slack:

I know that we could avoid scheduling items on the masters. However this proposed change would bring things in line with the default kubernetes behaviour:

- https://kubernetes.io/docs/admin/kube-apiserver/ defaults to listening on port 6443
- https://github.com/kubernetes/kubernetes/pull/34719 relates to changing the default
- https://github.com/kubernetes-incubator/kargo/issues/820 changes this in Kargo

I'm very happy to spend time on this if someone were to give some guidance on how they'd like it done.

**Comment by chrislovecnm** [comment]
What guidance do you require?
