### ISSUE TITLE
Ensure critical networking pods don't get evicted

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/kops#1908]
We should enable the following feature for weave,canal, etc.  Currently under disk pressure networking pods can get evicted.  This feature was released in k8s 1.5.3

https://github.com/kubernetes/kubernetes/pull/41052

Additional improvements over the memory improvements in #1874

**Comment by tazjin** [comment]
We are seeing weave frequently not getting scheduled under CPU pressure. The strange thing is that the DaemonSet will not consider this an error.

Assuming a 6 node cluster, if one node does not get `weave-net` due to exhausted CPU resources, the DaemonSet will happily say `5/5 pods running`.

Our workaround so far is to set the CPU requests to `0` as the guaranteed QoS (#1894) doesn't seem to work anyways.

**Comment by tsupertramp** [comment]
This just caused a 30 minutes outage on one of our kubernetes clusters during upgrade from 1.5.4 to 1.6.0 as the basic resources on the master nodes increased. I see it the same way as tazjin. Set the cpu requests to 0 to be sure it is scheduled.

**Comment by sstarcher** [comment]
The CriticalPod annotation should resolve your issue - https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-add-on-as-critical

**Comment by chrislovecnm** [comment]
I believe we have these on the pods now. Need to double check

/assign

**Comment by bboreham** [comment]
There is a new `Priority` feature which should help with [evictions](http://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#eviction-strategy).

Currently in Alpha, and off by default.

**Comment by chrislovecnm** [comment]
/lifecycle froze

This needs to get addressed

**Comment by vainu-arto** [comment]
This also needs to be addressed in clusters that have PodPriority enabled, in which case the criticalpod annotation isn't used.

For example, the kube-proxy manifest seems to be hard-coded in nodeup and thus somewhat difficult to reliably change to contain a priority setting that prevents kube-proxy from being evicted (this problem would also be fixed by moving to running kube-proxy from a daemonset).

**Comment by sp-joseluis-ledesma** [comment]
kube-dns should also have:  “system-cluster-critical” or “system-node-critical” when podpriority is enabled
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by mars64** [comment]
/lifecycle frozen

I think this was intended earlier.

**Comment by johngmyers** [comment]
These all have critical `PodPriority` now.
/close
