### ISSUE TITLE
DNS records not updated on rolling-update

### ISSUE THREAD

**Issue by apenney** [kubernetes/kops#1921]
Hi,

I built a cluster on kops 1.5.0, and today did a rolling update while trying to fix something using 1.5.1.  It built 3 new masters but did NOT update the dns record api.internal.$cluster.  This had 3 hardcoded IPs to the old masters.

Should this be a loadbalancer rather than round-robin DNS?

**Comment by sstelfox** [comment]
I had a similar issue happen, the kops version I was using was the latest git commit as of this last Monday morning (2016/02/13). Turns out the cloud-init was broken. I found this error message in /var/log/cloud-init-output.log on the hosts:

```
Running nodeup
nodeup version 1.5.1 (git-01deca8)
flag provided but not defined: -install-systemd-unit
```

This was aborting the setup of the hosts altogether leaving them in a broken state long before they would update their DNS records. I'm not 100% positive this is the issue you experienced but I suspect it might be.

It appears someone jumped ahead a little bit by switching that flag before nodeup actually got the flag committed. I believe it was fixed with this merge: https://github.com/kubernetes/kops/commit/16197668620c15d229fdf03c79939b106418dd43

**Comment by chrislovecnm** [comment]
You may need to be using the latest built version of `nodeup`.  I am testing a rolling-update PR right now.  Will let you know.

**Comment by chrislovecnm** [comment]
I am testing cluster in private topo, but I am not running into `flag provided but not defined: -install-systemd-unit`

**Comment by sstelfox** [comment]
As I mentioned I suspect it was solved in the commit I referenced. I was just trying to add some potentially relevant context to the reporters bug.

**Comment by chrislovecnm** [comment]
Closing then - please re-open if needed
