### ISSUE TITLE
"export AWS_PROFILE" doesn't work for roles

### ISSUE THREAD

**Issue by ctolton** [kubernetes/kops#1933]
We use sub-accounts with shared roles to grant access into the sub-accounts.  We would like to be able to use these roles with kops (instead of creating special use access keys just for kops).

An example of our aws credentials file:

```
[default]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>

[subaccount1]
role_arn = arn:aws:iam::<account id>:role/<role>
source_profile = default
```

When using the AWS cli, specifying --profile lets us work on the sub-account no problem.  However, when setting "AWS_PROFILE=subaccount1" we get the following error:

> error reading state store: Unable to list AWS regions: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Are we doing something wrong?

**Comment by twelvelabs** [comment]
I see two issues:

1. You need to define your role in .aws/confit rather than credentials. See: http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

2. The golang library that kops uses will not take role config into consideration unless you set the AWS_SDK_LOAD_CONFIG env var. See: https://docs.aws.amazon.com/sdk-for-go/api/aws/session/

Note that if your role requires MFA then this will not work. I saw something in the issues today that suggested a workaround. I'll post a link if I can find it.

**Comment by twelvelabs** [comment]
Here it is: https://github.com/kubernetes/kops/pull/1888

**Comment by ctolton** [comment]
Thanks @twelvelabs, that worked perfectly.
