### ISSUE TITLE
Docker version set in config is not the one in the instances

### ISSUE THREAD

**Issue by alex88** [kubernetes/kops#1962]
I've tried to set docker version to 1.12.6 to fix issues with deadlocks on 1.12.3 using
```
  docker:
    version: 1.12.6
```
in my cluster spec, however, instances still have 1.12.3 after a forced rollout, could it be because of these lines https://github.com/kubernetes/kops/blob/master/pkg/model/components/docker.go#L49-L60 ?

**Comment by geojaz** [comment]
@alex88 That looks like it could very well be the reason. I think the reason we force the docker version is because there are certain versions that are tested and seem to work and others that don't. This has been a hot topic for folks for awhile, and I'm not sure we have a real solution yet. It seems to me that k8s is the bottleneck here. If k8s can support it, we can let kops configure it. 

Do you know if k8s supports 1.12.6 yet? If they do, we should update the code referenced below!

See: https://github.com/kubernetes/kops/issues/849#issuecomment-268149322
And: https://github.com/kubernetes/kops/commit/846b7601db65f18314472867f704bb2f4455484f

**Comment by alex88** [comment]
@geojaz you're right, seems the latest one tested is 1.12.3, at least from the only piece of info I've found https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information
Unfortunately for us the cluster is very unstable (had to terminate 2 instances in 5 days due docker being stuck) on that version so we wanted to upgrade

**Comment by geojaz** [comment]
Yeah, TBH, I really want more versions to get approved as well!

**Comment by alex88** [comment]
At least let the user decide which one to use and then their on their own since it's unsupported

**Comment by geojaz** [comment]
@justinsb ^ any reason we can't support this?

**Comment by justinsb** [comment]
It's actually here: https://github.com/kubernetes/kops/blob/master/nodeup/pkg/model/docker.go

The challenge is that we have to map each docker version (currently).  There might be a better way.

See e.g. https://github.com/kubernetes/kops/issues/1865

**Comment by alex88** [comment]
That would be a great step forward
