### ISSUE TITLE
kops create -f does not accept --yes

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1995]
`kops create -f myyaml.yaml` probably should support --yes

**Comment by kris-nova** [comment]
Right now most of our commands will run by default in **dry mode** such as

```bash
kops update cluster 
kops delete cluster
kops create cluster
```

In order to run the commands **not in dry mode** the user must append the command with `--yes` as in

```bash
kops update cluster --yes
kops delete cluster --yes
kops create cluster --yes
```

Right now `kops create` **does not** run in **dry mode** by default. So we would need to make `kops create` behave like the other commands and require a `--yes`.

An example of using `--yes` can be found [here](https://github.com/kubernetes/kops/blob/master/cmd/kops/delete_cluster.go#L68)
The `kops create` code can be found [here](https://github.com/kubernetes/kops/blob/master/cmd/kops/create.go)

**Comment by chrislovecnm** [comment]
We need to figure out how to allow a user to specify an ssh key with `kop create -f`.  What do think of another flag specify the ssh key?
