### ISSUE TITLE
The branch release currently links to ~1.4

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#2040]
It should link to a more recent release. It's confusing for users.

**Comment by justinsb** [comment]
So I think what we have now is:

- master is our dev branch, which will become 1.6
- release-1.5 is for our current 1.5 branch
- Not all PRs to master will go onto release-1.5.  I've marked some of the ones that definitely should be "cherry-pick", and will do that when we do the next 1.5 release
- release-1.4 is for our current 1.4 branch.  I can't imagine we will do another 1.4 release unless something critical comes out, because kops 1.5 works great with k8s 1.4 (and if not, I'd rather fix kops 1.5!)
- We still have the `release` branch, and I try to keep it mirroring `release-1.5` right now.  We'll see if we want to keep it.  It's not _that_ much work, but I don't know if it is useful.

**Comment by justinsb** [comment]
I put some of those notes into our release doc.  Do you want to take a look @geojaz and see if you think it fixes this issue (presuming we follow the procedure :-) )
