### ISSUE TITLE
not able to access any service from bastion(jump) server in topology private cluster

### ISSUE THREAD

**Issue by thaniyarasu** [kubernetes/kops#2057]
i did create a kubernetes cluster with 

"kops create cluster --zones us-west-1a --topology private --bastion=true --networking weave --kubernetes-version 1.5.3 --network-cidr 192.168.0.0/16 --associate-public-ip=false --dns-zone=dev.example.com dev.example.com"
i create a deployment by "kubectl run frontend --image=nginx:1.9.1 --port=80"
i create a service by "kubectl expose deploy/frontend --type=ClusterIP --port=80 --name=frontend"
i can able to "ssh admin@bastion.dev.example.com" successfully.
but when i try "curl frontend:80" from bastion server,  i got "host is not reachable" error message.
but i can able to do "kubectl port-forward frontend-container 8080:80" and can able to access frontend server in localhost:8080

how can i access "frontend" from bastion server ??
is that possible ?? because the docs says it is.

**Comment by tgrosinger** [comment]
I am interested in what I think @thaniyarasu is requesting as well. Basically, when a Kubernetes cluster is created with a bastion, it would be great to be able to forward Kubernetes services through that bastion (through ssh tunneling probably) without performing multiple hops.

Because of #1015, there is only SSH access from the bastion to the nodes in the cluster. If that were reverted it would be possible to open a tunnel through the bastion to a particular Kubernetes service.

**Comment by chrislovecnm** [comment]
It is really a security concern with bastions. You override the bastion sec group by adding an addition on to the instance group, if you like.  

Forwarding services through the bastion is an interesting use case. But our intention is that the bastion is a jump box, not a proxy.

**Comment by chrislovecnm** [comment]
Closing as this can be modified via additional sec groups. Also the bastion is not really a proxy.

Please reopen if you have other concerns
