### ISSUE TITLE
How to establish quorum again once one of the two availability zones goes down in AWS?

### ISSUE THREAD

**Issue by kustuntas** [kubernetes/kops#2064]
I have an existing kubernetes cluster on AWS in Tokyo region which has two availability zones (AWS advertised to have 3 AZs but our account has access to only two likely due to capacity issues). 

I created my cluster using Kops. It has 3 master nodes already; 2 on one AZ and 1 on the second AZ (I know this is not ideal, and 3 AZs are recommended for HA). Once the AZ with 2 master nodes go down, cluster loses quorum. How can I establish new quorum?

I thought about adding two more master nodes to the second AZ. I could not find a way to do this with Kops. I tried adding two new master instance groups. The VMs get created, but they do not join the cluster. 

Is there another way to establish new quorum? Is there a setting somewhere that I can say 1 is enough for quorum? I did not try this yet, but would deleting the two master nodes (instance groups) on the AZ that is out achieve this? I am concerned that I will not be able to add them back once the AZ comes online again.

By the way, I simulate AZ outage by suspending Launch process in the corresponding Auto Scaling groups for the masters.

**Comment by venth** [comment]
One of my collegues found article that seems to solve the issue: https://crewjam.com/etcd-aws/

Although it isn't related to kops unfortunately

**Comment by chrislovecnm** [comment]
I recommend running all of the masters in one az.  You can run into nasty issues with split brain :(  Since you have 2 and 1 you can loose the masters if you loose the AZ with two anyway.  The way to get around this is to have more than three masters or more than three etcd instances between the two AZs.    I do not think kops supports more than 3 masters, but I have not tested it.

From their docs:

> etcd is designed to be resilient to machine failures. An etcd cluster can automatically recover from any number of temporary failures (for example, machine reboots), and a cluster of N members can tolerate up to (N-1)/2 permanent failures (where a member can no longer access the cluster, due to hardware failure or disk corruption). However, in extreme circumstances, a cluster might permanently lose enough members such that quorum is irrevocably lost. For example, if a three-node cluster suffered two simultaneous and unrecoverable machine failures, it would be normally impossible for the cluster to restore quorum and continue functioning.

So running etcd in a different ec2 instance is probably the best pattern for having more than 3 instances.  The problem with that is latency and performance.  All of the kubernetes component rely on etcd, and drop in performance is a significant issue.

At this point, kops does not support offloading etcd to a separate instance, and I do not think we allow more than three masters.  My recommendation is to use a single AZ and loose your control plane.  Backup etcd :)  EBS volumes have a serious SLA.  Once the AZ come back the control plane should come back up automatically.

**Comment by chrislovecnm** [comment]
We need to document this ;)

**Comment by venth** [comment]
We think to use on premise master node as a simulation of third availability zone.
@chrislovecnm do you know how to join a manually spun up master to existing kops setup and reduce number of master per zone in Aws to 2?

**Comment by chrislovecnm** [comment]
@venth you would need to figure out if you can run nodeup and protokube on bare metal by hand.

@justinsb? Ideas?

**Comment by chrislovecnm** [comment]
Oh and not really supported ;)

**Comment by venth** [comment]
Sounds like non trivial task. What about virtual networking?
