### ISSUE TITLE
Configure instances for calico on AWS - Allow Calico to run in pure layer 3/BGP without IPIP encapsulation within a AWS VPC subnet

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#2066]
According to the Calico docs `source/dest check` should be disabled for the instances, and `ipip` disabled in the calico configuration when running on AWS:

http://docs.projectcalico.org/v2.0/usage/troubleshooting/faq#can-i-run-calico-in-a-public-cloud-environment

**Comment by ottoyiu** [comment]
The latest Calico (v2.1.0) which is still in RC as of this comment, supports routing traffic across different VPC Subnets and VPCs through IPIP, while not having to use an overlay within a VPC Subnet:

http://docs.projectcalico.org/v2.1/reference/public-cloud/aws

Config should look like this afterwards:
```
$ calicoctl apply -f - << EOF
apiVersion: v1
kind: ipPool
metadata:
  cidr: 192.168.0.0/16
spec:
  ipip:
    enabled: true
    mode: cross-subnet
```

**Comment by blakebarnett** [comment]
excellent, I'll try it out soon

**Comment by ottoyiu** [comment]
I've started working on a controller, which can be deployed on to a kops clusters to get this working.

If you are interested in following the progress:
https://github.com/ottoyiu/kubernetes-ec2-srcdst-controller

**Comment by blakebarnett** [comment]
Very cool!  I'm trying to think of scenarios where the src/dest check might get turned back on after it's turned off any can't think of any.  I was wondering why you chose to make a separate controller rather than patch protokube/nodeup/cloudup in Kops?

**Comment by ottoyiu** [comment]
Two main reasons why I thought it was a better idea to implement it as a controller:
1. It's very specific to running Calico which require src/dst check to be disabled. It doesn't seem to make sense to build it into protokube/nodeup/cloudup which ties Calico specific logic into kops and only allows users that run kops to get Calico to work in native layer3/BGP mode. I did some research, and there doesn't seem to be anything out there for Calico and Kubernetes that can disable those checks automatically. So this controller can serve any users running Kubernetes with Calico in AWS. Once I finish writing the controller, I plan to submit a PR to integrate it within kops and run the controller as a pod within the kube-system namespace if the user decides to run in cross-subnet mode instead of ipip.
2. Assuming you were to implement this srcdst disabling in nodeup which I was thinking of doing initially, modifying the srcdst check instance attribute of the EC2 instances require you to give access to `ec2:ModifyInstanceAttribute` to every single node in your Kubernetes cluster. This doesn't seem like a very good idea, unless you can only give the permission for a node to modify its own attributes (I'm not sure if that is possible). Making a controller that runs as a pod within the kube-system that is scheduled on a master node (which already has the `ec2:*` IAM policy set) prevents the need of individual nodes to have that permission.

Obviously, those are my opinions and I'm open to hearing about other possibilities (ie. the possibility of just integrating it directly into kops).

**Comment by chrislovecnm** [comment]
@blakebarnett I updated the title. @ottoyiu you able to help out with this?

**Comment by blakebarnett** [comment]
Cool, I'll try it out on our test cluster this week.

**Comment by ottoyiu** [comment]
@chrislovecnm thank you! :) much appreciated. I'll submit a PR with the changes soon. Been running with cross-subnet mode for awhile in our environments and has been working great.

@blakebarnett let me know how it goes :)

**Comment by felipejfc** [comment]
awesome, I was thinking about how to solve this and send a PR yesterday, but then I found this issue. Have you any ETA @ottoyiu? thanks

**Comment by ottoyiu** [comment]
@felipejfc I'll try to aim for end of week to get a PR up and ready. I would also like to get some unit tests going for the controller:
https://github.com/ottoyiu/kubernetes-ec2-srcdst-controller/blob/master/main.go#L64

Can anyone here point me to the right direction on best practices on how to test informers? Otherwise, I'm just going to test out the handlers?

**Comment by chrislovecnm** [comment]
@ottoyiu we have developer office hours tomorrow morning, see the readme - otherwise I need some more details.

**Comment by felipejfc** [comment]
any updates @ottoyiu ?

**Comment by ottoyiu** [comment]
@felipejfc My apologies, I have not made huge progress towards this yet since I've been busy with a move. I attended the office hours last week, and so it was nice to put faces on the username handles. I'm running into an issue with integration right now, namely with getting the AWS region name injected into the manifest templates in the addons manager.

**Comment by ottoyiu** [comment]
@felipejfc I refactored the project and added tests cases the past several days. I am now working on getting that integrated into kops as an addon. The only hurdle I'm having now is that I'm trying to passing in AWS_REGION as an env variable, but there doesn't seem to be a very straightforward into doing so... I'll hop on the slack channel and ask for assistance.

**Comment by felipejfc** [comment]
@ottoyiu do you need to pass it as an env variable? I know that there exists an API that you can ping from inside an instance to grab some information(like the region) 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

for example 

```
services/domain	
The domain for AWS resources for the region; for example, amazonaws.com for us-east-1.
```

**Comment by felipejfc** [comment]
@ottoyiu 
```
EC2_AVAIL_ZONE=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
```

is that what you need?

**Comment by ottoyiu** [comment]
@felipejfc Thanks for the idea! Earlier, I made a Docker image with an init script to set the AWS_REGION if it's not set, with the similar commands as above. It sucks that the metadata service doesn't directly expose the region, but rather requiring parsing.

After talking to @chrislovecnm, I think the best approach is to bake it in directly into the calico manifests files. I can get the region name by grabbing the prefix of the first subnet name (the AZ name). Let me know if you think that's a bad idea.

I should be done by tonight, and I'll test out those changes tomorrow. I'll update this issue ASAP!

**Comment by ottoyiu** [comment]
Here's the branch I'm working on:
https://github.com/ottoyiu/kops/tree/kops_k8s_ec2_srcdst

and the commit:
https://github.com/ottoyiu/kops/commit/dd26d6eefdc984933ee842a341f9055b949fe730

It currently functions in Kubernetes 1.5; still working on the 1.6 manifest.

**Comment by felipejfc** [comment]
Nice @ottoyiu!

I think it would also be nice to update [networking docs](https://github.com/kubernetes/kops/blob/master/docs/networking.md)

Including example on how to use calico without ipip encapsulation

**Comment by ottoyiu** [comment]
@felipejfc I made a PR, which included your suggestion of making it opt-in :)

**Comment by felipejfc** [comment]
looks awesome! thanks @ottoyiu
