### ISSUE TITLE
kops upgrade cluster referring an old dated image as NEW

### ISSUE THREAD

**Issue by thaniyarasu** [kubernetes/kops#2074]
user@ubuntu:~$ kops version
Version 1.5.2-beta.2 (git-a8c6b81)

kops upgrade says 
293135079892/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-01-31 as OLD 
kope.io/k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09   as NEW

does that mean we should avoid 293135079892/k8s-1.4-debian-jessie-amd64-hvm-ebs-2017-01-31 image ??

**Comment by justinsb** [comment]
kops is recommending that you use the 1.5 image - that is the more important difference than the date.  If you're using kubernetes 1.5, you should probably use the 1.5 image; and the 1.4 image is best for kubernetes 1.4.

(If it is recommending the 1.5 image when you're using kubernetes 1.4, please let me know the kubernetesVersion in `kops get cluster -oyaml`)

If I recall correctly, I forgot to rebuild the 1.4 image, which is why the dates are so far apart.

**Comment by dmcnaught** [comment]
I did the manual upgrade, and it doesn't look like my nodes ig was update to the 1.5 image from 1.4 - is that likely @justinsb

**Comment by thaniyarasu** [comment]
@justinsb you are correct. i used 1.5. so it was.
