### ISSUE TITLE
kops create ig with role master does not work

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#2078]
Because we are validating subnets, but cannot provide them:

```
> kops create ig master-us-east-1b --role master
Master InstanceGroup master-us-east-1b did not specify any Subnets
```

**Comment by kustuntas** [comment]
I also think that is an issue. There should be a way to specify subnets in the command line otherwise there is no use to it. 

There is a workaround though. You can create a yaml file and just execute ```kops create -f new-master.yaml```.

If you are not sure what to put in the yaml file, you can get yaml output of one of your masters as an example. ```kops get ig <master instance group name> -o yaml```
