### ISSUE TITLE
Items in S3 should use server-side encryption

### ISSUE THREAD

**Issue by eknudtson** [kubernetes/kops#212]
PKI keys (and hey, why not everything) should use SSE in S3.

**Comment by chrislovecnm** [comment]
I will one up you on that @eknudtson - we need a better aim profile on the s3 bucket.  I am thinking that we dynamically build a profile the is tied to the security groups that the servers have and a profile that is provided by the user.

@justinsb should we build the profile or use a profile that is provided?  I am thinking provided, so that multiple people can access the files.

**Comment by chrislovecnm** [comment]
cc @genehand

**Comment by chrislovecnm** [comment]
KMS has been mentioned as an option as well.  https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws follows that pattern.  Need to research if that access can be tied to a security group, or does the server and kops need the KMS arn every time.

**Comment by chrislovecnm** [comment]
Closing as this is implemented

**Comment by justinsb** [comment]
Opened #738 to track the idea of KMS encryption
