### ISSUE TITLE
kops update -f

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/kops#2148]
Following up on https://github.com/kubernetes/kops/issues/267:

It looks like we have a use case for

```bash
kops update -f
```

This would feel similar to `kops create -f` with the only difference being that it is intended to manage deltas and not create a cluster from scratch.

I think this would help users achieve the awesome goal of [fully scripted](https://github.com/kubernetes/kops/issues/1907) `kops` management, and following the `kubectl` paradigm is a shoe-in. 

Thoughts anyone?

CC @justinsb @geojaz @yissachar @chrislovecnm @k8s-mirror-aws-misc

**Comment by chrislovecnm** [comment]
How does this compare to `kops replace -f`?

**Comment by vinayagg** [comment]
I came here looking for 'update', found 'replace' instead. 
I tested replace, it works perfectly as I think it should.

The only change can be to rename 'kops replace -f' with 'kops update -f' because
- update is more intuitive
- also, I was afraid that replacing with "node" ig yaml will destroy "cluster" and master ig yaml. However, it only replaced node yaml. So it is an update.

**Comment by chrislovecnm** [comment]
I think we can just alias update to replace with cobra.

**Comment by kenden** [comment]
I seems `update` would be more logical, but according to [the documentation](https://github.com/kubernetes/kops/blob/master/docs/commands.md), update does:
'creates or updates the cloud resources to match the cluster spec.'
(It does *not* 'update a cloud specification in the registry.`)

I thought the same as @vinayagg, that replace -f would destroy my existing cluster and create a new one. But maybe the problem is simply that there is no documentation about what `replace` does exactly: 
https://github.com/kubernetes/kops/blob/master/docs/commands.md

**Comment by pjfbashton** [comment]
It would be great to be able to just have files with deltas and do `kops update -f` 
Let's say I have and additional_policies.yaml containing just changes or additions

```yaml
spec:
  additionalPolicies:
    master: |
      [
        [...]
      ]
     node: |
      [
        [...]
      ]
```
and want that merged with existing configuration.
Currently it does not seem possible as `kops replace -f ` complains about missing objects (`kind`, then `apiVersion` and so on).  Is it supposed to work and I am missing something or replace/update still requires full cluster config file ?

**Comment by geojaz** [comment]
/close 

we dunnit!
