### ISSUE TITLE
Unable to access API bearer token with `kops get secrets`

### ISSUE THREAD

**Issue by anurag** [kubernetes/kops#2234]
I created a new private cluster and attempted to access the master API bearer token using instructions here: https://github.com/kubernetes/kops/blob/master/docs/security.md#api-bearer-token

```
$ kops get secrets admin -oplaintext
Using cluster from kubectl context: <...>

secret type SSHPublicKey cannot (currently) be exported as plaintext
```

Workaround: ssh to the master and `sudo cat /srv/kubernetes/known_tokens.csv`.

Slack discussion: https://kubernetes.slack.com/archives/C3QUFP0QM/p1490821908710785

**Comment by justinsb** [comment]
The problem is that there is _also_ an SSH key with name `admin`

So this should work:

` kops get secrets --type secret admin -oplaintext`

I'll leave this open though while we figure out better behaviour here.  Should we error if there's more than one match?  Should we try to show them all?  Not sure yet...
