### ISSUE TITLE
kube-scheduler, kube-ontroller-manager, kube-proxy logs have restrictive (root) permissions

### ISSUE THREAD

**Issue by wongma7** [kubernetes/kops#2281]
We ssh in as admin but these files are only readable to root:
```
-r--------  1 root root              31705 Apr  3 22:46 kube-controller-manager.log
```
is this intentional? In particular, i'm interested in the kube-controller-manager.log having nicer permissions so that it can be copied by cluster/log-dump.sh: https://github.com/kubernetes/test-infra/issues/2397

**Comment by justinsb** [comment]
Hmm... that's tricky and a good point.  It isn't _unintentional_ - we try to lock things down as much as possible.  But it doesn't have a huge amount of value in this case, not least because we're discussing exposing them via `kubectl logs`.

I wonder if cluster/log-dump did a `sudo chmod a+r /var/log/kube-controller-manager.log` first... let me have a look at whether that would work.

**Comment by vlad-vintila-hs** [comment]
@justinsb maybe reopen? there are other use-cases beside log-dump.sh
