### ISSUE TITLE
Developer Experience Improvements

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#2307]
We need to determine how to educate developers / testers about custom nodeup / protokube / kops versions.

@justinsb uses the makefile with options

I use the hack/dev-build.sh with an alias.

The problems to fix:

1. not have users test HEAD without a custom nodeup / kops
1. simplify the process to locally build a test env
1. speed up the local build ... especially protokube
1. allow users to test custom dnscontroller containers

**Comment by anurag** [comment]
For someone who just wants to test HEAD out (or use a new feature just introduced) but isn't necessarily a contributor, it can be useful to build `kops` and `nodeup` just once and use an alias to create a cluster: 

```
export NODEUP_BUCKET="kops-nodeup"
aws s3api create-bucket --bucket ${NODEUP_BUCKET} 
cd ${GOPATH}/src/k8s.io/kops
make && make test && S3_BUCKET=s3://${NODEUP_BUCKET} make upload
```

Then you could add something like this in `.bash_aliases` and use `kops-dev` going forward.
```
KOPS_CHANNEL=$(${GOPATH}/bin/kops version | awk '{ print $2 }' |sed 's/\+/%2B/')
KOPS_BASE_URL="http://${NODEUP_BUCKET}.s3.amazonaws.com/kops/${KOPS_CHANNEL}/"

function kops-dev () {
    NODEUP_URL=${KOPS_BASE_URL}linux/amd64/nodeup KOPS_BASE_URL=${KOPS_BASE_URL} ${GOPATH}/bin/kops "$@"
}
```

**Comment by kris-nova** [comment]
This is how I usually rock https://github.com/kris-nova/kenv/blob/master/bash_profile#L33

**Comment by geojaz** [comment]
We need to turn this into docs in (maybe) `docs/development/builds.md`? But in order to have more people hacking on this stuff, it shouldn't be hidden in issues. I don't think there's a completely "correct" way, but we can start sketching some ideas about how to do this and iterate.

**Comment by geojaz** [comment]
Just noticed https://github.com/kubernetes/kops#developer-from-source and the link to [install notes](https://github.com/kubernetes/kops/blob/master/docs/install.md) - We tell folks that they may need to do custom builds for nodeup and protokube, but don't explain how!

**Comment by chrislovecnm** [comment]
We need to 

1. update CONTRIBUTING.md to point to our docs on how to build kops.  /docs/development/building.md
1. update building.md with a link to install go
1. update building.md with a note that we do not support dev on windows.  Windows devs need to use a container
1. update building.md with a list of base tools
  - make
  - bash
  - sha sum (may not need)
  - aws cli
  - docker
1. update building.md to point to bazel docs
1. update building.md on how to do a full dev build and push to s3

**Comment by geekofalltrades** [comment]
I'm posting this here because it seems appropriate.

We use a self-hosted Kops build. Occasionally we have customizations in Kops, but even when we don't, we like to host nodeup, protokube, et al in our own S3 bucket so we have better control of our supply chain.

`KOPS_BASE_URL` is a constant source of pain for us. I'm testing out upgrading our clusters from 1.14.x to 1.15.0, and I just had to discard a bunch of work because I realized that I'd forgotten to update `KOPS_BASE_URL` in the shell I was working in, and it had invisibly tainted all of the testing I was doing.

This var should be part of the cluster spec instead of an env var, so that it can't invisibly affect clusters like this. This would also protect clusters against accidental misconfigurations by operators with slightly different shells, and even against the same operator with different shells on different days.

**Comment by fred-vogt** [comment]
@geekofalltrades - Got to dog pile a bit on this one too.

The default is: "https://kubeupv2.s3.amazonaws.com/kops/<version>/":
  * https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/urls.go

The `clusterspec::assets` setting doesn't seem to support nodeup binary:
* https://kubernetes-kops.netlify.app/cluster_spec/#assets

**Comment by fred-vogt** [comment]
My notes on how to build / stage a release branch build:  
* https://github.com/cicdenv/cicdenv/wiki/KOPS-use-custom-build

Ran into something odd with the CI default short version value:
* [KOPS_BASE_URL isn't url-encoded safely when used #9452](https://github.com/kubernetes/kops/issues/9452)
