### ISSUE TITLE
Upgrading with Terraform

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kops#2390]
The upgrading docs (https://github.com/kubernetes/kops/blob/master/docs/upgrade.md) mentions that changing the Kubernetes version requires doing a rolling update with kops. I was wondering what happens if I change the K8s version, get the terraform output and do `terraform apply`. Will this do a rolling update? Any chance that I will lose state?

**Comment by chrislovecnm** [comment]
I can say that it will not do a rolling update.  I have not tested a TF created cluster doing a rolling update, but I can make an educated guess that it will work fine.  But it kinda depends, because the launchconfigurations will be updated.

I can say for certain that you have to use `kops rolling-update cluster $CLUSTER_NAME` is the only way that a cluster will be truely rolled.  Using the new feature flag `export KOPS_FEATURE_FLAGS="+DrainAndValidateRollingUpdate"` will allow for kops to drain and cardon nodes.

**Comment by olalonde** [comment]
If the ASG deletes all old instances before starting new ones, wouldn't the cluster state be lost?

**Comment by chrislovecnm** [comment]
Not sure what u mean

**Comment by olalonde** [comment]
ASG  = auto scaling group. If your cluster nodes/masters all go down before new instances are started, wouldn't you lose any state that was in etcd (e.g. all your kubernetes resources)?

**Comment by while1eq1** [comment]
@olalonde I tested this. When you do a `kops update cluster --target=terraform --out=.` then a `terraform plan` and `terraform apply`, What it will do is recreate the launch configurations and then update the ASG's to use the new launch configuration, Existing nodes will not be touched so you dont have to worry about losing your cluster. Then you will have to do the rolling update yourself by manually (or via a script) terminate each instance 1 by 1 so that the ASG will recreate them with the new launch configuration that contains the new `user_data`

**Comment by chrislovecnm** [comment]
@while1eq1 I am betting that you can do the steps that you mentioned, and then execute `kops rolling-update cluster`.  That command only loops through the nodes drains, validates and deletes the node.  The ASG then replaces the node.

**Comment by chrislovecnm** [comment]
We need to update the documentation with instructions for TF.

**Comment by olalonde** [comment]
Ok thanks, that answers my question. It would indeed be a good idea to add this info to TF doc.
