### ISSUE TITLE
kops (rolling-)update does not detect docker config change

### ISSUE THREAD

**Issue by ebbeelsborg** [kubernetes/kops#2393]
I just tried to update Docker to v. 1.12.6 on a k8s 1.5.2 cluster using kops v. 1.6.0-alpha.2. It worked (cool!), but 'kops update' and 'rolling-update' did not recognize the change and I had to --force rolling-update to make it apply the change. That's a bug, I think.

Issue [#1831](https://github.com/kubernetes/kops/issues/1831) seems related. It's more general but   also exhibits a case with the docker-key.

**REPRO SCENARIO**
I inserted the following snippet under the "spec" section of the cluster config:

    docker:
      logDriver: json-file
      version: 1.12.6

I then did:

    > kops update cluster <cluster name>
    ...
    No changes need to be applied

(NEEDUPDATE was 0 for all IGs.)

Then I did:

    > kops rolling-update cluster <cluster name>
    ...
    No rolling-update required.

Not convinced, I then did:

    > kops rolling-update cluster <cluster name> --force
    ...
    Must specify --yes to rolling-update.

(NEEDUPDATE was 0 for all IGs.)

Still not a believer, I did:

    > kops rolling-update cluster <cluster name> --force --yes
    Stopping instance
    ...
    Rolling update completed!

Then I verified that the output of "kops get cluster <cluster name> -o yaml --full" mentioned docker:

    docker:
      bridge: ""
      ipMasq: false
      ipTables: false
      logDriver: json-file
      logLevel: warn
      storage: overlay,aufs
      version: 1.12.6

I also ssh'ed to a node in that cluster and did a "sudo docker version", which concurred that 1.12.6 was indeed running.

This is as expected when one inspects the code:
[https://github.com/kubernetes/kops/blob/master/pkg/model/components/docker.go#L45](https://github.com/kubernetes/kops/blob/master/pkg/model/components/docker.go#L45)

So, I conclude that there seems to be a bug in the config change-detection mechanism.

**VERSIONS**

    > kubectl version
    Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

    > kops version
    Version 1.6.0-alpha.2 (git-d57ceda)

**Comment by chrislovecnm** [comment]
This is a bug, and we always appreciate contributions!!!

**Comment by chrislovecnm** [comment]
Is https://github.com/kubernetes/kops/issues/1831 a dup?

**Comment by ebbeelsborg** [comment]
@chrislovecnm , I think that this issue along with [#1831](https://github.com/kubernetes/kops/issues/1831), [#2231](https://github.com/kubernetes/kops/issues/2231), and [#2157](https://github.com/kubernetes/kops/issues/2157) are all symptoms of the same bug. It is not docker-specific.

To pinpoint the culprit I'd write some more tests of the change-mechanism ([changes.go](https://github.com/kubernetes/kops/blob/d3f69496e410630c219fa8ea35032e5a22eb6991/upup/pkg/fi/changes.go) and [default_methods.go](https://github.com/kubernetes/kops/blob/f146ac309cf75d2424d9b7dca2f020c5f6289d80/upup/pkg/fi/default_methods.go) e.g.).

**Comment by chrislovecnm** [comment]
#2157 I think stands out differently

Otherwise yep looks like we have some logic problems.  Workaround is to use the force ... err `--force` on rolling-update.  It is late, forgive the pun.

I agree that we have some logic issues in the update code base.  Rolling-update just checks that update has marked that nodes need to roll, drains, validates and deletes nodes. (there is a feature flag to drain and validate).  kops update does the updates ;)

**Comment by rdtr** [comment]
I tried to tackle with this issue (fix update logic) a bit, however still not clearly see the implementation.

Currently RollingUpdate [just checks whether launch configuration name is the latest one](https://github.com/kubernetes/kops/blob/ff9a13ce32107ef962c434f6b23f6796bf07e419/upup/pkg/kutil/rollingupdate_cluster.go#L287) to check if update is necessary. So anyway we need to create a new launch configuration name when update needed.

The problem is, right now only [LaunchConfiguration](https://github.com/kubernetes/kops/blob/8206b2da708cca50f6d6bc3a4b0abff4d5adc538/upup/pkg/fi/cloudup/awstasks/launchconfiguration.go#L36-L60) related changes would trigger this.

So, kops needs to compare the current cluster spec and new one (to be updated) in `apply_cluster.go`, and if a change requires a rolling-update (like this docker config) found, tells cloud tasks to create a new launch config name.

@chrislovecnm Correct me if my understanding is wrong. I'm still learning the current code base.

**Comment by chrislovecnm** [comment]
I think you are correct, but the challenge is that we are not figuring out if we have nodeup changes. Docker version is determined and installed by nodeup. We would need to run the nodeup tasks and see if there are changes.

This may be a topic you would want to discuss at our developer office hours. See our readme for the time.

**Comment by KashifSaadat** [comment]
Hi @ebbeelsborg, as mentioned in #1831 these changes are now being detected correctly and mark the nodes for a rolling update. Can we close this issue as a duplicate and resolved?

**Comment by ebbeelsborg** [comment]
@KashifSaadat Sure.

**Comment by jonathan-kosgei** [comment]
@KashifSaadat I'm trying to update the docker logging driver to use aws

```
docker:
logDriver: awslogs
logOpt:
- awslogs-region=us-west-2
- awslogs-group=k8s
```
But I get the same no rolling-update required. And running with `--force` takes down the entire cluster. The master goes down, the api elb is outofservice it stalls and doesn't work. I have to remove the above config and terminate the master to get back to where I was.

**Comment by markine** [comment]
FYI when you update the docker stanza in the cluster config, the change is saved in S3 and any new EC2 instance that comes up absorbs the new settings.

**Comment by jonathan-kosgei** [comment]
Thanks for the super fast reply @markine! I didn't know that. Thanks, let me do this again without forcing a rolling update.

**Comment by markine** [comment]
@jonathan-kosgei No problem, I've actually been avoiding 'kops rolling-update' in live clusters. I'd need to correctly set up PodDisruptionBudgets on all "customer" pods to make pod eviction safe on nodes. And I've been manually killing master nodes one at a time in clusters with 3 masters (master fault tolerance).

**Comment by jonathan-kosgei** [comment]
@markine I'm finding that the master's elb won't come up (change to InService) with my docker options set

**Comment by markine** [comment]
@jonathan-kosgei Sorry, can't help you there, I have not played with awslogs log driver.

**Comment by jonathan-kosgei** [comment]
@makine no prob thanks
