### ISSUE TITLE
Cant we use custom AWS AMI in kops

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [kubernetes/kops#2420]
Hi,
Is there a way i can use my own AMI created from CentOS 7 default AMI. I edited a IG spec and mentioned my AMI-ID. Unfortunately after a rolling-update kops didn't created the nodes using my custom AMI.

How do i achieve this using kops or is there a way to run arbitrary scripts from S3 or from local disk?

**Comment by chrislovecnm** [comment]
We need more details on the ami question -

Kops version 
Commands used
Logs from kops

Second question is that we have hooks in alpha, but the best choice is using ami

**Comment by hangtwenty** [comment]
(just linking explicitly to #245)

**Comment by chrislovecnm** [comment]
Closing, let us know if you still need help

**Comment by reachmeselva** [comment]
Hi Chrislovecnm,

I followed the steps to use custom/owned AMI from the below link and tried but due to the issues that follows, I couldn't use my owned AMI on KOPS cluster

https://github.com/kubernetes/kops/blob/master/docs/images.md

1. Owned AMI (AWS) -  Both master and worker nodes has created (see the detailed updates of both instances in AWS Console) however, there is no machine details came on the terminal while trying to validate the cluster 

2. After created KOPS cluster with default AMI, I have replaced with my owned AWS AMI( tried with image permission - both Private and Public) but it doesn't validate the cluster.

May I know, which are the steps do I need to follow other than the above mentioned link to use my owned AWS AMI on KOPS cluster.

It would be great if you could please help on this to move further
