### ISSUE TITLE
`kops addons create` fails

### ISSUE THREAD

**Issue by jmound** [kubernetes/kops#243]
In my environment, `kops addons create` fails, while `kops addons get` succeeds. It may be due to running it incorrectly, I'm not sure it's being used correctly. The reported error, `open kops-dev.REDACTED.com: no such file or directory`, appears to be due to kops not looking/finding the files in s3 even though they exist and KOPS_STATE_STORE is set. I also tried `kops addons create --state $KOPS_STATE_STORE $NAME` which failed similarly. 

```
$ kops addons get $NAME 
dns		dns
namespace.yaml	namespace.yaml

$ kops addons create $NAME -v 8
I0802 09:23:32.663510   78703 kubectl.go:54] Running command: /usr/local/bin/kubectlkubectl config view --minify --output json
I0802 09:23:32.685907   78703 addons.go:66] config = "{\n    \"kind\": \"Config\",\n    \"Version\": \"v1\",\n    \"preferences\": {},\n    \"clusters\": [\n        {\n            \"name\": \"kops-dev.REDACTED.com\",\n            \"cluster\": {\n                \"server\": \"https://.kops-dev.REDACTED.com\",\n                \"certificate-authority-data\": \"REDACTED\"\n            }\n        }\n    ],\n    \"users\": [\n        {\n            \"name\": \"kops-dev.REDACTED.com\",\n            \"user\": {\n                \"client-certificate-data\": \"REDACTED\",\n                \"client-key-data\": \"REDACTED\"\n            }\n        }\n    ],\n    \"contexts\": [\n        {\n            \"name\": \"kops-dev.REDACTED.com\",\n            \"context\": {\n                \"cluster\": \"kops-dev.REDACTED.com\",\n                \"user\": \"kops-dev.REDACTED.com\"\n            }\n        }\n    ],\n    \"current-context\": \"kops-dev.REDACTED.com\"\n}"
I0802 09:23:32.686106   78703 addons.go:79] using cluster name "kops-dev.REDACTED.com"
F0802 09:23:32.686835   78703 addons_create.go:30] error listing path kops-dev.REDACTED.com: open kops-dev.REDACTED.com: no such file or directory

$ aws s3 ls $KOPS_STATE_STORE
                           PRE kops-dev.REDACTED.com/

$ aws s3 ls $KOPS_STATE_STORE/kops-dev.REDACTED.com/
                           PRE instancegroup/
                           PRE pki/
                           PRE secrets/
2016-08-01 15:05:44       3659 cluster.spec
2016-08-01 15:05:44        577 config
```

**Comment by justinsb** [comment]
Hi @jmound thanks for reporting.  Sorry for the confusion - `kops addons` was sort of a backwater of kops, because addons in HA mode don't really work the way we've doing it in the past.  We've figured out a way forward which is to prefer kubectl, and work through the API instead.

I've put up some docs: https://github.com/kubernetes/kops/blob/master/docs/addons.md

Do you want to try them and see if they work better for you?

`kops addons` may come back in future as a wrapper around this functionality, but hopefully we can just build this into kubectl.  The intention there is that anything we build into kubectl is useful for your apps as well!

Going to close this, but do reopen (or open a new issue) if there are still issues.

**Comment by jmound** [comment]
Thanks for all the details and clearing up the confusion. I saw #253 that you removed the references to addons. Adding the dashboard as you described worked seamlessly. Any pointers for strategy to setting up ELK as it is installed by default via kube-up?
