### ISSUE TITLE
kops create is not taking values from `--config`

### ISSUE THREAD

**Issue by Tibingeo** [kubernetes/kops#2451]
@chrislovecnm 
While creating a cluster with pre defined spec `--config /path/kops.yaml`  it says `Using config file: /path/kops.yaml` but it is not taking values from the file. It takes default kops values.
kops Version 1.5

**Comment by geojaz** [comment]
@Tibingeo Have you tried using `kops create -f /path/kops.yaml` instead of `--config`?  We definitely have support for creating a cluster based on a cluster spec in 1.5, but I'm not sure what `--config` does. 

Can you look into this and please let me know if this gets you what you need. If you're good, we can close the issue. If we need something else, please let me know!

**Comment by Tibingeo** [comment]
@geojaz thanks for the command `kops create -f /path/kops.yaml`, is there a way to pass `--node-size`, `--master-size` in config file.?
Bacically I want create a cluster by specifying node-size, master-size etc. and override some values like `subnets` and loadbalancer type which kops creates with default values, 
I do it with  `kops create cluster --node-size --master-size ...`.  and then I need to edit kops config with `kops edit cluster` and update values. 
Is there any way so I can combine this 2 tasks. ?

**Comment by geojaz** [comment]
Absolutely- any values that would go into either your cluster spec or your instance group spec (nodes, masters, etc) are able to be passed in via the `-f` flag.  Take a look at this:  https://github.com/reactiveops/intro-to-kops and specifically step 2. 

I don't think this is an issue anymore so I'll close it. Please keep in touch on the k8s slack #kops if you have further questions. Thanks!

**Comment by Tibingeo** [comment]
@geojaz Thank you for the template file.
