### ISSUE TITLE
Is there a way to stop the cluster and instances within it, without terminating the instances or deleting the cluster

### ISSUE THREAD

**Issue by beanspatil** [kubernetes/kops#2498]

**Comment by olalonde** [comment]
I don't think it's possible. But it'd be an interesting feature. I wouldn't count on it though because it's probably not trivial to implement.

**Comment by beanspatil** [comment]
I think it is important feature specially as resources can cost you a lot
if not in use.

Thanks
Beena

**Comment by rdtr** [comment]
kubernetes relies upon etcd which requires at least more than half of etcd nodes are alive.
I haven't tried myself but we may let one master node stay alive in which etcd lives together and manually stop all worker nodes. (all pods other than daemon-set should become "PENDING" status)

**Comment by beanspatil** [comment]
need to check then how we can configure etcd to stop all other worker nodes and keep only the master alive. Does kops have such configurations?

**Comment by rdtr** [comment]
> Does kops have such configurations?

I think currently not, and not sure if that is a scope of kops.

For now, it looks Terraform working to support stopping instances so hopefully after that is implemented, you can use Terraform and stop worker instances on your needs.
https://github.com/hashicorp/terraform/issues/1579

**Comment by olalonde** [comment]
@beanspatil if you can keep your cluster "stateless", deleting from scratch and re-creating is equivalent to stopping/starting.

**Comment by beanspatil** [comment]
By keeping the cluster stateless you mean the database should not be a part of cluster right?

**Comment by mikesplain** [comment]
@beanspatil You can actually scale the ASG's all the way down to 0 which will terminate instances but since we store etcd state on EBS volumes it should recover when you scale back up.  I've done this a number of times with 100% success. Obviously, you should try to have backups of what's in etcd in case it can't recover but the cluster should come back up.  

If I were you, I'd give it a shot. Bring up a cluster, add some pods to it. Then scale down and back up and see if it recovers given your setup.

**Comment by ashiee** [comment]
Found some ways to do this on this blog.
https://perrohunter.com/how-to-shutdown-a-kops-kubernetes-cluster-on-aws/
