### ISSUE TITLE
Document CoreOS (and other distro image) SSH instructions

### ISSUE THREAD

**Issue by Z3r0Sum** [kubernetes/kops#2506]
As of now, the admin user is not created for CoreOS.  So when SSH'ing into members of the K8s cluster you need to use the `core` user.  I think either the documentation should be updated or the `admin` user should be created.

**Comment by geojaz** [comment]
CoreOS isn't officially supported yet, but I think we can start making the process better for folks. 

While I don't think we should create an `admin` user, we could put some information in https://github.com/kubernetes/kops/blob/master/docs/images.md#coreos for the default username. That information actually would have been helpful for me a few months ago, so I would support it. @Z3r0Sum Would you be interested in helping get this done?

**Comment by dolftax** [comment]
@geojaz @Z3r0Sum Modifying this doc works? - https://github.com/kubernetes/kops/blob/master/docs/security.md#ssh-access

**Comment by geojaz** [comment]
That's a good place to put it. I would put it in both spots

**Comment by Z3r0Sum** [comment]
@dolftax  Thanks - looks like you beat me to it.

**Comment by canadiannomad** [comment]
The placement and wording of that actually confused me.  It maked it seem like you may have to run either
`kops create secret --name <clustername> sshpublickey admin -i ~/.ssh/newkey.pub`
or
`kops create secret --name <clustername> sshpublickey core -i ~/.ssh/newkey.pub`
because it isn't clear anywhere if "admin" in that command is referring to a username or something else.
