### ISSUE TITLE
Alias `kops replace` to `kops apply` to match `kubectl`

### ISSUE THREAD

**Issue by WillemMali** [kubernetes/kops#2616]
As discussed [here](https://github.com/kubernetes/kops/issues/2603#issuecomment-302885788).

The idea is to change `kops replace` to `kops apply`, so it matches `kubectl` and its semantics (you don't replace a cluster, you apply a new desired state to it, which may or may not involve replacing parts of the cluster or the whole cluster).

Practically we'd have to copy [the command definition code for the replace command](https://github.com/kubernetes/kops/blob/master/cmd/kops/replace.go) and change `replace` to `apply`, and then perhaps add a deprecation warning to the `replace` command, AFAICT that's all there is to it.

**Comment by WillemMali** [comment]
I've implemented this suggestion in the linked PR, if anyone could comment on it that would be great.

**Comment by justinsb** [comment]
So I'm working on "kops server" mode, where we will be able to run kops as a kubernetes apiserver, and you'll be able to use `kubectl apply`.

My concern therefore is that we might be increasing the mental overhead, if `kops apply` is subtly different from `kubectl apply`.  `kubectl apply` applies immediately, which is certainly going to be one big different (and feeds into the `--yes` discussion happening on other issues).

So I agree this would be good, but I ask that we wait until we have `kubectl apply` and can compare, to make sure we aren't painting ourselves into a corner.  (And yes, I know replace already exists as well.. :-) )

**Comment by WillemMali** [comment]
If I'm getting that right, you're integrating kops into kubernetes in the
form of additional resource types (InstanceGroup, Cluster), bootstrapped by
running a master on your management machine ("kops server" mode)? Or not
quite?

**Comment by justinsb** [comment]
You're right, but let me provide a bit more of a description!

Kubernetes has api-machinery which does object versioning etc.  We've used that machinery for a long time - it is why the YAML files "look like" k8s objects.

Over the past few months the kubernetes project has refactored out the kubernetes api server logic, such that it is now practical to run an apiserver with your own API objects.  It would work with kubectl.  So we would have a kubernetes apiserver that only spoke Cluster & InstanceGroup etc.  That's what I'm calling the "kops server".

In 1.7 there should be early support for aggregating API servers, so the kops server would appear in the "main" kubernetes API.  So you would be able to edit your instancegroups from the main kubectl.

I don't see this replacing the current mode of operation (where there is no server).  If nothing else, it makes bootstrapping hard!  Also, I like the lightweight CLI / S3 mode of operation.

But for teams, it might be handy to have a standalone kops server, rather than sharing an S3 bucket.  And some people might prefer it (and we could probably create an AMI that boots up into kops server, to avoid the bootstrapping problem).

There are challenges here: the current mode of operation of k8s is quite different from kops in that when you `kubectl apply` something it happens right away, whereas with kops there is a separate "confirm" step (`kops update cluster`).  I think that confirmation step would have to go away in kops-server mode, that's going to be tricky, and that's why I'm a little wary of adding to the complexity right now.

But this is good, and I want to do it, but it's one of those where I'm like "uh oh, this could make other work much harder" so my opinion is that we should wait to see how that other work goes.  But that is predicated on _this_ PR being a "nice to have" rather than critical functionality.  (And it is nice to have, but I hope this makes sense!)
