### ISSUE TITLE
Let DNS controller manage a route53 record containing a few nodes

### ISSUE THREAD

**Issue by hubt** [kubernetes/kops#262]
I'd like to have kops manage a single DNS A record which points to a few nodes, updating the record automatically. eg. I want kubernetes.example.com to point to a DNS entry with a few ready nodes, but not all(I don't want a DNS record with 100 nodes in a large cluster). 5-10 seems like a reasonable default.

This allows me to access the cluster directly for NodePort services without using an ELB and with the simplicity of a single DNS entry, because kubernetes is providing the health checking and DNS updating.

One question would be: if you pick 5 nodes out of 100, should those 5 be consistent(causing hotspots) or randomly selected every poll interval(causing less consistent dns lookups). Most likely they should be consistent but it's something to consider.

**Comment by RXminuS** [comment]
I actually don't think this is a good idea, for two reasons. First of all because of the point you bring up...what do you do in a 100 node cluster, picking 5-10 nodes seems incredibly crude.

Second of all I feel that kops would then start interfering with the application space and I think kops should really hardcore focus on infrastructure. Kubernetes is starting to implement proper IngressControllers (expected in 1.4) which combined with something like area53 or another "register my hostPort deployments in route53"-pod would provide all the functionality you're asking for at an application level. That way devs can be in charge of which nodes to be picked and all those details.
