### ISSUE TITLE
IGs are being created with default LC and then being being updated

### ISSUE THREAD

**Issue by Gouthamve** [kubernetes/kops#2650]
Hi all, 
So I am facing a peculiar bug: I created an instance group with machineType: `c4.large`. But it turns out an LC and ASG was created with `t2.medium` and a minute later the ASG's LC was updated to be `c4.large` (confirmed from cloudtrail). This made two of the instances to be `t2.medium` and 4 of them to be `c4.large`.

I ended up with the two nodes as unresponsive as soon I depleted the CPU credit.

This is also not a one off incident and had happened twice until now. I had no mention of `t2.medium` anywhere in my manifests, so I am guessing its a bug with kops.

**Comment by robinpercy** [comment]
@Gouthamve what version of kops are you using? And mind pasting the params you're using to create the cluster?

**Comment by Gouthamve** [comment]
Hi,

➜  ~ kops version
Version 1.6.0 (git-f69a313)

**Comment by Gouthamve** [comment]
Hi sorry for the limited info before, so I was running it from https://github.com/prometheus/promebench

And looking at the Makefile now, I see that I am "editing" the IG myself after cluster creation:
```
$(KOPS_CMD) create cluster \
	--name $(CLUSTER_NAME).$(DOMAIN) \
	--cloud aws --zones $(aws_region)a --kubernetes-version 1.5.2 \
	--master-size t2.large --yes
EDITOR='./ed.sh $(build_path)/manifests/kops/regular-ig.yaml' $(KOPS_CMD) edit ig nodes
EDITOR='./ed.sh $(build_path)/manifests/kops/prometheus-ig.yaml' $(KOPS_CMD) --subnet $(aws_region)a create ig prometheus
```

I am new to kops and if its due to a default cluster being created and then updated to `c4.large` later upon the `kops edit ig nodes`, then please go ahead and close this issue. But I also think if we edit an IG, we need to replace any nodes of the old type.

Sorry for the noise and thanks for your work!

**Comment by robinpercy** [comment]
Thanks for the info @Gouthamve and no worries, some of these use cases could be documented better (and PRs are especially encouraged if you have the time 😄 ). As you say, part of the issue is that you're passing --yes to `kops create cluster`. If you omit that, you can edit the IGs, then run `kops update cluster --name $(CLUSTER_NAME).$(DOMAIN) --yes`, to apply the initial configs.

Having said that, editing IGs after the fact is supported (though with more steps than we'd like) and should output a message stating that a `kops rolling-update` is required. The overall process is described here: https://github.com/kubernetes/kops/blob/a19d2582d1503ab1e0de5138e6a6595ddde9e28a/docs/changing_configuration.md

@geojaz @chrislovecnm looks like this one can be closed.

**Comment by Gouthamve** [comment]
Thanks @robinpercy!
