### ISSUE TITLE
Master node not initialized in zone us-east-1a

### ISSUE THREAD

**Issue by dmasters19** [kubernetes/kops#2683]
Using kops v 1.6.0, creating a cluster with a master node in us-east-1a does not work.  Only worker nodes are created.

    kops create cluster useast1.dev.example.io --zones us-east-1a --master-zones us-east-1a --topology private  --networking kopeio-vxlan

Same issue was referenced in [#2384](https://github.com/kubernetes/kops/issues/2384).   The issue was closed, but there was no real resolution, user just ended up using us-east-1d as a workaround.

**Comment by chrislovecnm** [comment]
Can you set the master node type to an image type avaiable? I think we are having aws accounts that not longer have access to m3's. We default to m3's in us-east-1.

Double check the status of the asg, it will tell you why the instance did not start.

**Comment by johnwchadwick** [comment]
I have an AWS account that has access to m3 types, but sometimes they become unavailable in us-east-1a, *even though m4 is readily available*. I am guessing Amazon's capacity for m3 units is going down since it probably runs on older hardware that is being phased out.

It seems likely that moving the default to m4 would be intelligent given that the ASG may fail to actuate if an m3 shape is not available on EC2. The biggest downside is that m4s do not have a medium size, although the m4.large is cheaper and better than the m3.large at least.

**Comment by chrislovecnm** [comment]
I am wonderinf c4 or m4?

**Comment by johnwchadwick** [comment]
I actually originally went to C4 assuming it was the most logical upgrade. However, in my personal experience, C4 is a bad trade-off. It does offer more CPU muscle, but Kubernetes and running a lot of containers actually eats a lot of memory in my experience, and you easily hit the RAM ceiling. I am actually using R4 instead, but M4 seems like a reasonable trade off, and seems to have reasonably close CPU performance to C4.

**Comment by chrislovecnm** [comment]
Good points, let's look at changing to m4s.

Pretty simple code change if you are in inclined.

Chris

**Comment by chrislovecnm** [comment]
We have a PR in to detect available instance types.
