### ISSUE TITLE
Terraform bug is fixed -> Doc update

### ISSUE THREAD

**Issue by stephanlindauer** [kubernetes/kops#281]
The terraform bug, mentioned in the README.md is fixed and should probably not be mentioned in the README.md anymore but rather kops should have a dependency to terraform >= `7.0`

More info regarding the bug:
https://github.com/hashicorp/terraform/issues/2143

**Comment by justinsb** [comment]
Do you know of any way we can enforce that a terraform manifest is only for version >= X?  I worry that we have to keep advertising it because most people won't be on 0.7 for the while, and terraform fails silently for < 0.7.

I agree we can put the workaround into a child page though, but at least for now we probably have to keep the notice pretty prominent.

**Comment by justinsb** [comment]
Going to rejig the docs, and hopefully everyone will update quickly.  But AFAICT there's not version annotation in 0.7, so I can't remove it entirely:

https://github.com/hashicorp/terraform/issues/4092
https://github.com/hashicorp/terraform/issues/1400

I'm a little wary of the trick in https://github.com/hashicorp/terraform/issues/4092#issuecomment-199719193

**Comment by justinsb** [comment]
Moving further work on this (e.g. locking to a particular version) to the backlog

**Comment by chrislovecnm** [comment]
We specify version and the docs are updated
