### ISSUE TITLE
Gossip-based cluster explanation/docs?

### ISSUE THREAD

**Issue by gugahoi** [kubernetes/kops#2858]
Docs refer to a gossip mode for clusters but dont really explain what that means. Why would I use this mode? What restrictions/benefits does it provide?

**Comment by gugahoi** [comment]
@arun-gupta

**Comment by jwickens** [comment]
One of my questions is how resolve the name from my workstation. 
```
nslookup api.my-cluster-name.k8s.local
```
fails. Somehow kubectl is able to connect though.

**Comment by arun-gupta** [comment]
@justinsb would know about the name resolution

**Comment by StevenACoffman** [comment]
@arun-gupta [has an article](http://blog.arungupta.me/gossip-kubernetes-aws-kops/)

**Comment by StevenACoffman** [comment]
This ticket is a possible duplicate of #2272

**Comment by chrislovecnm** [comment]
So DNS ... one of our challenges.  Here is some background information and what I understand.

In order to do cool stuff like HA control plane (masters) and have a functional rolling update of a cluster, you need a way for Etcd and Nodes to find the stuff it needs to find.  The option that is generic i.e. works on multiple platforms, of course, is DNS.  But DNS can be a bit of a pain, and for instance, in AWS China, there is not route53 DNS.  Also what about running in GCE, when you do not want to use a public DNS domain?  As far as I know, a user cannot have a private domain hosted by GCE.  

So enter gossip.  As mentioned above gossip is a communication pattern which allows a distributed system to maintain eventual consistency.  Gossip is actually a very good pattern for eventual consistency.  Many systems like Weave and Cassandra use gossip.

Quite simply instead of using DNS, a kops clusters can perform lookups using gossip.  Here is an example.  During the creation of a kops cluster or a rolling update of a cluster, Etd nodes need to discover each other.  Instead of using Route53 for DNS, the hostnames are now updated via protokube container running gossip.

Trade offs.  At this point using gossip is new, and is not hardened by users breaking it.  So that is exactly what we need the user base to do, is use it, break it for us, so we can make kops great!  Also without DNS, you do not get stuff like a DNS name for the API endpoint.

**Comment by StevenACoffman** [comment]
From [aws docs here](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-internet-facing-load-balancers.html):

> An Internet-facing load balancer has a publicly resolvable DNS name, so it can route requests from clients over the Internet to the EC2 instances that are registered with the load balancer.

I am a bit confused how a gossip-based cluster on AWS works too. An Internet-facing ELB that fronts the API server requires DNS, I think.

**Comment by StevenACoffman** [comment]
Also, [this is where the kops gossip notes are located](https://github.com/kubernetes/kops/blob/master/docs/development/gossip.md)

**Comment by justinsb** [comment]
@StevenACoffman it _should_ be possible, but I made a mistake.  See #3053 for the fix.

**Comment by gugahoi** [comment]
@chrislovecnm  thanks for clarifying! is this anywhere in the docs?

**Comment by StevenACoffman** [comment]
For reference:
> *   Bastions always have an ELB in front of them
> *   When we're using a gossip DNS name, we use the AWS assigned ELB name (or the IP on GCE)

**Comment by StevenACoffman** [comment]
@gugahoi Some [notes are here](https://github.com/kubernetes/kops/blob/master/docs/development/gossip.md) but the information in this ticket, and the article mentioned above, are better.
