### ISSUE TITLE
kops does not work aws sts assume role 

### ISSUE THREAD

**Issue by hgallo0** [kubernetes/kops#2900]
Version 1.7.0-alpha.1 (git-e7a4222)
PRETTY_NAME="Ubuntu 16.04.2 LTS"

Sample output 
root@kops:~# env $(awsudo ${AWS_PROFILE} | grep AWS | xargs) aws ec2 describe-availability-zones --region ca-central-1
{
    "AvailabilityZones": [
        {
            "State": "available",
            "Messages": [],
            "ZoneName": "ca-central-1a",
            "RegionName": "ca-central-1"
        },
        {
            "State": "available",
            "Messages": [],
            "ZoneName": "ca-central-1b",
            "RegionName": "ca-central-1"
        }
    ]
}
root@kops:~# env $(awsudo ${AWS_PROFILE} | grep AWS | xargs) kops create cluster $NAME --zones ca-central-1a
I0711 00:00:29.084209    9843 create_cluster.go:656] Inferred --cloud=aws from zone "ca-central-1a"
I0711 00:00:29.084385    9843 create_cluster.go:842] Using SSH public key: /root/.ssh/id_rsa.pub

error populating configuration: Got an error while querying for valid regions (verify your AWS credentials?): UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 03220cb3-8292-4fe7-9b4f-dd3ddb6b5617

**Comment by StevenACoffman** [comment]
You are using `awsudo`, and I was able to successfully use kops with the similar `aws-vault` (and that also uses aws sts), but it is possible you are seeing errors due to timed out temporary credentials or other problem, like a mix of some exported environment variables and conflicting ~/.aws/credential file. I would check how long the session length is, since it can sometimes take a while to do everything.

You might also try seeing if all is right with the world with these commands:
`aws sts get-caller-identity`
`env | grep AWS`

aws-vault (if that is what you are using)

**Comment by hgallo0** [comment]
Thank you Steve, The credentials were still good. No time out there. It is
very possible that some of my environmental variables are not set up
properly.

See vars below:

root@kops:~# env  |grep -i  "kop\|aws"
AWS_SDK_LOAD_CONFIG=1
AWS_PROFILE=someprof
AWS_DEFAULT_REGION=ca-central-1
AWS_DEFAULT_PROFILE=someprof
KOPS_STATE_STORE=s3://clusters."my dns here"

Here is the output you requested, just like above. I removed the account id
and session id:
root@kops:~# aws sts get-caller-identity
{
    "UserId": "'some user id':AWS-CLI-session-'session id here",
    "Arn": "arn:aws:sts::'account number
here':assumed-role/PowerUser/AWS-CLI-session-'session id here'",
    "Account": "account number here"
}
