### ISSUE TITLE
Required a new linux image with Kernel version 4.12

### ISSUE THREAD

**Issue by ghost** [kubernetes/kops#2901]
## Issue
During the last few weeks we encountering too many OOM events, while investigating our nodes we keep see the follwing:
```KernelDeadlock - unregister_netdevice: waiting for lo to become free. Usage count = 1```

Our containers handling heavy traffic leading to numerous OOM events. 
One explanation is due to false connections termination, not releasing them gracefully.

> during container shut down. When if I inspect the container network namespace, it seems like the eth0 device has already been deleted, but only the lo device is left there. And there is another structure holding the reference for that device. - https://github.com/moby/moby/issues/5618#issuecomment-286274811

Which was resolved in the latest release: 4.12 
Following the long lasting thread: https://github.com/moby/moby/issues/5618

## Suggested Solution
Updating the kernel version to 4.12 (https://github.com/torvalds/linux/commit/d747a7a51b00984127a88113cdbbc26f91e9d815)
Currently we are using image: _image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02_ (Kernel: 4.4.65-k8s)

## Humble Request
We would like to know if the team plan to release a new Kubernetes AMI with the new kernel version?

**Comment by itskingori** [comment]
@eldar-fairfly are you sure this is the fix? See https://github.com/moby/moby/issues/5618#issuecomment-313413120.

**Comment by justincormack** [comment]
This patch is queued up for the stable releases, so should be backported fairly soon, while there may well be other issues with 4.12, and it will only have a very short support period, so you will need to keep upgrading. So if you really want this I would recommend you build your own AMI and support it yourself.

**Comment by blakebarnett** [comment]
Hitting this in our production clusters now also.

**Comment by wdauchy** [comment]
(this patch will be present in the upcoming 4.11.12 and 4.9.39 releases)

**Comment by itskingori** [comment]
I'll be everyone's guinea pig 😅. So ...

@justinsb submitted a PR to bump the kernel to 4.4.78 see https://github.com/kopeio/kubernetes-kernel/issues/8. I've been able to build my own AMI that kernel and rotated my cluster to use it.

@chrislovecnm Pinging you, just FYI. Maybe this is the cause of my issues i.e. https://github.com/kubernetes/kops/issues/2928.

@eldar-fairfly I think `kops` is hesitant to bump to 4.12 because kubernetes tests run on 4.4 (I could be wrong). Safer for the child to stay close to what the parent validates.

**Comment by chrislovecnm** [comment]
The PR was merged, really appreciate you help with the kernel! @justinsb when can we get a new ami?

**Comment by itskingori** [comment]
@chrislovecnm ah, I see. Thanks.

**Comment by itskingori** [comment]
Update: we're seeing a reduction of this in our logs since switching to a 4.4.78 kernel AMI.

**Comment by chrislovecnm** [comment]
Reduction or fix?

**Comment by justincormack** [comment]
The message is normal, it is the associated kernel panic that is a problem.

**Comment by justinsb** [comment]
Building the AMI now with 4.4.78 (thanks @itskingori ).  In 1.8 we'll continue to look at a newer kernel (let's see how the 4.4 kernel does) / debian squeeze (the logrotate fix would sure be nice) etc.

**Comment by itskingori** [comment]
> Reduction or fix?

@chrislovecnm Fix? I've not seen this error since I swapped AMI. We can give it more time. 

> The message is normal ...

@justincormack Maybe, but this was more than usual ... so much so when I would be ssh'd into the box my session gets random interruption of the error (to be clear, I'm not referring to logs) ... and then obviously they were also in the logs.

@justinsb cool! 👍

**Comment by mikelorant** [comment]
This has fixed a number of issues with our Kops 1.6.2/Kubernetes 1.6.8 cluster. I would consider this an issue that should be rolled into both the 1.7 and 1.6 branches and pushed out as a major bug fix.

**Comment by mikelorant** [comment]
This has fixed a number of issues with our Kops 1.6.2/Kubernetes 1.6.8 cluster. I would consider this an issue that should be rolled into both the 1.7 and 1.6 branches and pushed out as a major bug fix.

**Comment by chrislovecnm** [comment]
Can we close this?

**Comment by blakebarnett** [comment]
This still happens with 4.4.65, but it's far less frequent, I think we should still upgrade to whatever it's tested by test-infra ASAP.

**Comment by chrislovecnm** [comment]
@itskingori et al, if someone wants to make updates with our builder, it would help.  @justinsb mentioned that he wanted a new 1.8.0 image.

**Comment by nancykyo** [comment]
I read through the [moby/moby#5618](https://github.com/moby/moby/issues/5618). it seems have something to do with networking storage.
[moby/moby#5618 (comment)](https://github.com/moby/moby/issues/5618#issuecomment-313413120)
I'm using ceph krbd as persistent volume, if the container crash, there's a possibility that the docker daemon defunct or even turn D/Z state. Have any idea of this?

**Comment by victorgp** [comment]
Before you made changes to update to 4.12, you should be aware that the issue is not yet fixed, the fix done in that version is not actually fixing it.
It is still happening as you can see in the last comments of the issue report in moby: https://github.com/moby/moby/issues/5618

We are also hitting the issue with 4.12.
The bug was recreated in the Ubuntu issue tracking: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1711407

**Comment by nebril** [comment]
Does `block-next` label mean that kernel will be updated in next kops release?

**Comment by chrislovecnm** [comment]
We released new images with 1.8 release. Removing label but keeping open.

**Comment by chrislovecnm** [comment]
The issue is still open as this is a bug in the Linux kernel that has not been resolved yet.
