### ISSUE TITLE
feature request: user provided ca cert

### ISSUE THREAD

**Issue by mad01** [kubernetes/kops#2924]
Currently the ca cert is privately signed . In some cases you like to use a valid ca cert for the cluster. 
Suggested solution is to add the option to provide a cert at `kops create cluster` and use that ca cert

**Comment by mad01** [comment]
if i were to add support for this. Is the best way to use the `kops create cluster` or use the `kops create secret` to add a cert/private key ? 

@jjustinsb / chrislovecnm what is your thoughts on this ?

**Comment by chrislovecnm** [comment]
@mad01 `kops create secret` does make more sense to me, and we don't have to have yet another cli flag on kops cluster;(  Also many users don't use `kops create cluster`, they are using `kops create -f mycluster.yaml `.  If we have it in `kops create cluster` we would need to represent a secret in YAML, which at this point we do not do.

**Comment by mad01** [comment]
@chrislovecnm that makes since. will take a look on it

**Comment by mmacfadden** [comment]
This is especially useful in an "infrastructure as code" paradigm. We use terraform and KOPS to manage our infrastructure. When standing up environments, we need to be able to use a known root or intermediate cert so that we can use pre-generated client certs to access the environment in automated testing scenarios. Having KOPS create it's own certificate creates a minor hurdles we have to jump through.

**Comment by mad01** [comment]
closing since now merged
