### ISSUE TITLE
crossSubnet mode for calico not installing the k8s-ec2-srcdst controller

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#3019]
Kops version: 1.7.0-beta.1
Kubernetes version: 1.7.1

Setting this in the cluster spec:

```
spec:
  networking:
    calico:
      crossSubnet: true
```

And doing a rolling-update I would expect from the docs here: https://github.com/kubernetes/kops/blob/master/docs/networking.md#enable-cross-subnet-mode-in-calico-aws-only that it would bring up a `k8s-ec2-srcdst` controller but nothing seems to happen.

Installing the controller manually works fine though: https://github.com/ottoyiu/k8s-ec2-srcdst/tree/master/deploy

**Comment by ottoyiu** [comment]
This is a tricky one. Currently, the manifest to deploy k8s-ec2-srcdst is part of the Calico addon manifest. If you already upgraded your cluster to use the latest version of the Calico addon, kops doesn't see the changes within the template if "crossSubnet" is then set to true.

On top of that, a user will need to manually use calicoctl or run a Job to change an existing ipPool to be cross-subnet mode. Otherwise, even with the controller deployed - the cluster will still run in ipip mode until that migration. This was triggered by the CIDR migration script bug you reported in #3018.

I'll have to think on what is the best way to tackle this... any suggestions would be appreciated.

**Comment by blakebarnett** [comment]
Maybe when we move to the k8s backend for calico it'll be simpler and we can just update the TPR record to enable/disable settings like this.  I don't really have a suggestion for a great solution with the way it currently works. :(

**Comment by chapati23** [comment]
so _that's_ why it wasn't working, i was very confused that after forcing a rolling upgrade there was still nothing there but at least it's a known issue :)

**Comment by blakebarnett** [comment]
maybe this will be possible with the new kops api server?

**Comment by chrislovecnm** [comment]
@blakebarnett more like the addon manager maybe ??

**Comment by blakebarnett** [comment]
Yeah, I'm thinking the apiserver will have nicer ways to query for the current state of the cluster (the way kops set it up) so that we can ask it things like "Was crossSubnet enabled previously?" to make upgrade decisions like this.

**Comment by komljen** [comment]
@blakebarnett So, what is the status of this? 

I'm running kops 1.9, k8s 1.9.6 and wanted to migrate to `crossSubnet: true`, but after editing the cluster and running `kops update cluster --yes` nothing seems to happen.

Also calico-node DS is still set to always:
```
⚡  k get ds calico-node -n kube-system -o yaml | grep -A 1 "name: CALICO_IPV4POOL_IPIP"
        - name: CALICO_IPV4POOL_IPIP
          value: always
```

I could edit DS manually, but not sure if that is right thing to do?

I guess I need to run migration manually using the script from here https://github.com/kubernetes/kops/tree/master/docs/calico_cidr_migration and start `k8s-ec2-srcdst` from here https://github.com/ottoyiu/k8s-ec2-srcdst/tree/master/deploy?

**Comment by blakebarnett** [comment]
You need to deploy the controller separately.
