### ISSUE TITLE
Kops Create Master HA with 2 AZ AWS Singapore

### ISSUE THREAD

**Issue by abdidarmawan007** [kubernetes/kops#3088]
Hi all,can im set Kops create HA Master Kubernetes in singapore regions with only 2 AZ ?
Example like this
--zones=ap-southeast-1a,ap-southeast-1b --master-zones=ap-southeast-1a,ap-southeast-1b

**Comment by eedugon** [comment]
Please correct me if I'm wrong, but due to the nature of etcd clustering,
which requires a quorum of at least 51% of the nodes up, you shouldn't even
consider having 2 nodes, because if one of them goes down, the entire
"master" cluster will go down (I guess).

So, you should consider a minimum of 3 nodes in 3 AZs.

I also feel it would be nice to have some basic HA for the masters with 2
nodes (active/passive for example), so if anyone knows a better (or the
right) way to achieve this with kops let us know...

About your specific question, I believe at this moment kops doesn't allow
to create a cluster with 2 masters only, but I'm just a kops user, not a
developer.

Thanks!!

**Comment by msvbhat** [comment]
I agree with @eedugon, you shouldn't create a etcd cluster with 2 systems. It is better to have odd number of masters so that etcd cluster will have odd number of systems.

But for your case, you can specify `--master-count=3` and `--master-zones=ap-southeast-1a,ap-southeast-1b`. I haven't tested this myself, but in theory it should work. (May not be advisable too, but should work ).
