### ISSUE TITLE
cluster upgrade 'forget's custom image

### ISSUE THREAD

**Issue by dcowden** [kubernetes/kops#3160]
We use the image: field in our kops cluster to use a custom image. It works great for creating the cluster.

Unfortunately, we find that when we do do a cluster upgrade, the custom image is ignored, and it is replaced with the stock image. Here's an example:

$kops upgrade cluster
Using cluster from kubectl context: elasticsearch-1.dev.colinx.com

```
ITEM                            PROPERTY                OLD             NEW
Cluster                         KubernetesVersion       1.6.2           1.7.0
InstanceGroup/master-us-east-1c Image                   ami-8c4c69f7    kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
InstanceGroup/master-us-east-1d Image                   ami-8c4c69f7    kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
InstanceGroup/master-us-east-1e Image                   ami-8c4c69f7    kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
InstanceGroup/nodes             Image                   ami-8c4c69f7    kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
```

Note that as a part of the upgrade, the image has been replaced with the new one.

Curerntly, we work aroudn by manually re-editing the manifest to put the new image again, before we apply the changes.

**Comment by KashifSaadat** [comment]
Related code: https://github.com/kubernetes/kops/blob/master/cmd/kops/upgrade_cluster.go#L200-L221

It looks like the image change is intentional only if the Kubernetes version is changing, however https://github.com/kubernetes/kops/blob/master/cmd/kops/upgrade_cluster.go#L169 sets this to have a value regardless so the if block will always be processed? I'd expect that the image should only be set from the channel if it isn't already specified within the spec.

**Comment by chrislovecnm** [comment]
@dcowden a work around for this is to:

1. edit the k8s version
2. run update
3. run rolling update

@KashifSaadat how about if we parse for our stock image name if it is not kope.io then leave the image along?

**Comment by KashifSaadat** [comment]
@chrislovecnm yep that sounds alright, I'll raise a PR.
