### ISSUE TITLE
Find resources by tags

### ISSUE THREAD

**Issue by gambol99** [kubernetes/kops#3174]
Hi @chrislovecnm @justinsb 

Was raising as an issue first to get initial impressions ... We were looking at a way of making the cluster.spec more mobile. At the moment I CI e2e involves taking what was last deployed to prod, building a temporary cluster off the tag and then applying the changes over the build followed by numerous tests. One annoyance is the fact we have to scrap the provider id's for the subnet's and vpc from the ephemeral infra before building out kops as we manage our infra outside of kops. I was looking to streamline the build and provide a feature to find the resource by tag and if not there build it .. Technically we 'could' apply the same process to other resources ...

**Comment by gambol99** [comment]
I was thinking for the run at this, I might introduce it part of the template toolbox rather than integrating direct into the API?

**Comment by justinsb** [comment]
So my long term plan (which is not necessarily correct) was to make the network a top-level concept, and to start identifying network resources by a tag like `k8s.io/network=mynetworkid`, rather than by cluster.  So the AWS instances would probably also get a `k8s.io/network=mynetworkid` tag but that would indicate that it uses those resources.

For the short-term this would just be an easier way of doing what you describe, but once we have the AWS cloudprovider recognize this tag also it obviates the need for the shared network tags.

However, it gets tricky.  I started here but was also doing a lot of other stuff as well, though I believe this shared network object is the last thing from that integration branch (or you've already done it :-) )  The very branch is #3191, and a commit that might explain this better is https://github.com/kubernetes/kops/pull/3191/commits/2c9d2eaee59eea6f8e9709dc85407a3532b9a355

However, very open to other approaches or hearing what you think!
