### ISSUE TITLE
Re-using existing elastic IPs for NAT gateways created by kops

### ISSUE THREAD

**Issue by shaun-willows** [kubernetes/kops#3182]
We currently have a kops cluster with a private topology. If we need to re-create this cluster, the elastic IPs associated with the NAT gateways are deleted, and new EIPs are allocated when the replacement cluster is created. Is there any scope for re-using existing EIPs for NAT gateways created by kops?

We did consider creating a VPC independently and using it for our cluster, in which case we could re-use existing NAT gateways. However, this is a lot of additional overhead when we only want to re-use existing EIPs.

**Comment by BradErz** [comment]
Yea this is something we would also be interested in.

Maybe the easiest way to solve this would be to "precreate" the elastic IP's and provide their ID's to kops? Then if its an existing VPC or a new one and the ID's have been provided the NAT Gateways will use the provided ID's.

@chrislovecnm @justinsb what do you think?

**Comment by montyz** [comment]
This would be very helpful to us. We have to provide NAT IPs to our partners for whitelisting and it would be very helpful to have a known pool of Elastic IPs that would be pulled from. Perhaps tagging them would be sufficient?

**Comment by MaSattari** [comment]
We also need this feature, That would be great if we could have this.

Thank you.

**Comment by andinh-itm** [comment]
We also have whitelist at partner side, which takes a lot of effort to update. Re-use existing EIP would be very helpful.

**Comment by KIVagant** [comment]
I have the same problem. Really important feature for some cases when EIPs were whitelisted somewhere.

**Comment by esselius** [comment]
Isn't this already supported by: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#publicip ?

We're in the process of testing this feature now.

**Comment by openJT** [comment]
@esselius Be careful, I think Kops will delete the EIP if you use kops delete cluster.

Last time we tried to solve this problem, we created a second NAT with our EIP, and modified the route tables to replace it. That worked but kops delete cluster failed to work and we had to manually clean up ressources :(

Please let us know if you find a better way.

**Comment by esselius** [comment]
@openJT 
Yeah we checked running `kops delete` without the `--yes` and figured this was the case.

The non-optimal solution right now, in a worst case scenario where we'll need to recreate this cluster, keeping the same outgoing IP's, we'll run `kops cluster delete --unregister` to `Don't delete cloud resources, just unregister the cluster`, manually clean up all resources, except for the EIP's and then just pass them in through yaml-files when creating the next cluster.

`kops` has `publicIP` marked as immutable, meaning it can't be changed _after_ cluster creation.

I think that if IP whitelisting is important for b2b-reasons (like it is for us), you shouldn't let kops be the one creating the VPC at all, handle this yourself with cloudformation, separation of concerns, rather than relying on the potentially changing behaviour of a FOSS-project.

Unfortunately we're stuck the kops-created VPC etc, thank the lords that in our case, it's only a staging-cluster and not production..

**Comment by KIVagant** [comment]
@esselius just try to remove tags from an AWS resource and kops will "forget" about it.

**Comment by esselius** [comment]
@KIVagant Cool, will try this!

**Comment by thrawny** [comment]
> @esselius just try to remove tags from an AWS resource and kops will "forget" about it.

This does in fact not work. The resource still shows up in the list when running delete. Kops also warns about the resource being untagged.

`W1107 12:52:48.328400   13380 aws.go:1828] (new) cluster tag not found on elastic-ip:x.x.x.x`

And when applying the delete, the resource was deleted, so it was not just something it displayed in preview. Some other step that needs to be done in order to get kops to "forget" about something for real?

**Comment by KIVagant** [comment]
@thrawny , in my case I removed not only EIPs but also whole network part including security groups etc. And Helm has forgotten about EIPs at least when I tried "cluster delete". But no guarantee that it will work in long term.

**Comment by kivagant-ba** [comment]
To my previous comment: `sed 's/Helm/Kops/g'`

**Comment by AndresPineros** [comment]
I understand that the question is focused on NAT, but I wanted to know if there's a solution for public topologies. I need my nodes to have a static IP for the same reasons:
- whitelisting
- reaching them (we have UDP and AWS doesn't have UDP LoadBalancers, which forces us to use NodePort)

**Comment by AndresPineros** [comment]
So far, I'm at this point. I've added this to the userdata of my masters in the Kops definition:
```
INSTANCE_ID=$(wget -q -O - http://169.254.169.254/latest/meta-data/instance-id)
EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
EC2_REGION=$(echo $EC2_AVAIL_ZONE | sed 's/[a-z]$//')
EIP_ID=eipalloc-<redacted>

aws ec2 associate-address --region $EC2_REGION --allocation-id $EIP_ID --instance-id $INSTANCE_ID
```
We need masters with a specific EIP, so this is good for us.
I could do something more dynamic like having a DynamoDB to lock IP assignment and have a pool of EIPs that are assigned to nodes if they are free.

**Comment by rverma-nikiai** [comment]
Re-use existing EIP would be very helpful.

**Comment by AndresPineros** [comment]
Well, I'm not sure how pretty the script I did is, but here it is:
```
additionalUserData:
  - content: |
      #!/bin/bash
      echo "$(date) - Starting userdata" &>> /tmp/userdata.log
      wget -O /tmp/masterscript.sh <place-where-you-store-the-script...like-gist>
      chmod +x /tmp/masterscript.sh
      (sleep 60; ./tmp/masterscript.sh -l <name-of-your-LB> &>> /tmp/userdata.log) &
    name: myscript.sh
    type: text/x-shellscript
```

And the actual script:
```
# The LB_NAME that will be used
LB_NAME=""

while getopts 'l:' OPTION; do
  case "$OPTION" in
    l) LB_NAME="$OPTARG"; 
       echo "Loadbalancer name is $LB_NAME" ;;
  esac
done
shift "$(($OPTIND -1))"

#Query current instance id
INSTANCE_ID=$(wget -q -O - http://169.254.169.254/latest/meta-data/instance-id)
echo $INSTANCE_ID

#Query current instance AZ
EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
echo $EC2_AVAIL_ZONE

#Query current instance region
EC2_REGION=$(echo $EC2_AVAIL_ZONE | sed 's/[a-z]$//')
echo $EC2_REGION

#Query elastic ip with proper Name tag.
EIP_ID=$(sudo aws ec2 describe-addresses --region $EC2_REGION --query "Addresses[0].AllocationId" --filter Name=tag:Name,Values=${LB_NAME} --output text)
echo $EIP_ID

#Associate elastic ip to current instance
sudo aws ec2 associate-address --region $EC2_REGION --allocation-id $EIP_ID --instance-id $INSTANCE_ID
```
I created the elastic ip ($EIP_ID) with terraform before creating the cluster. Maybe part of this is script could be to create it if it doesn't exist, I just wanted to have more control over them.

The reason why I moved the script outside of the userdata definition is because I may want to change it without actually having to update the cluster. Basically change for it to apply the changes on the next restart. The script has getopts because it has more flags, I'm just showing the part related to the static IP.

I'm not using CoreDNS, but it was painful to make it work on the regular Kops nodes. Mainly because I never worked with userdata before and I had issues having permission to use or finding binaries like aws-cli and kubectl.

I also had to add AWS policies to the master role
```
{
          "Effect": "Allow",
          "Action": [
              "ec2:DescribeAddresses",
              "ec2:AssociateAddress"
          ],
          "Resource": "*"
        }
```
Not sure if security-wise this is a bad choice.

**Comment by grebois** [comment]
@AndresPineros thanks for sharing, I was in a rush to make it work and implemented it like this: 
https://forums.aws.amazon.com/message.jspa?messageID=515725#613460

**Comment by tomekit** [comment]
@AndresPineros Thanks. Just curious how would that work on a multi-node Kubernetes cluster?
Is it that you just elect one node to receive the IP address?

**Comment by tuapuikia** [comment]
This can be resolve if you create vpc, public and private subnet architecture and nat gateway using terraform. Then use kops to provision the cluster in precreated vpc.

All network service remain intact even you delete your k8s cluster using kops

**Comment by esselius** [comment]
> @tuapuikia This can be resolve if you create vpc, public and private subnet architecture and nat gateway using terraform. Then use kops to provision the cluster in precreated vpc.
> All network service remain intact even you delete your k8s cluster using kops

This is what we do, but with cloudformation, works pretty well

**Comment by AndresPineros** [comment]
@tomekit I was thinking about this and ot shouldn't be difficult. You just need to create an IP "pool".

You have to keep in mind that this would oly make sense if you have a static number of nodes. If you have dynamic nodes, then new nodes would have to create a new elastic ip, it is possible but I can't imagine a use-case.


The logic would be something like:

- Before creating the cluster, create all of your elastic IPs and tag them with "K8s-cluster: myClusterXYZ". We can simulate an IP pool using that tag.

- When a node is created, the userdata of the new node should:
1. Search all elastic IPs with the tag "K8s-cluster: myClusterXYZ"
2. In that set of IPs search if there is any IP that isn't attached to a node.
3. Attach that IP to the node.

If you want dynamic nodes, then just create a new IP with the tag in case you don't find free IPs with the tag.

**Comment by tomekit** [comment]
@AndresPineros 
Time to open-source this idea :)

This is what works for me.

When creating cluster run:
`kops edit ig nodes --name ${NAME}`

Add the `additionalUserData` to instance group `spec`.
```
# Script to assign elastic IPs, named: ip-kops from the unassigned pool
additionalUserData:
  - content: |
      #!/bin/bash
      apt update
      apt install -y jq awscli
      export AWS_DEFAULT_REGION=eu-west-1
      ALLOCATION_ID=`aws ec2 describe-addresses --filters="Name=tag:Name,Values=ip-kops" | jq -r '.Addresses[] | "\(.InstanceId) \(.AllocationId)"' | grep null | awk '{print $2}' | xargs shuf -n1 -e`
      INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
      if [ ! -z $ALLOCATION_ID ]; then
        aws ec2 associate-address --instance-id $INSTANCE_ID --allocation-id $ALLOCATION_ID --allow-reassociation
      fi
    name: assign-eip.sh
    type: text/x-shellscript
```
Some of the parts of this script were copied from the internet.

**Comment by alfirin** [comment]
I don't think it's fixed!

**Comment by joulaud** [comment]
/reopen

This feature is still lacking and could be of interest in several cases. I for one would have been happy to use it if it existed.
I thus allow mysel to reopen the issue.

**Comment by kkreso** [comment]
Expanding on @tomekit script - if there's only 1 EIP available in the pool it won't get associated to a new instance during rolling-update (since a previous instance is not yet terminated and holds association), so here's a initContainer version (in combo with podAffinity which is not included here):

```
      initContainers:
      - name: eip-assign
        image: atlassian/pipelines-awscli
        imagePullPolicy: "IfNotPresent"
        command:
        - "/bin/bash"
        - "-ec"
        - |
          set -o nounset
          set -o errexit
          apk -q --no-cache add curl
          echo "Starting EIP assignment"
          echo "EIPPOOL:" $EIPPOOL
          ASSOCIATED_INSTANCES=$(aws ec2 describe-addresses --filters="Name=tag:Name,Values=$EIPPOOL" | jq -r '.Addresses[] | "\(.InstanceId)"')
          INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          echo "ASSOCIATED_INSTANCES:" $ASSOCIATED_INSTANCES
          echo "INSTANCE_ID:" $INSTANCE_ID
          while ! [[ $ASSOCIATED_INSTANCES =~ (^|[[:space:]])"$INSTANCE_ID"($|[[:space:]]) ]]; do
            ALLOCATION_ID=$(aws ec2 describe-addresses --filters="Name=tag:Name,Values=$EIPPOOL" | jq -r '.Addresses[] | "\(.InstanceId) \(.AllocationId)"' | grep null | awk '{print $2}' | xargs shuf -n1 -e)
            if [ ! -z $ALLOCATION_ID ]; then
              echo "ALLOCATION_ID: " $ALLOCATION_ID
              aws ec2 associate-address --instance-id $INSTANCE_ID --allocation-id $ALLOCATION_ID --allow-reassociation
              ASSOCIATED_INSTANCES=$(aws ec2 describe-addresses --filters="Name=tag:Name,Values=$EIPPOOL" | jq -r '.Addresses[] | "\(.InstanceId)"')
            else
              echo "ALLOCATION_ID: NOT AVAILABLE"
              sleep 60
            fi
          done
          aws ec2 describe-addresses --filters="Name=tag:Name,Values=$EIPPOOL" | jq -r '.Addresses[] | "\(.InstanceId) \(.AssociationId) \(.PublicIp)"' | grep "$INSTANCE_ID"
```
In case EIP is already associated with given instance - it does nothing (except echoing InstaceId, AssociationId and PublicIP) otherwise it'll try to fetch and associate address from EIP pool every 60s.
