### ISSUE TITLE
kube-apiserver templates

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#3247]
kube-apiserver is the only non-addon where we are still using templates.  We need to move all of the templating into code.

All of this templating fun should be moved to logical code: https://github.com/kubernetes/kops/tree/master/upup/models/config/components/kube-apiserver

**Comment by georgebuckerfield** [comment]
I started some work on this here:
https://github.com/kubernetes/kops/compare/master...georgebuckerfield:refactor-apiserver-templates

Am I going in the right direction with it? Is there anything else that I should be looking at?

**Comment by chrislovecnm** [comment]
That is awesome.  @andrewsykim did you need anything specific for DO?

**Comment by andrewsykim** [comment]
yes! @georgebuckerfield for DO, the cloud provider passed into kops doesn't correlate to the cloud provider passed into kubernetes components. If the cloud provider is DO the `--cloud-provider` flags should be `--cloud-provider=external` since DO will depend on out-of-tree cloud providers. 

Example: https://github.com/kubernetes/kops/blob/master/pkg/model/components/kubecontrollermanager.go#L107-L108

**Comment by chrislovecnm** [comment]
Probably get this fix in and then do the DO change.

Please get a PR in!
