### ISSUE TITLE
Kubernetes Cluster is not working with Nat Instance, but works with NAT Gateway

### ISSUE THREAD

**Issue by ghoshaditya** [kubernetes/kops#3268]

**Comment by chrislovecnm** [comment]
@ghoshaditya at this point we only support Nat Gateways.

**Comment by chrislovecnm** [comment]
Can we close this? Phases will allow you soon to have more custom network setup.

**Comment by rajholla** [comment]
@DerekV @chrislovecnm 
Is there an option to turnoff Nat Gateways when [http_proxy](https://github.com/kubernetes/kops/blob/master/docs/http_proxy.md) is setup ?

**Comment by DerekV** [comment]
@rajholla http_proxy support is currently targeted for the situation where you are deploying to an existing VPC or network.  So for now the best approach might be to set up your VPC outside of kops and deploy into it (see the docs on existing VPC).   Since we don't create an http proxy server for you, using http_proxy more or less implies this situation anyways.

**Comment by rajholla** [comment]
Got it. @DerekV thank you again for the excellent work on http_proxy.

**Comment by chrislovecnm** [comment]
Closing this, please re-open if needed
