### ISSUE TITLE
"GC" old launch configurations

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#329]
We probably want to keep them around while instances still use them, but we should eventually remove old launch configurations as part of a rolling-upgrade

**Comment by jkinkead** [comment]
Is there a reason these should persist at all, and not simply be deleted when they're removed from the ASG?

**Comment by leoblanc** [comment]
@justinsb Hi, we hit this bug recently. Kops was unable to update the cluster configuration and we detected that the reason is that we reached 100 AWS Autoscaling Launch Configurations on our AWS account. Recently, we performed a lot of tests (and rolling-updates) on our cluster. Although we can manually delete/purge some old configurations to allocate some slots, if Kops can handle that automatically, it will be awesome. Thanks in advance!
