### ISSUE TITLE
Delete folder aws object in config store

### ISSUE THREAD

**Issue by vvbogdanov87** [kubernetes/kops#3321]
If config store contains folder object(ex. s3://my-kubestore/my.cluster.com/) delete command returns error
```error removing cluster from state store: refusing to delete: unknown file found: s3://my-kubestore/my.cluster.com/```
When you create s3 folder manually, aws creates object with "/" at the end. AWS treats all objects that have a forward slash "/" character as the last character in the key name as a folder. kops delete command doesn't handle this situation properly.

**Comment by justinsb** [comment]
Sorry for the delay on this one - we had some test problems that was stopping our test suite from working.

So the error messaging `refusing to delete: unknown file found: s3://my-kubestore/my.cluster.com/` is because we see a file that we don't recognize, and so we deliberately choose to stop deleting things.  The idea is that if you had put important things into the bucket, we don't want to accidentally delete them.

So it isn't so much that it is a folder, but rather anything we don't know to be safe.

Can you explain why you're creating the folder?  (Are you using a cool S3 FUSE system or something like that?)

We also could just mark the folder as safe, and delete it even though we don't create it, as it sounds like there will be a valid reason to keep creating the folder.

**Comment by vvbogdanov87** [comment]
I use my custom tool to create cluster specs from several templates and instance group files. After that I copy all this files to s3 folder and launch clusters using kops update. This case may be very specific. But I think that deletion of "folder" object is safe operation.
