### ISSUE TITLE
Restore a failed etcd-events cluster

### ISSUE THREAD

**Issue by doronoffir** [kubernetes/kops#3412]
Hi Guys,

We have a problem with etcd cluster that your insight would be appreciated.

The situation is:
A K8s 1.6 cluster that it etcd-events cluster became unhealthy due to misconfiguration of new members. Since the cluster is unhealthy, we can not use the member remove command.
The etcd cluster on the other hand is healthy.

We are trying to fix only the etcd-events cluster, but it does not seems like a real option :(

From the documentation it seems that the only approach is a restore from backup.
But, at the etcd ver 2 documents it states that using restore will create a new etcd cluster, and from a quick test I've tried after the etcd-events started from the backup, all events sent to it from the etcd cluster are failing with an error of a cluster id mismatch.

Does this mean that in case of a restore I will need to restore both the etcd and etcd-events cluster?

Thank you and all of the very best,

**Comment by etiennetremel** [comment]
I'm having a similar issue, any tips to restore it?

**Comment by chrislovecnm** [comment]
@robinpercy any recommendations?

/remove-lifecycle stale

**Comment by robinpercy** [comment]
@doronoffir and @etiennetremel: I suspect you've both worked through this issue already, but I'll include some suggestions for posterity, based on my past experience restoring the primary etcd cluster. This is from memory and is meant to provide guidance rather than be a comprehensive recovery procedure. It should go without saying that this shouldn't be done in production without sufficient backups/desparation ;)

It should be possible to rebuild the etcd-events cluster without touching the primary etcd cluster. At least in our case, we rebuilt the primary cluster without having to touch etcd-events.

We essentially followed the etcd2 DR instructions here: https://coreos.com/etcd/docs/2.2.5/admin_guide.html#disaster-recovery. Since etcd-events is run as static pods, their lifecycle and configuration have to be managed via the manifest files. But the overall flow is the same: 
1. Take a snapshot backup of one of the etcd-events data dirs
1. Stop all etcd-events containers
1. Delete all etcd-events data dirs (on all servers)
1. Recover the snapshot on one of the masters (using --force-new-cluster)
1. Start the other two etcd-events containers with ETCD_INITIAL_CLUSTER_STATE=existing
