### ISSUE TITLE
Feature Request: Support for using AWS Certificate Manager managed certs in the API load balancer.

### ISSUE THREAD

**Issue by hsyed** [kubernetes/kops#3464]
Picking up a CA cert file is standard practise in k8s tooling and support for picking it up from the kube config is present in most k8s api libraries. There are lots of scenarios where a k8s library cannot be used -- a tool using a well-known k8s library is misconfigured ([example](https://github.com/JetBrains/teamcity-kubernetes-plugin)), or it is just too inconvenient. 

Another key benefit would be the ability to access the dashboard securily without the kubectl proxy. 

Kops support for AWS managed certs would be a great simplification to this problem for users on AWS. 

Two levels of support:

1. Core: In this case kops is aware that a AWS cert is used for the api server and it can leave out the CA from the kube configs it generates. During cluster creation kops can try to find a suitable cert or kick off the process to generate an AWS certificate manager cert. 
2. Simple user Extension: In this case kops just configures the ELB with the user supplied cert ARN, and could be something that is done after the cluster has been created -- a bit like adding a new security group to nodes.

**Comment by mtolan** [comment]
That would mean that instead of creating a TCP Listener for port 443, forwarding to TCP 443 on the relevant instances, you'd want an ELB created with an HTTPS Listener on port 443 (which is necessary if you want to SSL terminate at the ELB, which is probably the only place an ACM certificate would be useful) forwarding to HTTPS:443 on each of the instances.

The trouble with that listener change is that ELBs notably [don't support the SPDY protocol](https://forums.aws.amazon.com/thread.jspa?threadID=90109) so this would most likely break any operations that require that (including but limited to `kubectl exec -it`)

I'm not actually certain that Amazon's ALB offering would be any better, since their SPDY support seems to end at the load balancer, and distribute HTTP/1.1 request among all the configured targets.

I'd love to see this work, but I think there are issues outside the scope of kops that will prevent it.

**Comment by mumoshu** [comment]
Hi @hsyed - I believe what I've experimented in not kops but kube-aws before would help here.

For me, it was't easier than what I had thought.

Basically, we are relying on TLS to authenticate not only servers(=apiservers may or may not behind a LB) but also clients.

ACM would help automating management of certs for authenticating servers, but it implies that we can no longer rely on TLS to be used for authenticating clients because enabling ACM means we'd terminate TLS on ELB/ALB.

The outcome would be - when you configure the TLS termination to occur on LB, either with an ELB with the HTTPS listener or an ALB, your k8s nodes, and probably admins, would end up becoming inaccessible from an apiserver. The apiserver is unable to see who the client was because TLS is already "terminated" on the LB - now it can't rely on TLS to authenticate the client.

As the problem is how to authenticate clients now - all the k8s api consumers, including k8s nodes and admins - theoretically we can utilize ACM with ELB/ALB when and only when we provide an alternative authentication strategy, other than mutual TLS authentication, to the apiserver.

So, if we'd really like to move towards that way, the question to be answered would be:

* Should we use [static tokens](https://kubernetes.io/docs/admin/authentication/#static-token-file)
* Or something like https://github.com/heptiolabs/kubernetes-aws-authenticator

in an AWS installation of the kops cluster to authenticate nodes and admins via IAM credentials?

Please see https://github.com/kubernetes-incubator/kube-aws/pull/651#issuecomment-301688304 for what I've experimented - and please correct me if anything is wrong. I'm still learning 😉
