### ISSUE TITLE
Kops doesn't add private hosted zone to newly created VPC

### ISSUE THREAD

**Issue by hubt** [kubernetes/kops#362]
I created a new cluster with Kops and terraform. It initially failed to start because etcd failed to start complaining of 

```
E0824 00:36:47.298882       6 cacher.go:220] unexpected ListAndWatch error: pkg/storage/cacher.go:163: Failed to list *api.PodTemplate: client: etcd cluster is unavailable or misconfigured
```

This was because etcd was unavailable because etcd could not look up its hostname. This was caused by using an existing private route53 hosted zone. Private hosted zones must be explicitly attached to each VPC for dns to work in them, and kops/terraform doesn't do this.

**Comment by mrichmon** [comment]
kops/direct also does not add the private Hosted Zone to the newly created k8s VPC.

**Comment by chrislovecnm** [comment]
What is the status on this issue?

**Comment by waldman** [comment]
I'm having the same issue. Is there anyone looking on it?

**Comment by chrislovecnm** [comment]
I kinda need more details. We are working on tf support and testing.

Version of kops.
Version of k8s.
Master build broken as well?

**Comment by samreaves** [comment]
I'm using the following  and had this issue.

kops 1.4.3
kubectl Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by justinsb** [comment]
This is a limitation of the current implementation.  The workaround is to manually attach the newly created VPC to your private route53 hosted zone, after kops has created it.

I will look at attaching it automatically though - it shouldn't be too hard :-)

**Comment by samreaves** [comment]
I want to reiterate that someone else in the Kubernetes Slack and I experienced this where Kops did NOT create the api or etcd private hosted zones.

**Comment by justinsb** [comment]
If you are running kops 1.5.0 beta1 or later, and you specify `--dns private` we _will_ create the dns zone (recommend specifying it using `--dns-zone`) and we will attach it to your VPC automatically.

It remains tricky to then resolve the API server endpoint from your machine (e.g. laptop), because the DNS zone is private, but my understanding is that many people are running some form of VPN to their VPC.  (Probably best to open another issue for that specific point, if you're affected, as it's tangential to this issue).

Do comment/reopen this issue if you continue to hit it with kops 1.5.0 beta1 or later (when using the `--dns private` flag)

**Comment by jurgenweber** [comment]
`kops create cluster --admin-access X.X.X.X/32 --dns private --dns-zone test.kops.aws.example.com --zones ap-southeast-2a,ap-southeast-2b,ap-southeast-2c test.kops.aws.exmaple.com
I0509 10:54:32.796872   15536 create_cluster.go:493] Inferred --cloud=aws from zone "ap-southeast-2a"
I0509 10:54:32.797241   15536 create_cluster.go:630] Using SSH public key: /Users/bob/.ssh/id_rsa.pub
I0509 10:54:34.009304   15536 subnets.go:183] Assigned CIDR 172.20.32.0/19 to subnet ap-southeast-2a
I0509 10:54:34.009346   15536 subnets.go:183] Assigned CIDR 172.20.64.0/19 to subnet ap-southeast-2b
I0509 10:54:34.009355   15536 subnets.go:183] Assigned CIDR 172.20.96.0/19 to subnet ap-southeast-2c
Previewing changes that will be made:

I0509 10:54:36.312004   15536 dns.go:90] Private DNS: skipping DNS validation

cannot find DNS Zone "test.kops.aws.example.com".  Please pre-create the zone and set up NS records so that it resolves.`

This is my first time playing with this stuff, you say here it should create it when specifying --dns private. I have done so but it is clearly looking for a hosted zone and I have the same chicken and the egg problem as first reported here (Can not create a private hosted zone without a vpc, but need kops to create teh VPC, etc).
