### ISSUE TITLE
AutoscalingLaunchConfiguration: ValidationError: The security group 'sg-*' does not exist

### ISSUE THREAD

**Issue by TrevorRobertsJr** [kubernetes/kops#3698]
Thanks for submitting an issue! 

-------------BUG REPORT --------------------
1. Fill in as much of the template below as you can. 

2. What kops version are you running? use `kops version`
1.7.1

3. What Kubernetes version are you running? use `kubectl version`
1.8.2

4. What cloud provider are you using?
AWS

5. What commands did you execute (Please provide cluster manifest `kops get --name my.example.com`, if available) and what happened after commands executed?
Attempting to specify security group names for the master and the nodes with the syntax that follows, but I am getting security group not found messages during Auto Scaling Group creation:
kops create cluster   --name cluster.k8s.local  \
--zones eu-central-1a,eu-central-1b   \
--state s3://mybucket \
--master-security-groups sg-c8a0deb5 \
--node-security-groups sg-239fe15e

**Error messages:**
W1025 07:32:14.785718    2957 executor.go:109] error running task "LaunchConfiguration/master-eu-central-1a.masters.cluster.k8s.local" (9m44s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: The security group 'sg-c8a0deb5' does not exist
	status code: 400, request id: 9ee34577-b956-11e7-b437-4780568e39ea
W1025 07:32:14.785844    2957 executor.go:109] error running task "LaunchConfiguration/nodes.cluster.k8s.local" (9m44s remaining to succeed): error creating AutoscalingLaunchConfiguration: ValidationError: The security group 'sg-239fe15e' does not exist

**Cluster Manifest:**
[ec2-user@ip-172-31-26-65 ~]$ kops get --name cluster.k8s.local
Cluster
NAME			CLOUD	ZONES
cluster.k8s.local	aws	eu-central-1a,eu-central-1b

Instance Groups
NAME			ROLE	MACHINETYPE	MIN	MAX	SUBNETS
master-eu-central-1a	Master	m3.medium	1	1	eu-central-1a
nodes			Node	t2.medium	2	2	eu-central-1a,eu-central-1b

6. What you expected to happen:
cluster creation should complete without any issues
7. How can we to reproduce it (as minimally and precisely as possible):
attempt to create a k8s cluster with security groups specified for the master and nodes
8. Anything else do we need to know:
yes, the SG's were created in advance :-)

-------------FEATURE REQUEST --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to submit an issue documentating a design supporting your feature request.

**Comment by KashifSaadat** [comment]
Hi @TrevorRobertsJr, thanks for submitting an issue.

AWS Security Groups are associated with a VPC. With the command you are running, kops will attempt to create a new VPC and network infrastructure for the Cluster to reside within. Because of this, you won't be able to use SGs that were created for another VPC. You could take one of the following options to resolve this:
- Create the Cluster (including VPC) with kops. Once the new VPC is available, create the custom Security Groups and then update the InstanceGroupSpecs with the ids: https://github.com/kubernetes/kops/blob/1.8.0-alpha.1/pkg/apis/kops/instancegroup.go#L92
- Create kops configuring it to use an existing VPC, which has your Security Groups already created: https://github.com/kubernetes/kops/blob/1.8.0-alpha.1/docs/run_in_existing_vpc.md

As a side-note, please use the kops v1.8 release (https://github.com/kubernetes/kops/releases/tag/1.8.0-alpha.1) which has additional support for Kubernetes v1.8+.

**Comment by TrevorRobertsJr** [comment]
Thank you!
