### ISSUE TITLE
Cloud-init?

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kops#380]
I read in the readme in regards to `cloud-init` generation, however, I don't see any documentation other than a few in-line code comments.

Also, cloud-init = Ubuntu's cloud-init or is this coreos config's being generated?

Someone mind directing me on how to generate these?

**Comment by chrislovecnm** [comment]
Nodeup runs a model against an image.  A shell command is executed and nodeup is run.  At this point Debian is only supported.

**Comment by cdrage** [comment]
errrr, what do you mean by nodeup? what would be the particular commands to get a cloud-init configuration output?

also, i don't think cloud-init is natively implemented in Debian yet, unlike coreos or Ubuntu. There's the package for it here: https://packages.debian.org/jessie/cloud-init but that's after you install it.

**Comment by justinsb** [comment]
The cloud-init support was experimental, and was the Debian/Ubuntu cloud-init, not the CoreOS fork.  But as I recall I was primarily doing it for GCE support, and it turns out that the official GCE images don't support it anyway (as I recall).  Also it turns out not to be nearly as good as nodeup, though my view there is biased :-)

nodeup is the "bootstrap" program that runs on the nodes: 
https://github.com/kubernetes/kops/tree/master/cmd/nodeup
https://github.com/kubernetes/kops/tree/master/upup/pkg/fi/nodeup

I believe most cloud images now run cloud-init - the AWS debian ones do.  Technically it's not a "core install" package, but it is usually installed as part of AMI creation.

**Comment by justinsb** [comment]
To be honest, it just hasn't proved very useful to use cloud-init, so I've been neglecting it.  But I'd love to hear about your use-case @cdrage  - it would be very helpful to know whether we should keep it or just dump it (as I currently suspect!)

**Comment by cdrage** [comment]
@justinsb I'd love for one day to be able to setup a k8s cluster without it having to be on AWS or GCE.

There's ansible scripts, but it's convoluted and often hard to setup :(. Hence my motivation for the cloud-init scripts to plug-in to Debian or Ubuntu-based OS'.

**Comment by justinsb** [comment]
@cdrage what is the non-AWS / non-GCE you are thinking of?  The tricky things here are etcd and DNS - we rely on movable volumes & DNS to enable a "no-ops" etcd cluster.  But we could probably do a less hands-off etcd cluster, and even use external DNS providers.  (And we're using the DNS provider infrastructure from k8s federation, so I expect that all DNS providers that you want to use will be supported eventually anyway)

**Comment by chrislovecnm** [comment]
We have examples of books that are due out in 1.6. This I think is a use case for the use of hooks

**Comment by chrislovecnm** [comment]
Closing as we have options now. Please reopen if needed

Hooks and fileassests
