### ISSUE TITLE
Don't require enableDnsHostnames on VPC

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kops#399]
Currently `enableDnsHostnames` is required on the cluster VPC. This can be problematic when using a shared VPC that doesn't have this set.

Are there any problems with making this an optional setting? I tested manually overriding `enableDnsHostnames` to be false, and didn't encounter any problems; kubectl works fine, and I can hit the master via IP.

**Comment by rochacon** [comment]
@yissachar This VPC flag is required by Kubernetes to properly discover an Kubelet node name.
I've installed an cluster (v1.3.5) in a shared VPC without this flag last week and my Kubelets wasn't working because of this missing flag. I've opened an issue related to this kubernetes/kubernetes#31329.

I don't think we can drop the requirement for this flag right now since this will break the AWS integration.

For more details on how Kubernetes integrates with AWS have a look at this [document](https://github.com/kubernetes/kubernetes/blob/v1.3.6/docs/design/aws_under_the_hood.md).

**Comment by yissachar** [comment]
@rochacon I'm not seeing that issue in my deploy. My nodes get assigned the private DNS name as their node name (e.g. `ip-172-20-160-8.ec2.internal`).

For the most part things work OK. Almost all `kubectl` work, e.g. `create`, `apply`, `get`, etc. so that I am able to deploy resources to my cluster. Pods can also talk to each other without any problems.

There are only a few things that don't work, such as `kubectl exec` or `kubectl logs`, which require master -> node communication (thanks to @justinsb for pointing this out).

**Comment by michaelajr** [comment]
We have our own Domain name (e.g., mydepartment.mycompany.com) and our DHCP options are configured to use it. We also have our own DNS servers that resolve to these names (set up via our AMI). It would be nice not to require the VPC to have DNS host names set to true. Is there any way I can work around this issue?

**Comment by justinsb** [comment]
kubectl exec and kubectl logs now will work with k8s 1.5 with kops 1.5.0 beta1 or later.

I just put a PR that makes this entirely optional as well; see the comment on the related issue:
https://github.com/kubernetes/kops/issues/786#issuecomment-275894515

**Comment by yissachar** [comment]
Fixed by #1673, thanks @justinsb!
