### ISSUE TITLE
Document TF workflow

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#4056]
High-level outline of documenting how to use manifests, templating, etc

/area documentation

1. generate a cluster manifest with --dry-run -`kops create cluster --zones us-west-2b -oyaml --dry-run --name $NAME --networking weave --authorization RBAC > $NAME.yaml`
1. edit the manifest to add anything you need such as audit logs for the API server.
1. figure out what if anything needs to be templated with go
1. create a values file for the template
1. check that base template/manifest into source control 
1. use the toolbox component in kops to generate values and template on the fly - `kops toolbox template --values values-cluster.yaml --template template-cluster.yaml > $NAME.yaml`
1. `kops create -f $NAME.yaml`
1. `kops create secret --name $NAME sshpublickey admin -i ~/.ssh/id_rsa.pub`
1. `kops update cluster --name $NAME -o $NAME-kops-tf --target terraform`
1. run your TF

To update a cluster

1. Update the templates in source control, and check them in
1. Generate the new cluster manifest with toolbox
1. `kops replace -f $NAME.yaml`
1. `kops update cluster --name $NAME -o $NAME-kops-tf --target terraform`
1. run your TF
1. `kops rolling-update cluster`

**Comment by satran** [comment]
I have been using kops for a while now and would love to contribute. If it’s okay I would like to work on this.

**Comment by gambol99** [comment]
Controversial question but I thought I'd ask :-) .. Should we support for all three streams? .. i.e. do we need to support three ways of building a kops cluster in the same cloud beyond backwards compatibility

**Comment by rdrgmnzs** [comment]
@gambol99 at least for me, currently not having the ability to export TF templates would just about kill the way I use Kops. This is because I modify the outputted templates to support some of the things I do. Such as re-using a already create SG and IAM role.

I know there is a PR pending that will cover both of those feature but I imagine many other folks having similar requirements, that may not yet be in the pipeline.

**Comment by shamsalmon** [comment]
Agree with @rdrgmnzs . If there was a way to define the "base" terraform that was generated and we can change things as needed (re-using EIPs, additional routes for VPC peering) that would be awesome.

**Comment by jhedev** [comment]
I'm using Kops in combination with terraform for nearly a year now and it's basically the workflow above. If no one has started working on this so far, I could try :)

**Comment by ApsOps** [comment]
@jhedev Please go ahead :)

How do you handle rolling updates? That's the only thing stopping me from using TF workflow right now. I have a few ideas, but not sure what's the safest approach.

**Comment by jhedev** [comment]
I don't know if what I am doing is the safest approach :D 

I am currently running multiple (rather small,i.e. only a couple of nodes) clusters on AWS using a combination of kops + terraform for the setup. 

All manifests are stored in a single git repo. The terraform config is split into multiple environments. In a subdirectory I have stored the kops yaml files (cluster.yaml, instance group yamls). To change any settings of the cluster the corresponding file is edited and I will run `kops replace -f ` and `kops update` to generate the terraform output. kops' terraform output is referenced as a terraform module. The deployment pipeline takes care of all the terraform plan and apply stuff. 

Since all IGs are in autoscaling groups and only the launch configuration is updated I need to run `kops rolling-update <ig-name>` afterwards (if required). Or manually drain and/or terminate the nodes to force recreation. This process is currently not automated but could be in the future; especially in large clusters it could take quite a while. 

So far this has worked very reliable and I had not any issues (even in a HA setup). However, as I mentioned the cluster is rather small so I'm not sure how easily this can be done in clusters with 100s of nodes ;)

**Comment by chrissnell** [comment]
I assume that the multi-cluster folks in here are dropping the generated TF configs into separate, per-cluster directories and then laying additional TF configuration into each of those directories to do things like VPC peering and routes.

I experimented with putting the TF configs of multiple clusters into the same directory put `terraform plan` balks because of some namespacing issues that cause conflicts between the individual cluster configs.  There are some object names and such that need to renamed to something cluster-specific.   My reason for wanting to store TF configs for multiple clusters in one directory is so that I could also drop a config for the VPC peering that would reference the VPC IDs from each cluster.

Does this sound like a useful pattern to anyone here?  Is it worth opening a separate issue and perhaps patching the TF generator to use completely unique and specific names for all resources?
