### ISSUE TITLE
upgrade weave to 2.1.3

### ISSUE THREAD

**Issue by jjo** [kubernetes/kops#4069]
`kops-1.8` still uses `weave` 2.0.5, we should switch to 2.1.3, some picks from
https://github.com/weaveworks/weave/blob/master/CHANGELOG.md ->
* Improved Kubernetes Network Policy - Weave Net now supports the 'v1' policies introduced in Kubernetes 1.7 as well as the 'beta' policies supported previously (_read_: weave 2.0.5 is _unusable_ for 1.7+ network policies)
* Weave Net now reclaims IP addresses owned by Kubernetes nodes which have been deleted from the cluster - this avoids running out of IP addresses when many nodes are added and deleted over a long period (_read_: with node recycling from e.g. kops upgrades, you can potentially exhaust weave IP allocation)

**Comment by gambol99** [comment]
hi @jjo .. i believe this has been [merged](https://github.com/kubernetes/kops/pull/3944) already

**Comment by jjo** [comment]
Ah cool thanks, I spotted it while using kops 1.8
(seeing that PR to actually merged just a few hours ago, waiting for 1.8.1 now :) ).

Cheers! --jjo

**Comment by cmur2** [comment]
Today we discovered that kops 1.8.0 still uses the very outdated weave 2.0.5 because one of our clusters could not launch new pods since the IP address allocation pool was exhausted.

Could you please think about releasing a new version of kops including the fix from https://github.com/kubernetes/kops/commit/1b9486a7af97a9df02fbcff9d7322e63ff2ad44b or even a more recent weave version 2.2.0 soon?
