### ISSUE TITLE
Openstack documentation

### ISSUE THREAD

**Issue by hingstarne** [kubernetes/kops#4111]
I would appreciate if there would be a hint how to use the openstack implementation.
Is there any docs on it?

**Comment by chrislovecnm** [comment]
It is still a work in progress, I do not have the engineers name handy.  @dims who is working on this again?

**Comment by dims** [comment]
Chris, that would be @zengchen1024 

zengchen, Can you please add some docs when there are some scenarios working?

**Comment by zengchen1024** [comment]
@hingstarne Currently, it can not build a k8s cluster on openstack platform by kops. Up to now, I have implemented the framework of openstack that you can run the command like "kops create cluster --cloud openstack --zones nova -v 15 --target direct --yes myoscluster4.k8s.local", but it does not really deploy a cluster because there are many tasks to be done.  Besides, I have implemented the tasks like volume, security group etc and I will continue to add other tasks such as network, auto scaling. If you are interested in this work, we can do it together.  Thanks!

**Comment by xlucas** [comment]
@zengchen1024 How fare are you on this matter ? Do you need some help ?

**Comment by zengchen1024** [comment]
@xlucas Sorry. the key reason is I have not much time to do the work on this issue. But I promise I will complete it. The next week is Chinese New Year and I will leave for about a week. I will start to work on it when I come back. Thanks for your comments.

**Comment by chrislovecnm** [comment]
@xlucas if you want to help, I do not think tasks for networks or creating instance / something like autoscaling groups are completed.
