### ISSUE TITLE
FailSwapOn kubelet option is not exposed by Kops

### ISSUE THREAD

**Issue by bitfusion-brian** [kubernetes/kops#4123]
Kubelet config is defined in pkg/apis/kops/componentconfig.go and many other files. FailSwapOn is not part of any of these files. In K8s >= 1.8.0, this options defaults to 'true', and there is no way to set it to 'false'.

-- edit below with additional info --

Kops is missing the `--fail-swap-on` config option for Kubelet. In kubernetes/kubelet version <1.8.0, kubelet uses the flag `--experimental-fail-swap-on` which defaults to `false`. In kubernetes/kops >=1.8.0, kubelet uses the flag `--fail-swap-on`, and it defaults to `true`. 

If `--fail-swap-on` is set to `true`, kubelet will error out and never start if the system has swap enabled. If try to use latest kops with kubernetes >= 1.8.0, a system that has swap enabled will never join the cluster because kubelet will never start, and there is no way to  change the `--fail-swap-on` option to `false`.

Kops allows you to specify multiple configuration options for Kubelet. These configuration options can be found [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L22), among a couple other places. If the config option you are trying to affect is not in this model, then it will not get passed to kubelet.

Like I said, there are many places that the kubelet model shows up: [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L22), [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha1/componentconfig.go#L22), and [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go#L22). There also appears to be some generated code that affects the kubelet options as well, for instance these files: [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/zz_generated.conversion.go) and [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/zz_generated.deepcopy.go).

**Comment by chrislovecnm** [comment]
@bitfusion-brian more details please?

**Comment by wannabesrevenge** [comment]
just to clarify, this is my main account. @bitfusion-brian is me.

Kops is missing the `--fail-swap-on` config option for Kubelet. In kubernetes/kubelet version <1.8.0, kubelet uses the flag `--experimental-fail-swap-on` which defaults to `false`. In kubernetes/kops >=1.8.0, kubelet uses the flag `--fail-swap-on`, and it defaults to `true`. 

If `--fail-swap-on` is set to `true`, kubelet will error out and never start if the system has swap enabled. If try to use latest kops with kubernetes >= 1.8.0, a system that has swap enabled will never join the cluster because kubelet will never start, and there is no way to  change the `--fail-swap-on` option to `false`.

Kops allows you to specify multiple configuration options for Kubelet. These configuration options can be found [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L22), among a couple other places. If the config option you are trying to affect is not in this model, then it will not get passed to kubelet.

Like I said, there are many places that the kubelet model shows up: [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L22), [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha1/componentconfig.go#L22), and [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go#L22). There also appears to be some generated code that affects the kubelet options as well, for instance these files: [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/zz_generated.conversion.go) and [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/zz_generated.deepcopy.go).

Couple questions:

1. As of now, I have some changes en route where I manually added `--fail-swap-on` to both the models and the generated files. Are there Makefile commands that I can use to automatically parse the model and add this option into the generated files?

2. Is there an example of how we handle the same flag with different names in different versions of kubernetes? This case being `--experimental-fail-swap-on` vs `--fail-swap-on`

@chrislovecnm I was intending on getting a PR out before holiday, but other things got in the way.

Adding this description to the ticket
