### ISSUE TITLE
kops not deploying the multi node kubernetes cluster on aws free tier

### ISSUE THREAD

**Issue by sujeetkp** [kubernetes/kops#4129]
I am trying to deploy a kubernetes cluster of 2 nodes and 1 master on aws.
But every time I try it creates 2 nodes but it does not create the master. I am completely new to kubernetes and aws free tier.

I tried it in 3 regions us-east-1, us-west-2 and eu-central-1, but every time It failed.

kubectl version

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 203.0.113.123:443: i/o timeout

kops version
Version 1.7.1 (git-c69b811)

I tried the below commands to create the Cluster (DNS/Hosted Zone is associated with the Private Default VPC)

Observations in us-east-1
----------------------------

Works fine for 

 kops create cluster \
 --cloud=aws \
 --zones=us-east-1d \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="2"

Does not work for the below commands

   kops create cluster \
 --cloud=aws \
 --zones=us-east-1d \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="2" \
 --master-count=1

Above command created only the master but did not create any nodes.
 
or

   kops create cluster \
 --cloud=aws \
 --zones=us-east-1d \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="3" 

Above command created one master and one node.

and 

   kops create cluster \
 --cloud=aws \
 --zones=eu-central-1a \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --node-count="2" \
 --master-count=1

Observations in us-west-2 
----------------------------

Below commands created only the nodes but not the master

  kops create cluster \
 --cloud=aws \
 --zones=us-west-2b \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="2" \
 --master-count=1

or

  kops create cluster \
 --cloud=aws \
 --zones=us-west-2b \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="3" 

Observations in eu-central-1 
----------------------------

Below commands did not create any master or node.

 kops create cluster \
 --cloud=aws \
 --zones=eu-central-1a \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="3" 

or

  kops create cluster \
 --cloud=aws \
 --zones=eu-central-1a \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --master-size="t2.micro" \
 --node-size="t2.micro" \
 --node-count="2" \
 --master-count=1

or

 kops create cluster \
 --cloud=aws \
 --zones=eu-central-1a \
 --name=useast1.k8s.kubernetes.com \
 --dns-zone=kubernetes.com \
 --dns private \
 --node-count="2" \
 --master-count=1

**Comment by geojaz** [comment]
@sujeetkp Can you run please try running your cluster creation command with verbose logging and share those logs with us? ie:

`kops create cluster --cloud=aws ... -v=10`
`kops update cluster --yes -v=10`

You also shouldn't need double (or single) quotes on any of your flagged commands but I don't think that's your issue.

**Comment by sujeetkp** [comment]
@geojaz : Please find the attached logs.

[create_logs.txt](https://github.com/kubernetes/kops/files/1580409/create_logs.txt)
[update_log.txt](https://github.com/kubernetes/kops/files/1580410/update_log.txt)

**Comment by geojaz** [comment]
@sujeetkp I'm sorry I missed this before, but could you upgrade to the latest release (kops 1.8) and  We don't support previous releases of kops because it's possible to manage previous versions of kubernetes with a newer kops. You don't necessarily need to run kops 1.7 with kubernetes 1.7.

I am not seeing the same situation as you are, but I don't have a free tier account. My understanding is that in the free tier, you should be able to launch multiple t2.micros, but I'm not sure. If you're still having issues, launch the cluster and take a look at the auto scaling groups in the AWS console and make sure that they are the size you expect and review and error messages in there. Hope that helps!

**Comment by geojaz** [comment]
possibly related to #3751

**Comment by sujeetkp** [comment]
@geojaz : Thanks a lot Sir. It worked like a charm after I updated the kops version to 1.8. My Cluster is ready.
But I am not able to validate the cluster using "kops validate cluster" command or the kubectl command is also not working.

I have created a "Hosted Zone" and attached it to my default VPC.

ubuntu@ip-172-31-86-134:~$ kops validate cluster
Using cluster from kubectl context: useast1.k8s.mykubernetes.com

Validating cluster useast1.k8s.mykubernetes.com


unable to resolve Kubernetes cluster API URL dns: lookup api.useast1.k8s.mykubernetes.com on 172.31.0.2:53: no such host

**Comment by geojaz** [comment]
@sujeetkp You're probably not able to connect to your cluster because you're using a private DNS zone. 172.31.0.2 looks like an internal IP address-  I'm not sure what your network topology looks like, but possible things that may help would be getting onto the network that k8s is running on so you'd have access to those DNS records and they would make sense or if it's exposed externally, you may be able to edit your local /etc/hosts to point to the actual location of the API server. 

It looks like the immediate issue has been resolved and this is more like k8s support now so I'm going to close this issue. You're welcome to join the kubernetes slack #kops channel and I'm sure someone there will have some ideas! Thanks

**Comment by punit-naik** [comment]
@sujeetkp Did you solve the DNS issue?

**Comment by gianfelipe93** [comment]
Has this issue been solved?

**Comment by gianfelipe93** [comment]
if anyone is going through this issue, for me it was just a matter of waiting a couple of minutes until the cluster gets created.
