### ISSUE TITLE
Allow setting clusterSpec.Kubelet.PodInfraContainerImage

### ISSUE THREAD

**Issue by macropin** [kubernetes/kops#4135]
It looks like the pause image is [hardcoded](https://github.com/kubernetes/kops/blob/e17127bd501cb692b6198d73dcb0d4ef5e16d3a8/pkg/model/components/kubelet.go#L200) to `gcr.io/google_containers/pause-amd64:3.0`. Please allow this to defined. This will allow usage of alternate pause containers, which in this case is necessary to get ahead of this zombie reaping issue: Ref: kubernetes/kubernetes/issues/50865. Also ref kubernetes/charts/issues/2989

**Comment by mrballcb** [comment]
The way I have managed this since I found the pause issue is by following a cluster create with a `kops edit ig` for each instance group and in the spec section override it:
```
  spec:
    kubelet:
      podInfraContainerImage: imeetops/pause-amd64:3.0.1
```
After doing a `kops update` for each ig, and a `kops rolling-update cluster`, all of the new nodes (and I do masters too for consistency) spawn images with the desired container.

**Comment by mrballcb** [comment]
It would be nice, allowing it to be specified from the kops cli, but I don't think it necessarily should require a new cli option.  Maybe a more generic option, such as `--set-item` could be added so that you can do
```
--set-item "instancegroup.*.spec.kubelet.podInfraContainerImage=gcr.io/google_containers/pause-amd64:3.1"
```
on the commandline and it would insert it into the config.  It would do it for all instance groups.  This does not seem to step on the toes of any available cli options.  But it does seem like it would put its claws deep into config generation, making it a very dangerous option.

**Comment by macropin** [comment]
@mrballcb Thanks, that seems to have worked! I initially tried updating the kops generated terraform userdata, and rebuilding the cluster, but it seems the values defined there are not used.
