### ISSUE TITLE
Question: sizing of utility subnet

### ISSUE THREAD

**Issue by keesveerman** [kubernetes/kops#4159]
I'm trying to convert our public cluster to a private one. Although that went quite well i have now the challenge that my utility subnets are too small as they are defined as a /28. I have several services with external elb's which refuse to be created since i NEED to have 8 ip's free. 
Which means that in a /28 with 5 reserved for aws itself, an igw and 8 free ip's i can only have 2 internet facing elb's.

Since my vpc cidr is a /22 how come the utility subnet is defined so terribly small??
Is there a way to have kops make utility subnets at least a /27?

subnets:
vpc = 10.223.32.0/22
utility-eu-west-1a = 10.223.32.0/28
utility-eu-west-1b = 10.223.32.16/28
utility-eu-west-1c = 10.223.32.32/28
eu-west-1a = 10.223.32.128/25
eu-west-1b = 10.223.33.0/25
eu-west-1c = 10.223.33.128/25

kops version = 1.8.0
k8s version = 1.8.6
cloud provider = AWS

**Comment by 1810755jiawei** [comment]
15815579644


地址:深圳


邮箱:101o@139.com


手机:15815579644















------------------ 原始邮件 ------------------




 
 发件人: Kees Veerman  <notifications@github.com>
 

 
 发送时间: 2017-12-28 17:53:35
 

 
 收件人: kubernetes/kops  <kops@noreply.github.com> 
 

 
 抄送: Subscribed  <subscribed@noreply.github.com> 
 

 
 主题: [kubernetes/kops] Question: sizing of utility subnet (#4159)
 



I'm trying to convert our public cluster to a private one. Although that went quite well i have now the challenge that my utility subnets are too small as they are defined as a /28. I have several services with external elb's which refuse to be created since i NEED to have 8 ip's free.
 Which means that in a /28 with 5 reserved for aws itself, a nat gateway and 8 free ip's i can only have 2 internet facing elb's.

 Since my vpc cidr is a /22 how come the utility subnet is defined so terribly small??
 Is there a way to have kops make utility subnets at least a /27?

 subnets:
 vpc = 10.223.32.0/22
 utility-eu-west-1a = 10.223.32.0/28
 utility-eu-west-1b = 10.223.32.16/28
 utility-eu-west-1c = 10.223.32.32/28
 eu-west-1a = 10.223.32.128/25
 eu-west-1b = 10.223.33.0/25
 eu-west-1c = 10.223.33.128/25

 kops version = 1.8.0
 k8s version = 1.8.6
 cloud provider = AWS

**Comment by amir-mehler-via** [comment]
I have slightly bigger utility subnets - but it's still not enough for several private ELBs.
I have two utility subnets sized /27 each (30 addresses).
When trying to create MORE utility subnets in the same AZs kops gave me an error.

Can I enlarge the existing utility subnets? What will be the effect, since I'll need to completely move one of them.
