### ISSUE TITLE
Add support for rkt

### ISSUE THREAD

**Issue by johnt337** [kubernetes/kops#433]
Any plans on adding support for rkt as an alternative to docker?

**Comment by justinsb** [comment]
Absolutely, once it is in the main branch of kubernetes!

Going to close as this is really more of a kubernetes issue, if that's OK.  But please reopen as soon as k8s supports it and we'll get it into kops.

**Comment by johnt337** [comment]
@justinsb awesome, thanks for the update.

**Comment by cdrage** [comment]
@justinsb isn't it already in the main branch of Kubernetes? (1.4.0 iirc)

**Comment by apobbati** [comment]
This is supported in Kubernetes 1.3+

http://kubernetes.io/docs/getting-started-guides/rkt/

Any chance of revisiting this issue?

**Comment by dmcnaught** [comment]
Can we reopen this ticket please? 😄

**Comment by chrislovecnm** [comment]
Contributions are always appreciated!  If anyone wants to contribute this please reach out!

**Comment by dolftax** [comment]
@chrislovecnm I would like to work on this. Help me with which files to look for? This docs LGTM - https://kubernetes.io/docs/getting-started-guides/rkt/

**Comment by gokulreddy07** [comment]
Any updates on supporting rkt ?

**Comment by arielkung** [comment]
+1, this would be a great additon

**Comment by chrislovecnm** [comment]
Nobody that I know is working on support at this time. Always happy to have contributions!

**Comment by PI-Victor** [comment]
sounds interesting, would like to take a shot at it starting tomorrow if nobody's working on it.

**Comment by dolftax** [comment]
@PI-Victor Can we collaborate?

**Comment by PI-Victor** [comment]
sorry for the late reply - @dolftax sounds good, what do you have in mind?

**Comment by PI-Victor** [comment]
Here's what i've got so far as a starting point.

The entire documentation about what rkt needs to work with k8s is here:
https://kubernetes.io/docs/getting-started-guides/rkt/

rkt on CentOS is problematic:
- https://coreos.com/rkt/docs/latest/distributions.html#centos 
- https://github.com/rkt/rkt/issues/1305

rkt version on k8s master branch is pretty old, the last bump was to v1.9.1 over a year ago. (could have a look and maybe try to bump it)
https://github.com/kubernetes/kubernetes/commit/b3d4f91aac8a1cae8fae3499ba3f0ce7e5451998
latest rkt release is 1.28.1 Aug. 2nd. I think this happened because the focus has changed to the project below.

the current effort to make rkt work with the CRI in k8s is in active development
- https://github.com/kubernetes-incubator/rktlet

**Comment by PI-Victor** [comment]
i've started hacking around in [a branch fork](https://github.com/PI-Victor/kops/commit/4cfc0e8aa0365a0aaa1264ef60dcea76f02a4d59) basically just mimicking what the docker builder model does, but i'm unsure weather to submit a WIP PR at this point.

**Comment by dolftax** [comment]
@PI-Victor I need to get more familiar with Kops codebase. Will look into it tomorrow (IST) and update here.

**Comment by PI-Victor** [comment]
given the low demand for this, i'd say we can add support to kops whenever rktlet is stable. https://github.com/kubernetes-incubator/rktlet
