### ISSUE TITLE
Kops doesn't fail when it does not have access to the Route53 zone

### ISSUE THREAD

**Issue by MrTrustor** [kubernetes/kops#434]
Hello,

I created a K8s cluster with kops. Following the README, I created a R53 zone, but in another AWS account. kops was happy to continue and did not report any problem. It took me a while to understand that in fact kops should have created automatically some entries in the zone.

So, I think kops should throw some errors here. Also, the doc should explicit what the R53 zone is used for, what entries should be created, etc.

Thanks for the work!

**Comment by tazjin** [comment]
It's not actually `kops` that creates entries in the zone, at least not the `kops`-binary that you run on your machine. The master adds those entries which is why `kops` sets up the IAM policies for the master role in a way that allows Route53 access.

I think in your specific case you may want to delegate a subdomain to the account that the cluster is running on. You can use IAM trust relationships etc. etc. to delegate access across accounts but it gets messy and complicated very fast.

**Comment by MrTrustor** [comment]
Ok, I'll try it this way, maybe it will also solve the problem I described on #436. The doc still could be more clear on what exactly is happening. I'll check back in after my tests.

**Comment by MrTrustor** [comment]
After some tests, it works as you described @tazjin. I leave this issue open for the documentation aspect.

**Comment by justinsb** [comment]
Tagging as documentation.  There may be more we can do, but documentation is the first step.

**Comment by chrislovecnm** [comment]
I think this is [documented](https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md), and we have a discussion here as well. https://github.com/kubernetes/kops/issues/1873

Can we close this?

**Comment by MrTrustor** [comment]
Yes, I'm closing.
