### ISSUE TITLE
Schedule/roadmap?

### ISSUE THREAD

**Issue by pschuegr** [kubernetes/kops#4566]
First, thanks for all your work on Kops.

I'm not sure if there's a better place to ask this question: is there a tentative schedule or roadmap for kops releases?  Are we going to see 1.9 anytime soon?

**Comment by chrislovecnm** [comment]
We cut an alpha 2 days ago, please test and let us know.  We do not have a good schedule but are working on getting 1.9 out.

**Comment by taylorshaulis** [comment]
I tried out the alpha and did a kops update cluster as part of the move from kops 1.8.1 to 1.9.0-alpha.1.  The master instances failed to validate and eventually went unresponsive.  To recover I switched back to 1.8.1 and did a kops update cluster --cloudonly due to the api being unavailable.

I am more than happy to help test and provide information for clusters hosted in AWS.  

What information should I gather and what commands should I run to best help debug issues I encounter with the alpha kops?

**Comment by jpds** [comment]
@taylorshaulis See #4546 for that upgrade issue.

**Comment by chrislovecnm** [comment]
#4546 is fixed in master

**Comment by taylorshaulis** [comment]
Much thanks
