### ISSUE TITLE
Create limits

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#471]
kube-up now includes default limits; we should probably include the same

**Comment by chrislovecnm** [comment]
@brandoncole thoughts on this?

**Comment by brandoncole** [comment]
I'm coming in a bit late on this, for context this is about pre configuring limits per: http://kubernetes.io/docs/admin/limitrange/ on the cluster?  

Workaround today would be using `kops` to stand up cluster first then use `kubectl` to create and apply to the namespaces correct?

I can think of a few reasons it might make sense to put this into `kops` such as:

1. Default limits based on number of nodes / size provisioned during startup
2. Differences based on the cluster type - AWS or GCE
3. Best practices have been devised from existing clusters we want to promote

**Comment by justinsb** [comment]
In #479 we had the suggested command: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/saltbase/salt/kube-admission-controls/limit-range/limit-range.yaml`

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/974 Closes this

**Comment by msteffen** [comment]
Hello all, I know this bug is now quite old, and I apologize if I'm asking this in the wrong place, but I'm unsure what a better forum might be.

**Is there any way to prevent kops from creating this LimitRange?**

(Currently we're using kops in our testing suite, and our workflow is to create a cluster with kops and then immediately remove the LimitRange with `kubectl`, but that seems inelegant. In general, is there any way to give kops a kubernetes manifest that overrides the default?)

**Comment by ferrouswheel** [comment]
Having a "limit" (I mean a "request", the name limit is overloaded!) means I was confused as to why and where cpu requests of 100m per container were being set. It would be great for this to be documented or part of the kops cluster spec.

**Comment by chrislovecnm** [comment]
Can you open a new issue for us? I am glad I caught this on a closed issue ;)
