### ISSUE TITLE
Calico with CrossSubnet doesn't launch on CentOS hosts

### ISSUE THREAD

**Issue by gwkunze** [kubernetes/kops#4718]
Repost of closed (by submitter) issue #4331.

Re-opening because while the workaround works, any time a master is restarted, the original bootstrap channel is applied again undoing the patch.

The problem lies in the the k8s-ec2-srcdst deployment attempts to mount `/etc/ssl/certs/ca-certificates.crt` from the host into the container. But this file doesn't exist in centos, it should instead be either `/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt` or `/etc/ssl/certs/ca-bundle.trust.crt`.

I've tried making `/etc/ssl/certs/ca-certificates.crt` a symlink to the correct file in the master instancegroup's `additionalUserData` but for some reason that symlink's existence seems to cause docker to not trust any certificate anymore in turn causing kubelet not being able to start (pull) any container.

I've looked into creating a PR for this but afaict the template context for the addons does not contain knowledge about the current distribution, the context is only the `ClusterSpec` and I didn't see any template functions that return something like the distribution either.

**Comment by fr0stbyte** [comment]
@caseydavenport @blakebarnett I am interested in working on this one. 
I am thinking that a flag ( `--ssl-cert-path` ) can be added in conjunction with a field (`SSLCertPath`) on the `ClusterSpec`.
Additionally, a template function can be added that takes a default value for the  ssl path. If the `SSLCertPath` is defined then use that otherwise use the provided default. 
Is this a valid approach or is there some other less intrusive option ?
