### ISSUE TITLE
Consistant use of 'help' keyword on the CLI

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#480]
```
$ kops help
kops is kubernetes ops.
.......
$ kops create help
Create resources
.......
$ kops create instancegroup help
<opens an editor>
```

Should `help` for instancegroup attempt to make an instance group named help?

**Comment by yissachar** [comment]
FYI, `--help` is the proper help flag and has consistent behaviour:

```
$ kops --help
$ kops create --help
$ kops create instancegroup --help
```

All show the help output for the command. 

The explanation for the output you see is as follows:

```
$ kops help
```

Root level command `help`, print help output.

```
$ kops create help
```

Unknown command `help` for `create`, print help output. The use of `help` here is misleading, since you'll receive the same output for any invalid command, e.g.

```
$ kops create asdfasdf
```

And finally,

```
$ kops create instancegroup help
```

The `create instancegroup` command takes a single positional parameter, in this case `help`, so create an instancegroup called `help`. It would do the same for any other input:

```
$ kops create instancegroup asdfasdf
```

Will create an instance group called `asdfasdf`.

**Comment by justinsb** [comment]
So I don't think there is anything we should do here?  Closing, but comment/reopen if you disagree.
