### ISSUE TITLE
Deprecate etcd event cluster

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kops#5004]
1. Describe IN DETAIL the feature/behavior/change you would like to see.

According to @chrislovecnm the etcd event cluster isn't needed anymore, but as it is legacy thing it is hard to remove.

2. Feel free to provide a design supporting your feature request.

Add logic so new clusters is created without a etcd event cluster, but still support old cluster with a etcd event cluster.

**Comment by andrewsykim** [comment]
Thread: https://kubernetes.slack.com/archives/C8MKE2G5P/p1523721679000164

**Comment by andrewsykim** [comment]
It seems like this is actually doable by removing `events` from [here](https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/populate_cluster_spec.go#L43) and this would only be applied for new clusters since we only read those values when we write the initial cluster spec [here](https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go#L630-L651). I'm not sure  if we need to account for iops/size for new volumes but that change seems like a decent start. @justinsb @chrislovecnm thoughts?

**Comment by andrewsykim** [comment]
The original reason for having a separate events cluster was due to scalability issues with etcd (https://github.com/kubernetes/kubernetes/issues/32361) and at the time it was recommended to separate events to a separate cluster.  Having said that, it seems in the issue most of the scalability problems have been addressed in etcd3(?) so we may want to revisit this when we support etcd3. cc @justinsb
