### ISSUE TITLE
Is it possible to assign Elastic IP to nodes(master/slave) during Kubernetes cluster creation in AWS?

### ISSUE THREAD

**Issue by ma-sattari** [kubernetes/kops#5007]
Hi,

My backend services in K8s cluster on AWS need to connect to an external resources from a partner. However,  the partner requires us to prepare a list of fixed IPs to permit our access.

AFAIK I cannot change the IP address of nodes after built because the connection between the nodes will be lost. I was wondering if there is a method to assign Elastic IP to nodes during the cluster creation or after creating it?

**Comment by vicenteampliffy** [comment]
Hi,

You could create a deployment which launches a POD who does what you need. That's exactly what I'm doing myself: I select the node where this POD is running and assign it an EIP. If the POD restarts, then it reassigns the EIP again to the current POD's node. Just be careful to not do too much reassignments, as Amazon will charge for an excess of reassignments.

Hope that helps.

**Comment by annismckenzie** [comment]
@vicenteampliffy we were thinking of creating a DaemonSet of an ElasticIP reconciler that works exactly like that. Why did you choose a deployment instead? Are you targeting one node specifically? I'd imagine using a DaemonSet with an optional node selector would work better. But your usecase is probably confined to doing that on a single node.

@MaSattari you can't do that during cluster creation because Kops uses Auto Scaling groups and these cannot assign Elastic IPs. That's a shortcoming of AWS, not Kops. :/

**Comment by vicenteampliffy** [comment]
@annismckenzie , yes, we only need one node with the EIP. I guess, if you need to keep a list of EIPs, then it's better to have a Daemonset with some logic to assign the correct IPs to the correct Nodes.

**Comment by KIVagant** [comment]
See also https://github.com/kubernetes/kops/issues/3182

**Comment by tomekit** [comment]
/reopen
Is it possible today?

My use case is actually different. I am running NginX Ingress with without load balancer (clusterIp service type) and I need a stable IP address for my nodes, since my external DNS is relying on IP not changing.

**Comment by grebois** [comment]
@tomekit I manage to make this work by attaching an EIP to my ELB and then configuring it on the nodes, like https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#attaching-existing-load-balancers-to-instance-groups
