### ISSUE TITLE
How to create multi cluster by kops

### ISSUE THREAD

**Issue by hpham04** [kubernetes/kops#5074]
I want to create multiple cluster, each cluster has its own responsibility such as one for database, one for web application
Is it possible to do it by kops
If not, what is the alternative 
Can you please help to advise

**Comment by kaazoo** [comment]
You can deploy different clusters with kops by just using different cluster names. In order to make them more independent, you could use a different VPC for each of them (if using AWS).

If you just want to separate applications from each other, you could also deploy them in different k8s namespaces inside a single cluster and control communication with network policies:
https://kubernetes.io/docs/concepts/services-networking/network-policies/
