### ISSUE TITLE
Can 'kops update cluster' be run concurrently?

### ISSUE THREAD

**Issue by mkornacker** [kubernetes/kops#5086]
I couldn't find this in the docs:

I'm wondering whether it's safe to run 'kops update cluster --yes' concurrently (from multiple machines, but with the same --name and --state).

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
1.9.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

**Comment by gkope** [comment]
You mean `rolling-update cluster` right?

If yes, you can't run concurrently, but you can change the flags to make ir run faster, and with cloud-only if you are not worried about your pods and graceful periods.

**Comment by mkornacker** [comment]
No, I really meant 'kops update cluster', not 'kops rolling-update cluster'.

Can two of those be run concurrently? This isn't about speed, it's
basically two independent parties adding instance groups separately and
then spinning them up in EC2.

**Comment by justinsb** [comment]
So I would say it's not a great idea, but if you're modifying or creating separate instance groups I think you would get away with it.  Or if two processes are making the same changes (e.g. if you're both applying a different firewall rule on the API) then I think you would get away with that also, because we retry each individual task, and each task typically does a `Find` followed by an `Update`, and so I think a conflict on the `Update` because of a concurrent operation would just be skipped when `Find` detects that the expected state matches the actual state.

That said, it's not really something we've designed for or something we've tested and can claim to support.  So officially unsupported, but you will likely be OK!
