### ISSUE TITLE
User reported issue with zero length folders in S3

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#520]
Somehow a user reported they had real "folder" objects in S3, which were zero length files.  Unclear who created them!  But kops did not tolerate this - it tried reading instancegroup/instancegroup

**Comment by kemitche** [comment]
User in question here. I'm unsure how I ended up creating the 0-size "folder" objects in S3, but I had one for the entire kops cluster. Removing the 'folder' objects allowed me to move forward.

I have not been able to reproduce the issue since, but if I figure out what triggered the entries to get added I will add more info here.

**Comment by justinsb** [comment]
I believe this to be fixed by #549.  Please reopen if you see it again.
