### ISSUE TITLE
Disable scheduling on all nodes during cluster rollout.

### ISSUE THREAD

**Issue by john-delivuk** [kubernetes/kops#5206]
------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

Currently when you do a cluster rollout it just cordons, and drains each node it's replacing. Is it possible to have a flag for the rollout to cordon all nodes that need to be replaced. Idea being is that this way when a pod is moved to a new node, it currently can keep moving the pod to another terminal node. There would be a short period during the first node where you wouldn't be able to schedule, but would provide with some smoother operations.

**Comment by huang-jy** [comment]
If you had more than one instance group of workers then this could work (mass-cordon the instance group you're updating, for example).

However if you only have one instance group, then this would actually be a bad idea (IMO) since you're preventing any scheduling of new work onto the worker nodes during the rollout, including replacing crashed/terminated pods, with work only able to be scheduled once the first worker is registered into the cluster and ready. Also note, you would then have a backlog of pods waiting to be scheduled while the other workers are being replaced.

If you had, for example, 40 replicas of nginx since you have 40 workers, then Kubernetes would attempt to schedule all 40 pods onto the one worker when it registered.

Also, assuming the work to be scheduled on the first instance group WAS able to be rescheduled onto the second instance group, you would be putting those worker nodes under more strain -- and possibly leading to unschedulable pods, unless you have node autoscaling setup.
