### ISSUE TITLE
Create PKI with terraform components

### ISSUE THREAD

**Issue by eldondevat** [kubernetes/kops#5266]
1. Describe IN DETAIL the feature/behavior/change you would like to see.
Currently, when using kops with amazon AWS and terraform output, kops creates a PKI and populates the bucket/prefix with a number of different files for kops runtime functionality. There is functionality to use [terraform as a PKI provider](https://www.terraform.io/docs/providers/tls/index.html) as well. For organizations that are trying to push declarative infrastructure via terraform, also having these components be built as a part of the terraform files kops creates could enable improved communication between terraform and kops.

**Comment by eldondevat** [comment]
@itskingori @justinsb Can somebody take 2 minutes to give me feedback on this?

**Comment by itskingori** [comment]
@eldondevat Unfortunately, I don't know much about this. I use kops with terraform as is, and the certificates are "up-there" in the cluster state.

The only thing I'd say is that we're kinda ok with how it is, since we don't want to have the pki files and secrets in our repo. We keep a local copy of the state by doing something like this:

```console
$ aws s3 cp "${source}" "${destination}" \
  --recursive \
  --exclude "pki/*" \
  --exclude "secrets/*"
```
