### ISSUE TITLE
Consider deprecating older K8s versions

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/kops#5492]
As stated in our [compatibility matrix](https://github.com/kubernetes/kops#compatibility-matrix), we support back to 1.5.x.  

We certainly don't test as extensively (or at all?) on those really old versions so how and/or when is the right time to officially deprecate them?

How should we communicate that to Kops users?

**Comment by rdrgmnzs** [comment]
Thanks for creating this @mikesplain! Didn't meant to hijack your PR.

As state in the PR it was more of a passing thought, specially since we don't test as in depth for some of the older version. I was wonder if we still wanted to mark those versions as supported to be operated with newer versions of Kops. As @justinsb mentioned the amount of code to support those older version is minimal.
