### ISSUE TITLE
Kops 1.9.2 Create Cluster Failed on AWS

### ISSUE THREAD

**Issue by wwyhy** [kubernetes/kops#5521]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.9.2 (git-cb54c6a52)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
===> already created the s3 and exported KOPS_STATE_STORE and we have already a public domain test.com.cn on AWS(test.com.cn is example).

kops create cluster test.com.cn --cloud aws --master-count 3 --master-zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c --master-size t2.medium --node-count 3 --zones ap-southeast-1a,ap-southeast-1b,ap-southeast-1c --node-size m5.xlarge --dns-zone test.com.cn --dns public --vpc vpc-0b4d6eff755a54891 --networking calico --topology private --image ami-8e0205f2 --ssh-public-key ~/.ssh/id_rsa.pub

kops update cluster test.com.cn --yes

**5. What happened after the commands executed?**
 kops validate cluster
Using cluster from kubectl context: test.com.cn

Validating cluster test.com.cn

unexpected error during validation: error listing nodes: Get https://api.test.com.cn/api/v1/nodes: EOF
**6. What did you expect to happen?**
it should be show the correct info of the cluster 

The cluster create is failed, after checked that there is no EC2 instance launched, and DNS records in Route53 is incorrect. 

api.test.com.cn. | A | ALIAS api-test-com-cn-02e3j4-2367892345.ap-southeast-1.elb.amazonaws.com. (z1lgt91p8swle5) | No | - |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | api.internal.test.com.cn. | A | 203.0.113.123 | - | - | 10 |   |   |   |   |  
  | etcd-a.internal.test.com.cn. | A | 203.0.113.123 | - | - | 10 |   |   |   |   |  
  | etcd-b.internal.test.com.cn. | A | 203.0.113.123 | - | - | 10 |   |   |   |   |  
  | etcd-c.internal.test.com.cn. | A | 203.0.113.123 | - | - | 10 |   |   |   |   |  
  | etcd-events-a.internal.test.com.cn. | A | 203.0.113.123 | - | - | 10 |   |   |   |   |  
  | etcd-events-b.internal.test.com.cn. | A | 203.0.113.123 | - | - | 10 |   |   |   |   |  
  | etcd-events-c.internal.test.com.cn. | A | 203.0.113.123 | -

I am not sure if this is bug or something else, i have to choose bug. Could someone please help on this? thanks in advance！

BTW, I can create cluster with kops 1.9.1 with K8S 1.9.6 successfully with same configurations last week.

Thanks！
Br, Wayne

**Comment by gladiatr72** [comment]
Greetings,

That's normal.  The important part of the log message is '_got an error indicating that the IAM instance profile "nodes.test.com.cn" is not ready_'.  

Another approach would have been to poll the IAM API to check for the successful creation of the _IamInstanceProfile_ role before attempting to create the instance that depends on that role.  The brute-force method is uglier when log verbosity is increased, but I imagine it was chosen since it skips the last exchange (q: dependency read? a: yes.  -> create instance). It would not surprise me if it also dodges some default API rate-limits as well.

**Comment by wwyhy** [comment]
after checked that it is AWS issue. so close this one.

**Comment by pankajmt** [comment]
I ran into this today with kops 1.10.0. Went away when I got rid of the --subnets (specifying subnet ids) in my config, which was the last addition i did. wonder if this is still worth a pursuit, rather than being tagged as an AWS issue.

**Comment by bryan831** [comment]
I am thinking it is an aws issue too. I created a cluster the day before with same manifests, and it worked, but today it does not.   

After running `kops update cluster` I noticed this message:   
`Task did not have an address: *awstasks.LoadBalancer.....`  

I think it has something to do with ELB, when it doesn't work the cluster cannot be validated too.   

In my case it created all the resources, including EC2 instances, but `kops validate cluster` fails with the same error.

**Comment by jemc** [comment]
If this is an expected error, any chance we can just fix the "unexpected error during validation" log line?

In our local codebase we run `validate` on loop when bringing up the cluster until the cluster is ready, I currently have to echo advice that the "unexpected error" is expected, so that the user of the CLI tool doesn't assume that there is an issue with the loop while they wait for it to go green.

**Comment by naveeng68** [comment]
Try below version(it may be resolve ur issue)
Use kops version 1.13 (kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16)
and kubectl version 1.13.10
