### ISSUE TITLE
Kops - HTTP/HTTPS proxy and SSL inspection

### ISSUE THREAD

**Issue by krazykid** [kubernetes/kops#5575]
Hi. I'm trying to create and manage a k8s cluster on AWS using kops. When I use kops, I'm on a network that has both an http/https proxy and an SSL inspector (basically doing a man-in-the-middle attack on SSL). I'm on a Mac with kops installed via brew.

Almost all kops commands come back with an SSL based error like: 

```
error reading cluster configuration "gpu.useast1.dev.mk8s.org": error reading s3://clusters.dev.mk8s.org/gpu.useast1.dev.mk8s.org/config: Unable to list AWS regions: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority
```

I was wondering if you could point me to the various CA Certificate stores that kops uses so I can add my company's root CAs into the root cert file.

**Comment by justinsb** [comment]
We use the standard AWS SDK here, which uses the standard go CA certificate store AFAIK.

This is pretty similar to https://github.com/helm/helm/issues/3384  I'm guessing the location changes due to static linking...

Is your company's root CA in the OSX keychain?  I'm not overly familiar with the details of how these configurations are set up, to be honest!
