### ISSUE TITLE
bootstrapscript_test.go is testing different things than we think it is

### ISSUE THREAD

**Issue by geojaz** [kubernetes/kops#5798]
See: 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kops/5795/pull-kops-bazel-test/1883/
#5795 
Verifying diffs CAN be a useful method of testing, but we're over-reaching what makes sense here. In this case I claim that we're not exercising the functionality of the code. We're just checking to make sure it either didn't change, or the person who wrote it anticipated that they'd need to fix the test. 

I personally don't really care what the bootstrapscript code looks like- do we need to be testing here? I expect e2e is a better way to attack this- it either works or doesn't. (And is left as an exercise to the reader.)

**Comment by justinsb** [comment]
The link has sadly expired, so I'm not 100% certain what you're linking to, but...

The thought here is that by materializing the output we make it easy to verify in a PR, and we have the HACK_UPDATE_EXPECTED_OUTPUT trick to make updating the output easy(ish).  We do want our output to be stable, because it is reported to the end user in diffs.

I do think we have too many tests and could probably prune them a bit without really hurting our coverage (particularly if we combined a few), but I think this sort of "expected output testing" makes PR reviews easier, and is probably easier on the whole than writing explicit tests for certain facets of the output.
