### ISSUE TITLE
kops ignore nodes if role isn't exactly 'node' or 'master'

### ISSUE THREAD

**Issue by phspagiari** [kubernetes/kops#5871]
**kops version:** `1.10`
**kubernetes version:** `1.10.8`
**cloud provider**: `aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops validate cluster`

**5. What happened after the commands executed?**
After adding this label to a instance group:
```
  nodeLabels:
    node-role.kubernetes.io/spot: "true"
```
I received this error:
```
W1003 17:44:47.030058   46233 validate_cluster.go:274] ignoring node with role "spot"
```

**6. What did you expect to happen?**
Kops should accept instance groups with multiple roles, even if `node` role is mandatory.

**9. Anything else do we need to know?**
I found the exactly place of the code that this is "hardcoded":
https://github.com/kubernetes/kops/blob/master/pkg/validation/validate_cluster.go#L252-L275

**Comment by justinsb** [comment]
So the intention of the label format was indeed to support multiple roles - but what role are these `spot` instances playing in your cluster?  It might be better to simply have them as the conventional master / node roles, but then label (or taint) them to indicate that they are spot instances?

But ... it depends on what you're trying to do.  Can you elaborate :-) ?

**Comment by dobesv** [comment]
The custom node roles are used by some pusher tools for working with AWS spot instances:

https://github.com/pusher/k8s-spot-rescheduler
https://github.com/pusher/k8s-spot-termination-handler
https://github.com/pusher/k8s-spot-price-monitor

This is how they document how to set it up, so I set it up that way.  The error from kops is annoying but not fatal, so I never dug deeper how to make both of these systems happy.

It does seem like a bug in `kops`, though, so that seems like the place to fix this.

**Comment by stormmore** [comment]
I would definitely like to see the ability to add additional roles. I do not see why you would limit the roles to just Bastion, Master and Node if I am honest. Currently, if I have multiple "Node" instance groups, there is no way to distinguish them when looking at the output from `kubectl get nodes` as they are all assigned the Node role!

In my use case, I specifically want to have an instance group for infra services that I do not necessarily want to run on the masters but definitely don't want to run on my general pool.
