### ISSUE TITLE
Add a warning that kops is not AWS free tier friendly

### ISSUE THREAD

**Issue by prabhu** [kubernetes/kops#5880]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
It appears like kops is storing several files in the s3 store and making numerous calls in the process to burn out the 2000 free API calls in just 2 or 3 attempts.

kops version: 1.10.0

**2. Feel free to provide a design supporting your feature request.**
Consider using tar.gz for s3 or suggestion on a local filesystem only mode for dev purposes. If this mode already exist please improve the README.md or point me to the right direction so that I can send  a PR

Thanks

**Comment by joffreypannequin** [comment]
I am hitting the same issue described by @prabhu . I am trying to host a small kubernetes installation within AWS free tier. I was trying the local storage approach.

According to the documentation in https://github.com/kubernetes/kops/blob/master/docs/state.md we should be able to use local file storage with 
> local filesystem (file://)

But when trying that, i get:

```
$ kops -v9 create cluster --state=file:///var/lib/kops-state-store
I0106 20:32:09.482495    4268 factory.go:68] state store file:///var/lib/kops-state-store

State Store: Invalid value: "file:///var/lib/kops-state-store": Unable to read state store.
Please use a valid state store when setting --state or KOPS_STATE_STORE env var.
For example, a valid value follows the format s3://<bucket>.
Trailing slash will be trimmed.
```

This error message is coming from https://github.com/kubernetes/kops/blob/894371395838751c830d34a51143227b2ca64006/cmd/kops/util/factory.go#L108-L110

Because of https://github.com/kubernetes/kops/blob/af4df08b694e2a1f8814a7b3649060477be67c86/util/pkg/vfs/vfs.go#L114-L115

So a local filesystem is not Cluster Readable and as such cannot be used for kops state store, if i understand correctly. So the documentation does not seem correct. Unless i am missing something.

Thanks for the help.
