### ISSUE TITLE
after creating a cluster the command it gave at the end to apply it was wrong.

### ISSUE THREAD

**Issue by phynias** [kubernetes/kops#5967]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.10.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.12.0
**3. What cloud provider are you using?**
aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
kops create cluster \
--node-count=2 \
--node-size=t2.medium \
--zones=us-west-1b \
--name=${KOPS_CLUSTER_NAME
```

which worked fine and then told me at the end:
```
...
Finally configure your cluster with: kops update cluster prod-k8s.mine.com --yes
```

when i run that i get:
```
Found multiple arguments which look like a cluster name
	"prod-k8s.mine.com" (via flag)
	"prod-k8s.mine.com" (as argument)

This often happens if you specify an argument to a boolean flag without using =
For example: use `--bastion=true` or `--bastion`, not `--bastion true`


Cannot specify cluster via --name and positional argument
```
it then worked when i added --name to the command.

not sure why it gave me a command to run that was wrong.

**Comment by huang-jy** [comment]
Because there are two ways you can pass this to kops -- one is using an environment variable (which I think is the way the devs do it - hence the command returned at the end of the run doesn't have it) and the other is using the `--name` switch (which I do)

In short, if you have the cluster name included on an environment variable, then kops doesn't need the `--name` switch, if you don't have the environment variable, then you _need_ the `--name` switch.
