### ISSUE TITLE
localhost resolving to [::1]

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#598]
Would be better if it resolved to 127.0.0.1

**Comment by chrislovecnm** [comment]
What does our /etc/hosts look like?

**Comment by kris-nova** [comment]
Need context here.. What is resolving to what - and under what conditions?

**Comment by chrislovecnm** [comment]
He is talking the IP address that is used to resolve local host on a deployed kops VM

**Comment by ianjoneill** [comment]
I think we've just hit a problem related to this following an upgrade from Kops 1.4.4 (Kubernetes 1.4.8) to Kops 1.5.1 (Kubernetes 1.5.2).

We are using a Kubernetes local docker registry for storing images that are generated by a Jenkins server deployed inside the cluster, so that we can run our tests in containers in Kubernetes. We are using the officially supported setup detailed [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/README.md).

Unfortunately on upgrade to Kops 1.5.1, the host accessible port is no longer working. If I SSH into one of the nodes, and run curl - it seemingly hangs forever.

```
root@ip-172-20-62-53:~# curl -v localhost:5000
* Rebuilt URL to: localhost:5000/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:5000
> Accept: */*
>
^C
```

Looking at the nodes host file, I find:

```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

If however I modify it, so that it is instead:

```
127.0.0.1       localhost
::1             ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

The curl command runs successfully:

```
root@ip-172-20-62-53:~# curl -v localhost:5000
* Rebuilt URL to: localhost:5000/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:5000
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Wed, 08 Feb 2017 09:13:56 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
```

**Comment by chrislovecnm** [comment]
We need to disable IPv6 as well. This is causing some of the problems as welll

**Comment by ianjoneill** [comment]
I notice #1816 has been closed as a non-issue - I take it this will be alleviated in a different way then?

**Comment by jeb5-ccl** [comment]
Just hit this also. any update on status?

**Comment by chrislovecnm** [comment]
I just reopened #1816 - as that issue should not have been closed
