### ISSUE TITLE
security: outgoing ssh port

### ISSUE THREAD

**Issue by rootnix** [kubernetes/kops#6178]
i got a situation that, ssh socket was connected with 22 port for both inbound and outbound.
when client try connect to 22 port for ssh, kernel has to make a socket for response within port range which is system set (net.ipv4.ip_local_port_range).
in spite of net.ipv4.ip_local_port_range is set correctly, it happened.

i don't know, is it problem with ami image or aws system.

used cloud: AWS
used AMI: k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17 (ami-0834983cea1f06ad4)
used sysctl set: net.ipv4.ip_local_port_range = 10240 65535

auth.log:
`
Dec  1 16:04:34 ip-172-22-53-82 sshd[18913]: Invalid user lost from 211.219.xx.xxx port 51084
Dec  1 16:04:34 ip-172-22-53-82 sshd[18913]: Received disconnect from 211.219.xx.xxx port 51084:11: Bye Bye [preauth]
Dec  1 16:04:34 ip-172-22-53-82 sshd[18913]: Disconnected from 211.219.xx.xxx port 51084 [preauth]

<<<---------- here is problem ------->
Dec  1 18:53:16 ip-172-22-53-82 sshd[14903]: Invalid user webadmin from 211.219.xx.xxx port 22
Dec  1 18:53:16 ip-172-22-53-82 sshd[14903]: Received disconnect from 211.219.xx.xxx port 22:11: Bye Bye [preauth]
Dec  1 18:53:16 ip-172-22-53-82 sshd[14903]: Disconnected from 211.219.xx.xxx port 22 [preauth]`

**Comment by justinsb** [comment]
I think you're saying the issue is the `port 22`, but that's the port the remote client is using.  It's certainly an unusual choice, but they are trying to brute force logins...

I believe the message comes from here: https://github.com/openssh/openssh-portable/blob/2a35862e664afde774d4a72497d394fe7306ccb5/auth.c#L341-L350

Going to close, but if I've missed something please do comment / reopen

/close
