### ISSUE TITLE
Kubectl version error

### ISSUE THREAD

**Issue by PrasadK1995** [kubernetes/kops#6268]
root@smartenDev:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: EOF

**Comment by PrasadK1995** [comment]
What is the Problem. I installed kops 1.10.0

**Comment by Pharb** [comment]
Hello @PrasadK1995

The problem you are seeing can have a lot of causes and requires some more details on how exactly you setup your Kubernetes cluster with kops. For that I would recommend to try to answer all questions from the [ISSUE_TEMPLATE](https://raw.githubusercontent.com/kubernetes/kops/master/.github/ISSUE_TEMPLATE/bug_report.md), otherwise it is very hard to help you with this problem.

First maybe you could try to downgrade your kubectl version to e.g. 1.10.12. This seemed to resolve a similar issue before: https://github.com/kubernetes/kops/issues/6172#issuecomment-447375907. 

If that does not change anything, I would recommend following the advice on the following issues and if you are lucky, your problem has already been solved or at least you can collect some more data to include here (logs, command outputs, configuration files, ...):
- #6172 (I would recommend reading through this for a few ideas where to start looking what could be broken)
- #6181 (probably only relevant if you are running your cluster on AWS in the us-east-2 region)

If you have any questions, just comment here and I can try to explain it further. You could also take a look at the Kops channels in the Kubernetes Slack, there are some links here about that: https://github.com/kubernetes/kops#other-ways-to-communicate-with-the-contributors

**Comment by PrasadK1995** [comment]
I am giving issue template.Pls check it and how to resolve that issue , let me know
[kops.txt](https://github.com/kubernetes/kops/files/2709782/kops.txt)

**Comment by Pharb** [comment]
Thanks for providing more details, that helps to understand how your cluster is set up.

As far as I can see you are using the following options:
- Kubernetes 1.10.11 and kubectl 1.10.12
- SSH access via bastion
- Weave networking
- AWS zones `ap-southeast-1a,ap-southeast-1b` for your nodes and `ap-southeast-1a` for your single master instance
- a public load-balancer to access the K8s api-server (which runs on your master instance)
- you have setup a Route53 DNS zone for internal and external DNS

The `Unable to connect to the server: EOF` errors you see indicate that the access to the api-server do not work properly.

As the next steps, I would recommend that you verify these three points to ensure that the api-server access in your cluster has been properly configured by Kops:

1. The api-server itself

As you should have a working bastion instance, you should be able to SSH to the master instance. This is also explained here: https://github.com/kubernetes/kops/blob/master/docs/bastion.md#using-ssh-agent-to-access-your-bastion
When logged in to the master instance with SSH, you can check if the api-server responds locally using these commands:

- `curl http://127.0.0.1:8080` (the expected response is a successful result with a list of API paths)
- `curl --insecure https://127.0.0.1:443` (the expected response is an `Unauthorized` error, because the request with curl does not include any credentials) 

If that works, you can also run requests like `curl http://127.0.0.1:8080/api/v1/nodes` to see some actual data from your cluster.

2. The AWS Elastic Load Balancer (api ELB) that forwards requests from the internet to the master instance

 The api ELB should have healthy instances, [you can check that here in the AWS console](https://console.aws.amazon.com/route53/home?#hosted-zones:).

3. The Route53 DNS records pointing to the api ELB

I would recommend checking the actual IP addresses for your DNS records by running `host api.internal.<cluster-name>` and `host api.<cluster-name>` (on your local machine or with SSH on a cluster instance).
Then you can compare the IP addresses with your [Route53 DNS records in the AWS console](https://console.aws.amazon.com/route53/home?#hosted-zones:).
And also compare this with [the api ELB DNS records for you cluster here](https://ap-southeast-1.console.aws.amazon.com/ec2/v2/home?region=ap-southeast-1#LoadBalancers:sort=loadBalancerName).

If you notice anything not working in these 3 steps, that could be a good indicator to where the problem is.

**Comment by PrasadK1995** [comment]
HI
  I want to create 2 nodes (ubuntu - r5.4xlarge),  1 master (ubuntu - r5.large)  with 1 micro bastion.
can you giv

**Comment by PrasadK1995** [comment]
After login to master, I have given curl http://127.0.0.1:8080 , Im getting
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused

**Comment by PrasadK1995** [comment]
kube-apiserver.log is giving error info
d
I1229 04:05:00.479584       1 master.go:228] Using reconciler: master-count
W1229 04:05:00.480778       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
I1229 04:05:00.484445       1 store.go:1391] Monitoring podtemplates count at <storage-prefix>//podtemplates
W1229 04:05:00.484514       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
I1229 04:05:00.484963       1 store.go:1391] Monitoring events count at <storage-prefix>//events
W1229 04:05:00.485010       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
I1229 04:05:00.486563       1 store.go:1391] Monitoring limitranges count at <storage-prefix>//limitranges
W1229 04:05:00.486626       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
I1229 04:05:00.488051       1 store.go:1391] Monitoring resourcequotas count at <storage-prefix>//resourcequotas
W1229 04:05:00.488175       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
E1229 04:05:00.488383       1 cacher.go:271] unexpected ListAndWatch error: storage/cacher.go:/podtemplates: Failed to list *core.PodTemplate: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
I1229 04:05:00.488462       1 store.go:1391] Monitoring secrets count at <storage-prefix>//secrets
W1229 04:05:00.488575       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
E1229 04:05:00.488786       1 cacher.go:271] unexpected ListAndWatch error: storage/cacher.go:/limitranges: Failed to list *core.LimitRange: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
E1229 04:05:00.489387       1 cacher.go:271] unexpected ListAndWatch error: storage/cacher.go:/resourcequotas: Failed to list *core.ResourceQuota: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
I1229 04:05:00.489463       1 store.go:1391] Monitoring persistentvolumes count at <storage-prefix>//persistentvolumes
W1229 04:05:00.489568       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
E1229 04:05:00.489777       1 cacher.go:271] unexpected ListAndWatch error: storage/cacher.go:/secrets: Failed to list *core.Secret: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
I1229 04:05:00.489923       1 store.go:1391] Monitoring persistentvolumeclaims count at <storage-prefix>//persistentvolumeclaims
W1229 04:05:00.490025       1 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"
E1229 04:05:00.490191       1 cacher.go:271] unexpected ListAndWatch error: storage/cacher.go:/persistentvolumes: Failed to list *core.PersistentVolume: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
I1229 04:05:00.490240       1 store.go:1391] Monitoring configmaps count at <storage-prefix>//configmaps
W1229 04:05:00.490336       1 storage_codec.go:52] storage type "etcd2" does not support media type "appli

**Comment by Pharb** [comment]
Thanks for the apiserver logs. It looks like the api-server cannot connect to the etcd cluster, which should be running on master instances: `etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused`

Could you somehow check the state of your etcd cluster? Maybe you can find some log messages from the etcd cluster on the master instance.

You could also take a look at similar issues, as the internal DNS with Route53 might be somehow broken:
- https://github.com/kubernetes/kops/issues/3413#issuecomment-353285153
- https://github.com/kubernetes/kops/issues/6172#issuecomment-444801580

**Comment by Pharb** [comment]
@PrasadK1995 Which AMI are you actually using for your r5 instances in the cluster? I can imagine using the debian-jessie AMI might cause some problems with the r5 instances.

**Comment by abhijitio** [comment]
@PrasadK1995  , change the image type stretch from jessie.

```
kops edit ig nodes --name yourcluster.com --state s3://your-s3-bucket (change the image type to stretch)
kops update cluster --name yourcluster.com --state s3://your-s3-bucket --yes
kops rolling-update cluster --name yourcluster.com --state s3://your-s3-bucket --yes
```
