### ISSUE TITLE
No Binary version of v1.11.0 available

### ISSUE THREAD

**Issue by marcosdiez** [kubernetes/kops#6285]
Hi!

There is a tag for v1.11.0, there is a branch, there is even a release item with the source code, but no binary.

I am not sure this is a bug or a feature, but I definitely miss it.

**Comment by gwohletz** [comment]
Also the release notes that normally appear for each release on the releases page are missing, and https://github.com/kubernetes/kops/blob/master/docs/releases/1.11-NOTES.md has not been updated since october and just says "will be included with 1.11.0 beta releases" makes me wonder if this is an actual release

**Comment by gwohletz** [comment]
also even the source code link points to "archive" instead of the normal "releases" location

**Comment by Pharb** [comment]
@marcosdiez @gwohletz The 1.11 release is still being prepared and will hopefully be available soon. To track the progress, you can look at #6256 and #6270.

**Comment by gwohletz** [comment]
OK, you should probably remove it from https://github.com/kubernetes/kops/releases in that case, the fact that it is listed there is what made me (and I assume others) think it had actually been released

**Comment by gwohletz** [comment]
now the releases page has been updated to include binaries but https://github.com/kubernetes/kops/pull/6256 is still showing open while https://github.com/kubernetes/kops/pull/6270 has been merged...

**Comment by justinsb** [comment]
We have now released it!  I'll clean up the PRs!
