### ISSUE TITLE
Master doesn't put to SchedulingDisabled mode

### ISSUE THREAD

**Issue by shamil** [kubernetes/kops#639]
Hi,
Since upgrading to kops `1.4.1`, the master is no longer put into `Ready,SchedulingDisabled`.
Initially starts as `Ready,SchedulingDisabled`, but after minute switches to back to `Ready`.

**Comment by kris-nova** [comment]
Just curious - but what problems is this causing?

**Comment by chrislovecnm** [comment]
Yah I noticed this. Without it being in SchedulingDisabled mode pods are scheduled to the master.  Typically you don't want your master acting as a minion.

**Comment by kris-nova** [comment]
Understood. Are replication steps fairly straight forward? Is it safe to say this can be easily replicated with a fresh copy of `kops` and a simple deployment? 

Attempting to replicate now, but just wondering what you have noticed.

Cheers

**Comment by justinsb** [comment]
The master is tainted, so normal pods should not schedule on it.  Daemonsets don't honor taints though, but we also label it, so that you can target a daemonset only to run on the master.  We don't have a label on the nodes yet, so you could target a daemonset to run only on the nodes, but we probably should.

This is the "new way" of doing things, but we're ahead of - well - everyone here.  And perhaps we shouldn't have done that.  Would be interested to hear what problems this causes - we should open issues in the kubernetes repo where we are finding fault with this model.

We do have two problems already:

NodePort on the master: https://github.com/kubernetes/kubernetes/issues/33884

kubectl get nodes is awkward: https://github.com/kubernetes/kubernetes/issues/33533

Neither is a deal-breaker AFAIK though

**Comment by shamil** [comment]
2 questions:
1. Are taints supported in k8s 1.3.x? or we need to upgrade to 1.4
2. The `NodePort` issue is deal-breaker no? Usually masters using smaller instances, which may affect networking as well.

**Comment by spiddy** [comment]
For those interested to activate again the `SchedulingDisabled` flag until this is fixed you can do on each master:

```
kubectl patch node MASTER_NAME -p "{\"spec\":{\"unschedulable\":true}}"
```

The issue we're facing is that the ELBs are pointing also to masters. This will disconnect the masters from the ELBs and redirect traffic only to nodes.

**Comment by chrislovecnm** [comment]
What is the status on this issue? Can we close?

**Comment by chrislovecnm** [comment]
Closing, please reopen if needs be.

**Comment by mausch** [comment]
I lost track of how k8s changed "taints"/"schedulable" flags, but I just provisioned a new cluster with kops 1.8.1 10 days ago and got an unwanted deployment on a master. Had to drain it manually.
