### ISSUE TITLE
How to log ssh access into the nodes?

### ISSUE THREAD

**Issue by tewing-riffyn** [kubernetes/kops#6404]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.11.0 installed via brew

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

aws inside a VPC created with Terraform

I need to log shell access to the k8s nodes and masters.  I could add additionalUserData to the instancegroups where I install packages but I'm wondering if there's a recommended way of getting this feature.

**Comment by timothyclarke** [comment]
I think this one is a mindset question, and I'm not fully expecting a response.
* Why are you logging into the nodes / masters
* If you need to log into them for one reason or another it should be break glass for debugging purposes only
* If you need to make changes, why are those changes not going into the cluster config and then the nodes being recycled so they are in a state which matches the config and you are confidant they will be in the same state if they were recycled in a (community) standard way.
* If there was no change, why was it logged into in the first place and why is the node being left in a possibly contaminated state instead of being recycled

**Comment by tewing-riffyn** [comment]
Maybe scraping the node logs via fluentd and sending them to elasticsearch is good enough.  We have some compliance requirements to alert people when someone accesses the masters or nodes via ssh.

@timothyclarke - I agree.  ssh access to nodes should be a break-glass only for emergency process.  Because it's so rare we should get notification when it happens.  The only time recently I've needed to use direct ssh was to debug an etcd crash on the masters.

**Comment by tewing-riffyn** [comment]
I've investigated this further and can't find any good solution.  I'm sure other kops users are working in highly regulated environments and must need to log ssh access to the nodes.  Does anyone have a resource for this solution?
