### ISSUE TITLE
Setting MTU for Calico has no effect with kops 1.11 and k8s 1.11

### ISSUE THREAD

**Issue by juris** [kubernetes/kops#6407]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
```
Version 1.11.0
```
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
I have updated kops from 1.10 with brew and changed Kubernetes version to 1.11.6. from 1.10.8.
I have also added mtu for Calico:
```
   networking:
     calico:
       crossSubnet: true
       mtu: 9001
```

After rolling update `cni_network_config` section of `calico-config` configmap looks like this:
```

{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "__ETCD_ENDPOINTS__",
      "log_level": "info",
      "ipam": {
        "type": "calico-ipam"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```
and all the pods have default 1500 mtu.

However, configmap should contain `"mtu": 9001` property as well. Functionality had been  [implemented](https://github.com/kubernetes/kops/pull/5380) some time ago, but looks like cni templates needs to be updated again.

**Comment by juris** [comment]
Moreover, updating configmap `cni_network_config` to
```

{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "__ETCD_ENDPOINTS__",
      "mtu": 9001,
      "log_level": "info",
      "ipam": {
        "type": "calico-ipam"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```

and restarting calico nodes has no effect. I had to ssh into every machine in the cluster, update `/etc/cni/net.d/10-calico.conflist` manually, and then restart all the calico pods to get mtu of 9001 in the pods.

**Comment by eseliger** [comment]
I'm also experiencing the config not being updated properly.

But after setting this, you need to do a rolling-update (--force) to affect existing networking interfaces, at least that worked for me. Hope it helps

**Comment by KashifSaadat** [comment]
Hey @juris, thanks for raising an issue and apologies for the delayed response.

When providing the MTU value in the Networking Spec, the Calico addon manifest in S3 gets updated, however the version for that resource stays the same. Protokube running on the nodes performs checks every 60 seconds to see which addons apply for the current running k8s version, and whether the addon version differs from what has currently been applied. Because the addon version hasn't actually changed from what's currently applied (have a peek at the annotations set on the kube-system namespace), no calico resource updates are applied, nor are the nodes marked for a rolling update. As suggested by @eseliger you would need to either perform a forced rolling-update on each node, or; manually update the `calico-config` ConfigMap to set the `veth_mtu` key, then cycle the calico pods (the `install-cni` init container reads this setting and updates the config file for you).

I believe what we could potentially do to mark a node as `NEEDUPDATE` following the NetworkingSpec change is to grab a hash of the addon files and add them into the UserData content for the InstanceGroups.

^ My understanding is a bit flaky with the protokube behaviour, @justinsb any thoughts?
