### ISSUE TITLE
Single Zone HA Master

### ISSUE THREAD

**Issue by nckturner** [kubernetes/kops#661]
We are discussing setting up a cluster with an HA master in one zone for a development environment.  It seems that to create an HA master cluster from the command line, you must specify multiple zones.  This will incur a (slight) [cost increase](https://forums.aws.amazon.com/message.jspa?messageID=326076), so I just wanted to float the idea that in some circumstances it might be desirable to have more control over where the masters are placed from the command line.

**Comment by chrislovecnm** [comment]
@nckturner if you are concerned about cost then why run HA in dev?  HA is not HA if it is not in multiple AZ ... 😀 Are you doing working on K8s itself?

**Comment by kris-nova** [comment]
@chrislovecnm is right - From a true highly available standpoint a user typically wants the components of the cluster in different availability zones (AZ). That way if one AZ fails - we still have others to fail over to. 

Also he brings up another good question - which is why are we running HA in a dev environment? Is this by design? There might be some cost we could shave there by only run dev with a single master.

Just echo-ing what @chrislovecnm said - but with a bit of wordsmithing..

Thoughts?

**Comment by nckturner** [comment]
Yeah I'm not concerned about it actually being HA, I am more concerned with it mirroring production.  I went with masters in different AZ's because the cost is only $0.01 per GB, and given we won't have much data transfer it will be small.  Closing Issue.
