### ISSUE TITLE
Setting a dnsZone does not affect the dns-controller

### ISSUE THREAD

**Issue by geNAZt** [kubernetes/kops#6676]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.11.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create two hosted zones in AWS:

`example.com`
`clustername.example.com`

Give kops the Zone ID of the first one in `dnsZone`. This will lead to api.internal.clustername.example.com to be generated in the `example.com` zone which is expected.

**5. What happened after the commands executed?**

Running the cluster setup and seeing that the nodes can't connect to the master i saw that the dns-controller did pick up the `clustername.example.com` zone which is not correct

**6. What did you expect to happen?**

The DNS controller should update the internal API dns in the `example.com` hosted Zone

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The dns-controller template add a `--zone=*/*` to the argv which leads the dns-controller to match the closest zone to the domain name which is not correct in my case. Adding a switch so one could disable that wildcard would be nice

**Comment by everpeace** [comment]
I have the same issue with kops `1.12.1`.

In my case,

I have hosted zones below:
(_example.com is actually my domain._)

```
example.com (private)  ZXXX
example.com (public)   ZYYY
k8s.example.com (public)  ZZZZ
```

and I created a cluster with 

```
kops create \
 --dns private \
 --dns-zone ZXXX \
 aws-201906.k8s.example.com
```

However, dns-controller keeps reporting errors because it tries to create a recordset `aws.internal.aws-201906.k8s.example.com.` in wrong hosted zone (`ZZZZ`):

```
I0610 15:39:37.440222       1 dnscontroller.go:283] error updating records for {A aws.internal.aws-201906.k8s.example.com.}: error querying resource records for zone "aws-201906.k8s.example.com.": error querying resource records for zone "aws-201906.k8s.example.com.": AccessDenied: User: arn:aws:sts::551...507:assumed-role/masters.aws-201906.k8s.example.com/i-0b1...7b5 is not authorized to perform: route53:ListResourceRecordSets on resource: arn:aws:route53:::hostedzone/ZZZZ
```

As a result, `nodes` can't join forever.  Is there any workaround??

**Comment by carpenterbees** [comment]
Hello, experiencing same problem.
*kops verson: 1.13.2*

We have Private/Public DNS zones with same names.
`dns-controller` finds wrong DNS zone and tries to update it. 

Setting `dnsZone:` to specific zone ID in cluster.spec does not change `dns-controller` flags.

How kops can support multiple DNS zones with same names?
Or how can be possible to set up explicitly `--zone` flag for `dns-controller` ?

according to this doc [https://github.com/kubernetes/kops/blob/1.13.2/dns-controller/docs/flags.md](url) issue can be fixed just by providing specific DSN zone ID with flag `--zone`

**Comment by carpenterbees** [comment]
@gekart 
Seems like issue was fixed in the latest kops release:
kops 1.14.1 just was tested.

with  cluster.spec parameter provided with zone ID 
`dns-controller` is updated with flags:

`- --zone=*/MYROTE53ZONEID
 - --zone=*/*
`
now proper zone is updated.

another concern is that kops adds 2 flags anyway as shown above.
reason of this is appending second flag disregard of previous condition results.

[https://github.com/kubernetes/kops/blob/baa5ae3934139aecaf1d0a55620bcb02e617a1a4/upup/pkg/fi/cloudup/template_functions.go#L298](url)
