### ISSUE TITLE
Question: Upgrading kubernetes version using yaml

### ISSUE THREAD

**Issue by flmmartins** [kubernetes/kops#6720]
Hello All,

I need to change the instance types of my nodes & master because they are lacking memory. Since I'm this big change I thought it would be a good opportunity to upgrade to 1.11.x (I'm on 1.10.x) and also upgrade OS.

I'm using a Kops YAML file. I wonder how to upgrade kubernetes using a YAML and what's is the best approach. 
I would upgrade my kops using `brew`

So I was thinking about updating these lines in my YAML file:

```
kind: Cluster
....
kubernetesVersion: 1.10.3 would be changed to 1.11.9
```

```
kind: InstanceGroup
....
machineType: m3.medium would change to m5.large
image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11  would be changed to kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
...
role: Master
```

```
kind: InstanceGroup
....
machineType: t2.medium would change to t2.large
image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11  would be changed to kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
...
role: Nodes
```

```
kind: InstanceGroup
....
machineType: <will-not-change>
image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11  would be changed to kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
...
role: Bastions
```

Then I was thinking about doing **kops replace --force** point to a file followed by a **kops update cluster**

And finally a rolling-upgrade.

Is that OKey? What's is the best approach upgrading when using a YAML instead kops edit approach? Do I need to change the OS? Is there anything else I need to change in the YAML?

**Comment by justinsb** [comment]
That sounds great, as long as you remember to upgrade kops first (you said update using brew, which I'm less familiar with, but as long as you're on kops >= 1.11 before going to k8s 1.11 that is good).

We do have `kops upgrade` which can help guide you through the kubernetes version change, but what you've specified is what is really happening "behind the scenes".

I'm not entirely sure why you need `--force` in `kops replace` (that sounds like it might be a bug?)

That _should_ be all that is required.  Sometimes if you start overriding flags there can be some problems if the underlying flags changed, but these problems are fairly rare.

You don't need to change the OS, but it's a good idea - the 1.11 image includes the recommended version of docker for 1.11 preinstalled.

One thing: technically you _should_ update to 1.10 and then 1.11, because technically kubernetes requires that.  I'm not aware of anything in 1.10 or 1.11 that will actually require it though.

**Comment by marek-obuchowicz** [comment]
> You don't need to change the OS, but it's a good idea
In our case changing the OS to stretch was required to use `t3.*` and `m5.*` instances, because of new NVMe drivers for EBS volumes. Without this, jessie-based instances didn't find external volumes.

**Comment by flmmartins** [comment]
> > You don't need to change the OS, but it's a good idea
> 
> In our case changing the OS to stretch was required to use `t3.*` and `m5.*` instances, because of new NVMe drivers for EBS volumes. Without this, jessie-based instances didn't find external volumes.

Yes. I read about that so this is a requirement.

**Update:** I did this upgrade and everything went super fine! =) Thanks all!
