### ISSUE TITLE
Maintainers to Support DigitalOcean

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kops#6773]
Last year I added support for DigitalOcean (https://github.com/kubernetes/kops/issues/2150), currently it is alpha feature gated and lacks a few features such as HA control plane and cluster upgrades. I personally am not able to push this to beta but I'd be happy to help others who are interested in helping maintain it.

**Comment by srikiz** [comment]
@andrewsykim - I have time and I can take a look at it. Please let me know your convenient time, we can discuss.

**Comment by prksu** [comment]
@andrewsykim @srikiz  interested too. ping me too to discuss this one 😃

**Comment by timoreimann** [comment]
Hi @srikiz @prksu, I work on the DOKS team at DigitalOcean. We'd love to see you help maintaining the DigitalOcean part of kops and be happy to facilitate the effort as well as provide assistance as much as we reasonably can.

Would you be interested in me setting up a call (or Slack chat or anything else that you prefer) where we could talk about the next steps? Happy to accommodate a day / time that works for you. I'm available via email (see my Github profile page) and the Kubernetes Slack if you'd like to share preferences / contact details more directly.

@andrewsykim I looked into the existing DigitalOcean support in kops that you provided some time ago in order to gain context, but would be curious to know if there's anything extra to that we should be aware of? I'd be glad to have you join any talk / chat we come up with; alternatively I could reach out to you directly to ensure a proper hand over. Let me know what you prefer.

Thanks!

**Comment by timoreimann** [comment]
@srikiz has taken over maintaining DigitalOcean support in kops and related projects (like etcd-manager). He has already driven several improvements (thanks for that, Sri!), and more are to come.

I'm not sure if the project maintains something like an owner list that we could amend; if not, then I believe we're good to close this issue.

/cc @andrewsykim
