### ISSUE TITLE
Remove tags from subnet when deleting Cluster

### ISSUE THREAD

**Issue by vfreitas-cit** [kubernetes/kops#7053]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
Remove tags from AWS VPC Subnet when deleting Cluster, because it's reaching the tag limit for the subnet.
The tag has the following name convention: kubernetes.io/cluster/[cluster-name]

**2. Feel free to provide a design supporting your feature request.**
I implemeted using aws cli and jenkins, but one native implementation would be better

**Comment by dontlaugh** [comment]
This still appears to be an issue, and it's kidn of surprising behavior.

We launch kops clusters into existing subnets, to take advantage of existing local resources and our existing VPN. And we use temporary clusters for testing, so we quickly run out of tags. The AWS limit is 50.

**Comment by olemarkus** [comment]
/reopen
/remove-lifecycle rotten

Happy to review a PR on this.

**Comment by dontlaugh** [comment]
Thank you for reopening, @olemarkus . I'm cooking up a quick hack for my team right now, but fixing it upstream is something we'd be willing to do. Can you (or anyone else) point to a place in the code where we can shim this in?

For myself, I'm sketching out a program that does this:

* list tags on our existing, well-known subnets
* for each tag that looks like something kops would provide (`*.k8s.local` in our case), look up ec2s with the same key
* if there are no ec2s, we can be reasonably assured that cluster has been torn down, so remove the tag from all subnets

This scheme lets us avoid shelling out to kops, which is less convenient for our use case.

To implement this in kops, we might only remove tags when doing `kops delete cluster`, not delete instance groups or anything like that. Since (I assume) the subnet ids and other metadata will be available in the context of this deletion, it should not be difficult.

**Comment by olemarkus** [comment]
A good place to start is this file: https://github.com/kubernetes/kops/blob/master/pkg/resources/aws/aws.go
