### ISSUE TITLE
Feature request: Add DNS A records of nodes in Route53 via dns-controller

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/kops#718]
### Use case

If we're running a UDP service (like StatsD), and we need to expose it publicly, we can use only `NodePorts` since `ELBs` don't work with UDP.
### Solution

One possible solution is keeping updated A records for all the nodes in Route53, and using a pre-defined `nodePort` value.

So, it would be awesome if `dns-controller` can create and keep the records up-to-date with the IPs of healthy nodes. Extra options like setting a TTL value would also be nice to have.

cc: @justinsb

**Comment by chrislovecnm** [comment]
Since nodes can be really ephemeral how do we handle not polluting DNS?

**Comment by justinsb** [comment]
@chrislovecnm the dns-controller watches nodes & updates DNS.    Might be a higher update volume than e.g. services, but we do have some debouncing in there, and it shouldn't be too bad (it isn't like we're registering individual pods!)

It also gets really interesting because this effectively replaces ELB (with hostPort).  So if you're running on bare-metal (or just "raw" VPS), and you set up ingress via hostPort, ingress will work...
