### ISSUE TITLE
Use existing vpc throws an error

### ISSUE THREAD

**Issue by justinmydomain** [kubernetes/kops#7209]
I am running a kops cluster in AWS. I would like to create another kops cluster in same AWS vpc. but its not even identifying the  --vpc argument. What is the correct way to pass the argument either in configuration yaml file, or directly in command line. 

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

$ kops version
Version 1.12.2 

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

v1.12.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

$ kops create -f kops-prod.yaml --state s3://kops..xxxxxx.com  --vpc vpc-xxxxx

**5. What happened after the commands executed?**

Error: unknown flag: --vpc

**6. What did you expect to happen?**

Create the resources in the same VPC (provided in the command line)

**9. Anything else do we need to know?**

**Comment by nvanheuverzwijn** [comment]
--vpc is only for `kops create cluster` I think. What you are trying is doable as I have done it myself. You can pass the VPC via `spec.networkID` key. You may also specify the subnets with the key `spec.subnets[].id` if you wish to reuse your vpc subnet.

Note that if you are explicitly specifying the vpc id and the subnets, KOPS won't manage it therefor, it won't delete it if you destroy your cluster (this is the expected behavior).
