### ISSUE TITLE
Kops ignores tags and deletes PVs

### ISSUE THREAD

**Issue by jamesthegiantpeach** [kubernetes/kops#7478]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
  - 1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
  - 1.13.10

**3. What cloud provider are you using?**
  - aws
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
  - kops delete cluster
**5. What happened after the commands executed?**
  - kops deleted all of my volumes even though they were tagged appropriately with shared instead of owned. 
**6. What did you expect to happen?**
  - For kops to not delete my data
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
  
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
  
**9. Anything else do we need to know?**
  I'm not sure if this is a bug or if this is the design, but it seems counter intuitive to me and a bit alarming that I can't keep kops from deleting my volumes. 

EDIT: I wanted to make clear that the StorageClass I am using also has a reclaim policy of Retain. The volume is deleted anyway.

**Comment by justinsb** [comment]
Thanks - looks like we have a fix coming for this.  I'm guessing we're talking here about volumes that are created for a StatefulSet, and you add a tag to them in k8s to mark them as shared?  (I don't think we do that by default?)

I'm wondering how you're tagging these volumes (assuming they aren't automatically tagged as shared) and whether we should warn about them on cluster delete.  (@vvbogdanov87 is fixing the issue with the deletion in #8079, though, so that'll be good!)

**Comment by jamesthegiantpeach** [comment]
Hi @justinsb, the only volumes that I added tags to are static volumes that already existed in my AWS infra. I have to add KubernetesCluster etc tags for kubernetes to accept the PV and PVC specs.
