### ISSUE TITLE
certificate authority CN=kubernetes-<cluster name> (feature request)

### ISSUE THREAD

**Issue by gladiatr72** [kubernetes/kops#754]
Right now with every new cluster, I get this:`/CN=kubernetes`

Other bits, are, of course, unique; however, this is the bit that primates tend to glance at.  Perhaps `CN=kubernetes, O=dev.kube.poc.thing.com` or some such?

Thanks for all of your efforts! 

-S

**Comment by chrislovecnm** [comment]
I don't know if it would impact the cluster, but not a bad idea to make the o and ou unique when you create a TLS cert

**Comment by chrislovecnm** [comment]
@kris-nova is there a security benefit?

**Comment by kris-nova** [comment]
Lets catch up on this on our call tomorrow - I will follow up on the issue afterwards 

@chrislovecnm

**Comment by gladiatr72** [comment]
Inquiring minds want to know! 💃

**Comment by chrislovecnm** [comment]
Me too... Lol - I don't think there is, but @kris-nova knows ssl certs a ton better than I

**Comment by kris-nova** [comment]
I think adding some uniqueness to the certs is fine, assuming you are talking about the certs generated [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/generate-cert/make-cert.sh).. this might be a concern for a different repository

I don't know much about how we handle certs in kops right now, but assume that script is getting salted - maybe @justinsb can shed some light on how our certs are generated now.

My suggestion would be to use `OU` instead of `O` - I think `O` is reserved for org name, and `OU` is unit name - although that is semantics at this point..

Just curious what the use case is here? LDAP?

**Comment by gladiatr72** [comment]
is this still something that might make it into a release?

**Comment by dmfenton** [comment]
I'm interested in this too. I want to script saving a bunch of certs to the OSX keychain. Apparently you can't automatically a new cert as trusted if one is already in the keystore with the same CN

**Comment by gladiatr72** [comment]
Bueller...

Bueller...

**Comment by chrislovecnm** [comment]
Happy to have someone contribute this feature!

**Comment by dmfenton** [comment]
@chrislovecnm would you point to the line in the code where the cert is generated? I went through the codebase once before and wasn't sure I identified it.

**Comment by chrislovecnm** [comment]
I think it is here https://github.com/kubernetes/kops/blob/26e0c781eac71cc0aaabe40d80fa76aa40159a5c/upup/pkg/fi/fitasks/keypair.go

@gambol99 I think you know this code better than I, can you give us some direction?

**Comment by gladiatr72** [comment]
Bueller..

**Comment by gladiatr72** [comment]
Seriously, if _not_ giving the cn of every kops gen'd cluster an identical cn somehow breaks something, it deserves to be broken.
