### ISSUE TITLE
Rolling-update in HA master is broken / slow

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#768]
`kops rolling-update cluster` with an HA cluster restarted the first node, but did not make any progress after > 5 minutes.

**Comment by bernielomax** [comment]
When I ran this job again using the master interval to 2 seconds it completed almost immediately. I then ran a rolling update without the master interval set and it worked this time round. It could have possibly been related to the fact that the cluster was in failed state. Non schedulers were running, etc. This was caused by issue https://github.com/kubernetes/kops/issues/767

**Comment by chrislovecnm** [comment]
@bernielomax can you recreate this on a green field install?

**Comment by bernielomax** [comment]
Yeah sure. I will give it a go.

**Comment by justinsb** [comment]
The interval is (deliberately) slow now, but I haven't seen any recent reports of hanging.

If people see hanging, please comment/reopen.  If you have logs, all the better :-)
