### ISSUE TITLE
Migrating from default networking to CNI

### ISSUE THREAD

**Issue by razic** [kubernetes/kops#773]
Hey... I tried following the docs here:

https://github.com/kubernetes/kops/blob/master/docs/networking.md

But was unable to successfully migrate my existing cluster. Some context:

The cluster was originally created with `kops`. It has practically default everything, except that it specifies HA masters (i.e `--master-zones`).

I started by running `kops edit cluster`. When the editor came up, I changed `kubenet` to `cni` and saved the file.

Then I ran `kops update cluster --yes`.

If I SSH to one of my nodes, and run `sudo ps aux` the `kubelet` is still running with the old networking options.

**Comment by justinsb** [comment]
So I wonder if this could have been #123.

I just tried this, and we definitely hit #925  I did this to work around #925: 
`kops rolling-update cluster --force --node-interval=5s --master-interval=5s --yes`

Then my networking configuration came up.

Do you think this was the problem @razic - #925?

**Comment by jaygorrell** [comment]
I am hitting this trying to switch from `flannel` to `weave`. The network documentation isn't super clear but I assume that should be possible. After making the change in `kops edit`, I don't get any expected changes from `kops update` or `kops rolling-update`. Even if I can force the update somehow, this seems concerning since I do all changes through Terraform output and it isn't detecting any changes there.
