### ISSUE TITLE
Cleanup and improve examples

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#784]
Let's have more examples and more robust examples!

**Comment by kris-nova** [comment]
@JuJu227 - Can I get a little verbage on what you would **love** to see here?

**Comment by jaygorrell** [comment]
I'll try to add more later, but one thing I'd like to see is is more thorough options listed rather than a handful of "how to resize nodes" or "how to change the root volume":
https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md

There's not really a simply complete listing of available options on any of the pages, which makes them a little overwhelming to wade through. The indexing of documentation pages is similarly overwhelming, with a mix of configuration options, concepts, and policies that could probably use some sort of structure or organizational renaming:
https://github.com/kubernetes/kops/tree/master/docs

**Comment by chrislovecnm** [comment]
Going to close this as cobra docs and other docs have improved. We have specific open issues for docs that are lacking
