### ISSUE TITLE
Missing kops controller support for cloudproviders

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#7870]
Kubernetes 1.16 from kops point of view needs support for kops controller. However, that controller do have currently only support for AWS, GCE and OpenStack. This means that if kops controller is not implemented to another providers, kops >=1.16 or kubernetes >=1.16 **will not work** in that cloud.

Missing providers:
- alicloud @LilyFaFa @xh4n3
- digitalocean @srikiz 
- spotinst @liranp 
- vsphere @SandeepPissay @prashima @abrarshivani 

Example implementation for OpenStack: https://github.com/kubernetes/kops/pull/7692

So if you are using these providers please act now, otherwise you will not see kubernetes 1.16 with kops in that provider.

/priority important-soon

**Comment by bittopaz** [comment]
I'll take care of alicloud part, but it might come a little bit later.
I'm currently working on making etcd-manager support Alicloud.

**Comment by srikiz** [comment]
Thanks @zetaab - I'll look into that and have a PR sometime next week.
FYI - @timoreimann

**Comment by zetaab** [comment]
@liranp what about spotinst support?

@SandeepPissay @prashima @abrarshivani any ideas about vmware support for this?

**Comment by liranp** [comment]
@zetaab Please correct me if I get it wrong, but it seems like there's no need to implement anything special for Spotinst since it's not a classic cloud provider but more like an add-on for AWS. We do not change the `CloudProvider` field in the cluster spec, so the `providerID` remains `aws:///<zone>/<instance-id>` and can be parsed by the AWS Node Identifier.

**Comment by liranp** [comment]
@zetaab Please correct me if I get it wrong, but it seems like there's no need to implement anything special for Spotinst since it's not a classic cloud provider but more like an add-on for AWS. We do not change the CloudProvider field in the cluster spec, so the providerID remains aws:///<zone>/<instance-id> and can be parsed by the AWS Node Identifier.

**Comment by liranp** [comment]
@zetaab Please correct me if I get it wrong, but it seems like there's no need to implement anything special for Spotinst since it's not a classic cloud provider but more like an add-on for AWS. We do not change the `CloudProvider` field in the cluster spec, so the `providerID` remains `aws:///<zone-name>/<instance-id>` and can be parsed by the AWS Node Identifier.

**Comment by zetaab** [comment]
well if cloudprovider says AWS I think it works.

@justinsb so we have quite clear situation about missing kops controller cloudproviders:
- DO @srikiz 
- alicloud @bittopaz 
- spotinst will be supported by AWS kops controller
- vmware unknown.

So it seems that vmware is only one which is not going to be supported, but actually vmware support for kops is alpha currently. As I see the biggest problem there is that vmware do not have metadata API and that makes kops integration to vmware really difficult. Currently they are building own images per instancegroup.

**Comment by SandeepPissay** [comment]
@zetaab We do not have any plans of supporting kops.

**Comment by zetaab** [comment]
alicloud is the only missing one that I see should be done before 1.16 final release. @bittopaz What you think, could that be done before 1.16 or do we need implement checks+errors that people cannot update clusters to kops 1.16 in alicloud?

**Comment by bittopaz** [comment]
@zetaab I don’t think I can make it before 1.16 release. I found more bugs when developing kops with Alicloud. And since alicloud is not officially supported in kops, we can do check+errors for now. I will remove those errors when finish the support in alicloud.
