### ISSUE TITLE
Move master to another zone

### ISSUE THREAD

**Issue by gersonmdesouza** [kubernetes/kops#8311]
Hi guys,

Can I move my master instance group to another zone? I have a HA cluster in us-east-1a, us-east-1b and us-east-1c and I want to change to us-east-1b, us-east-1c and us-east-1d, removing the master that are running in us-east-1a and creating a new one in us-east-1d. Is this possible?

**Comment by gersonmdesouza** [comment]
Or maybe, if possible, delete the master from us-east-1a and create another master in us-east-1a from zero? I'm having a problem with my master in this zone, after a cluster upgrading this master can't connect back to the cluster. I try to edit the instance group to 0 nodes and edit back to 1 node, but every time this master back online, it starts with the same problem.

Any suggestion?

**Comment by johngmyers** [comment]
Have you tried editing the instancegroup spec for the 1a master, specifying to put it in 1d?

**Comment by gersonmdesouza** [comment]
Yep, I got it to move the master node from us-east-1a to us-east-1d, but this master keep not connecting to the cluster. I'm moving this issue to SO: https://stackoverflow.com/questions/59687345/master-cant-connect-to-cluster

**Comment by gsstuart** [comment]
I'm also trying to relocate one of my three masters to a different zone (AWS) and having some difficulty.  In my case, the issue seems to be the etcd main/events EBS volumes... because the volumes are tied to a specific zone, the new master cannot mount the volumes.   kops creates and mounts new EBS volumes, but they do not seem to get populated with any data.

In theory, I would think that kops could magically sync these new volumes with the rest of the cluster, which still has quorum.  Anyone know if there's a way to get it to actually do this?

**Comment by dobesv** [comment]
Did you ever figure out a way to do this?  I want to do the same thing.
