### ISSUE TITLE
L7 LB / NLB in front of kube-apiserver / audit logs real IP

### ISSUE THREAD

**Issue by michalschott** [kubernetes/kops#8370]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Currently when enabling audit logs, source/original IP is always set to LB one. According to https://github.com/kubernetes/kubernetes/issues/76928#issuecomment-573278361 preventing original IP address should be possible by using L7 LB or NLB.

**2. Feel free to provide a design supporting your feature request.**

Loadbalancer type in front of kube-apiserver should be NLB instead CLB (AWS) // should use L7 instead L4 loadbalancer.

**Comment by rifelpet** [comment]
That k/k comment mentions that the X-Forwarded-For header is respected in audit logs. According to the [AWS docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html) Classic ELBs do send X-Forwarded-For but only if they're using an HTTP(S) listener. Kops currently sets up the API ELB with a TCP listener because the TLS termination is handled by kube-apiserver.

One option is that you can provide an ACM Certificate in the ClusterSpec: `.spec.api.loadBalancer.sslCertificate` in which case Kops will create an HTTPS listener which should provide the X-Forwarded-For header. I suppose Kops might be able to upload the kube-apiserver certificate and key as an IAM Server Certificate (or an ACM Certificate) and use that on an ELB HTTPS listener but it doesn't currently support that. That might be a reasonable feature request, I'm not sure if it has been considered in the past.

If you can provide an ACM Certificate that would definitely be your easiest option. That requires your cluster name uses a domain that you own and is publicly resolvable (a public hosted zone in Route53 for example).

**Comment by johngmyers** [comment]
Don't L4 NLBs also preserve source IP addresses? Adding support for L4 NLBs would be another possible feature addressing the requirement.

**Comment by michalschott** [comment]
I understand k/k comment as "use Network Loadbalancer instead Classic", because only NLB is preserving source IP for non-http(s) traffic.

Approach mentioned by @rifelpet (upload cert to AWS) sounds more complex by adding a support to different LB type.

If this is true, switching LB type will cause to loose support for:
- EC2-Classic - not supported since 2013 if I recall correctly?
- Sticky Sessions - not used
- configurable idle conneciton timeout - we can live w/o that

and it will give us better scalability/performance (NLB can handle more traffic than CLB) while also being a little cheaper.

**Comment by olemarkus** [comment]
It would be lovely to use NLB instead of CLB, but there are some odd limitations on the AWS side with how many NLBs that one can have per region (soft limit) and how many NLB ENIs one can have per VPC (harder limit).

**Comment by olemarkus** [comment]
/remove-lifecycle stale

With #9011 merged, this one can be closed

/close
