### ISSUE TITLE
kops create cluster should fail if --name already exists

### ISSUE THREAD

**Issue by zapman449** [kubernetes/kops#85]
Steps to reproduce:

Create cluster with:
`${GOPATH}/bin/kops create cluster --v=0 --cloud=aws --zones=us-west-2c --name=${NAME}`

Accidentally run:
`${GOPATH}/bin/kops create cluster --v=0 --cloud=aws --zones=us-east-1c --name=${NAME}`
(same name, different region)

This will break the cluster config.  kops should check that --name doesn't already exist in the state_store before committing changes to the config.

**Comment by justinsb** [comment]
This is now fixed with the improved UX: https://github.com/kubernetes/kops/blob/master/CHANGES.md#jul-21-2016

* `create cluster` creates a new spec, but won't create anything in AWS (unless you pass --yes, but you probably shouldn't).  It can therefore now fail if the cluster already exists.
* `update cluster` will now apply changes from an existing spec, whether an initial create in AWS or an update.
