### ISSUE TITLE
Add support for defining/using AWS ASG Lifecycle Hooks

### ISSUE THREAD

**Issue by andersosthus** [kubernetes/kops#8708]
We would like support for defining AWS ASG Lifecycle hooks on an InstanceGroup.

Use case:
We use AWS ASG Lifecycle hooks with a custom script that watches for AWS Spot terminations, and if detected runs a drain on the node and then sends a `COMPLETED` signal to the Lifecycle hook, that then allows the instance to be terminated.
The fact that we have this Lifecycle hooks kinda "breaks" `kops rolling-update cluster`, since the instance won't be terminated until either a `COMPLETED` signal is sent or it reaches the timeout value.

Our proposed solution would look something like this:
Add an `awsAsgLifecycle` property to `InstanceGroup` where one can set the Lifecycle properties (name, transition, default result, heartbeat timeout, notification arn, role arn).

When `kops` is doing a node drain, if the `InstanceGroup` has the `awsAsgLifecycle` set, it should send a `COMPLETED` signal when the drain is done.

If this sounds ok, I can do the implementation (though I probably need some guidance since I'm not that familiar with the kops codebase)

**Comment by paalkr** [comment]
Yes, please!

**Comment by mikesplain** [comment]
Out of curiosity, is there a reason you chose to go this way and not use something like https://github.com/pusher/k8s-spot-termination-handler?

**Comment by paalkr** [comment]
I'm actually working with @andersosthus on this one, so I will make an answer. Yes, there is a good reason why we don't use the component you linked to. It does only support spot termination and we need a solution that also works on AGS termination. We do NOT use the common Cluster Autoscaler because we have memory bound and spiky workloads. So we export utilization metrics from Prometheus to CloudWatch, and the we use a combination of TargetTracking and StepScaling to modify the Autoscaling Groups desired count.

Also the proposed solution from @andersosthus will allow to attach custom ARNs, like a Lambda function to do arbitrary activities when machines are added or removed from an Autoscaling group.

**Comment by olemarkus** [comment]
This sounds good to me

**Comment by rdrgmnzs** [comment]
@andersosthus are you still interested in implementing this? If not I'm going to take a shot at it.

**Comment by olemarkus** [comment]
/remove-lifecycle stale

Anyone had any luck with this issue?

This is to some extent related to #7119

**Comment by paalkr** [comment]
Currently we handled this using a custom systemd unit in the instance group. But the use case will not longer apply when we get this NTH implementation in place.

**Comment by bigman3** [comment]
> Currently we handled this using a custom systemd unit in the instance group. But the use case will not longer apply when we get this NTH implementation in place.

@paalkr can you share/guide how the systemd unit should like? I am trying to replicate, with increased timeouts (TimeoutStopSec, TimeoutSec) but hitting 2 minutes when it stops not gracefully

**Comment by olemarkus** [comment]
With the support for NTH in SQS mode, are the use cases covered?
/remove-lifecycle stale

**Comment by olemarkus** [comment]
Closing it is
/close
