### ISSUE TITLE
us-gov-east image for k8s not found

### ISSUE THREAD

**Issue by xamalahmed** [kubernetes/kops#8766]
Hi 
Can i have this image available in us-gov-east region?
k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17

I have successfully deployed k8s cluster in us-gov-west region using KOPS but i am getting image not found error on us-gov-east region using KOPS.

`W0318 00:56:06.410774   10998 executor.go:128] error running task "LaunchConfiguration/nodes.stg.k8s.local" (9m58s remaining to succeed): could not find Image for "kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17"

`

**Comment by jmymy** [comment]
fyi this repo does not control kope.io image creating / distribution. https://github.com/kubernetes-sigs/image-builder

**Comment by jmymy** [comment]
after some digging, it looks like it pulls all the regions the builder has access to and since gov cloud is separate, it doesn't add the images there. 
You could build your own and publish and then pass that AMI into the kops config. Or just copy the ami from one of the main regions to the us-gov region.

I assume @justinsb might just need to enable that region in the AWS account that builds the images

**Comment by weisjohn** [comment]
This is also happening on AWS GovCloud west: `us-gov-west`

**Comment by weisjohn** [comment]
@xamalahmed I was able to successfully bring up a `kops`-based cluster by specifying the AMI via the `--image` parameter. https://github.com/kubernetes/kops/blob/master/docs/operations/images.md#coreos

**Comment by weisjohn** [comment]
@justinsb any idea if pushing the images into GovCloud is a possibility?

**Comment by olemarkus** [comment]
Following #9163, you may probably just want to use the default Ubuntu 20.04 images.

**Comment by rifelpet** [comment]
Kops 1.18 defaults to the official Ubuntu 20.04 which is available in the gov and cn partitions, so this request is no longer necessary

/close
