### ISSUE TITLE
Error with Romana Networking Provider topology private

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#877]
When I follow the instructions from Romana on how to install.  The DNS controller fails to start:

```
  2s		2s		1	{kubelet ip-172-20-204-120.us-west-2.compute.internal}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "dns-controller-844861676-6mp7k_kube-system" with SetupNetworkError: "Failed to setup network for pod \"dns-controller-844861676-6mp7k_kube-system(6d8fb260-a90c-11e6-b9f2-0a9c7f736c01)\" using network plugins \"cni\": service-error; agent_post_pod: error posting to agent: curl: (7) Failed to connect to localhost port 9604: Connection refused; Skipping pod"
```

I am using head version of kops, using a build script that uploads a custom nodeup.  Please reach out to test.  I will be filing and issue with Romana.

**Comment by chrislovecnm** [comment]
@cgilmour can you assist?

**Comment by cgilmour** [comment]
@chrislovecnm: of course. I'll look into it.

**Comment by cgilmour** [comment]
Hi @chrislovecnm , an update on this:

We've released a newer version that fixes some bugs and the install should now work as expected, with some limitations.
Those limitations are mentioned in the instructions that kops documentation links to.

One of those limitations is about [`SrcDestCheck`](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck).
Romana needs this disabled so that packets can use `podIP`s as the source and destination of traffic between EC2 instances. It's enabled by default, and when enabled those packets are dropped silently.

It'd help if kops had an option to affect this when creating the instances.
I suspect other CNI providers will be affected by this in addition to Romana.

**Comment by justinsb** [comment]
Let's get romana working in 1.5.1

**Comment by chrislovecnm** [comment]
Talking with them they may wait. Currently they do not support more that one az, and they are working on supporting multiple.

**Comment by chrislovecnm** [comment]
@cgilmour what is the status on multiple AZ?  We have the same issue with Calico and Source Destination, so that should be worked out soonish.

**Comment by chrislovecnm** [comment]
Closing as Romana will follow up
