### ISSUE TITLE
Mixed instance types and labels

### ISSUE THREAD

**Issue by coderanger** [kubernetes/kops#8923]
One issue we've had with using mixed instance policies has been that there doesn't seem to be a great way to tell if the node is spot or not. What would you all say about checking the instance metadata in nodeup and setting a label for it? I know we removed the automatic label setting stuff back in 1.16 because it moved to the kubelet, but this would be a different kind of thing?

**Comment by rifelpet** [comment]
I think this sounds reasonable. The two approaches I see are having nodeup check the instance metadata and add it to kubelet's `--node-labels`, or extend kops-controller to query the EC2 API in response to new nodes and label them through kube-apiserver. I suppose it depends on what the label key would be and whether kubelet has permission to set it, as you mentioned:

> Labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type, kubernetes.io/os)

Is there a standard label for this purpose?  I found this [EKS Blog Post](https://aws.amazon.com/blogs/compute/run-your-kubernetes-workloads-on-amazon-ec2-spot-instances-with-amazon-eks/) which uses `Lifecycle=spot` and this [terraform eks module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md) which uses `kubernetes.io/lifecycle=spot` but otherwise don't see anything "official".

Perhaps `node.kubernetes.io/lifecycle=spot`?

**Comment by johngmyers** [comment]
A common label is `node-role.kubernetes.io/spot-worker`

**Comment by hakman** [comment]
NodeUp should be as fast as possible to get the instance running. I wouldn't complicate it more for this. `kops-controller` seems a good place for this.

The label itself, maybe `node.kubernetes.io/instance-lifecycle=spot`.
As @johngmyers said, `node-role.kubernetes.io/spot-worker` is/was also used, but not sure how much, except for `k8s-spot-termination-handler`.

**Comment by rifelpet** [comment]
The downside of using kops-controller is more EC2 API requests, in this case `ec2.DescribeInstances`, rather than being able to use the compute metadata endpoint. Google has a fair amount of search results for `node-role.kubernetes.io/spot-worker` so I'd be inclined to go with that.

**Comment by atmosx** [comment]
> NodeUp should be as fast as possible to get the instance running. I wouldn't complicate it more for this. `kops-controller` seems a good place for this.
> 
> The label itself, maybe `node.kubernetes.io/instance-lifecycle=spot`.
> As @johngmyers said, `node-role.kubernetes.io/spot-worker` is/was also used, but not sure how much, except for `k8s-spot-termination-handler`.

Is anyone working on this? I'd be interested in working on this.

**Comment by MoShitrit** [comment]
Hey @atmosx ,
Doesn't seem like anyone's on that issue right now. Feel free to assign it to yourself by commenting `/assign`.
Thanks!
