### ISSUE TITLE
Add etcd detail settings to kops create cluster

### ISSUE THREAD

**Issue by krangerich** [kubernetes/kops#8993]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Additional settings for `kops create cluster`:

`--etcd-volume-size <GB>`

Should set `spec.etcdClusters[].etcdMembers[].volumeSize` in the cluster.yaml

`--etcd-storage-kms-key-arn <string>`

Should set `spec.etcdClusters[].etcdMembers[].kmsKeyId` in the cluster.yaml

**Comment by olemarkus** [comment]
Unless there are really good reasons, we avoid creating additional cli flags. Why do you need these settings as flags vs using the cluster resource?

**Comment by krangerich** [comment]
Whats the exact design choice when there is a CLI flag and when not, since there are like 50 of them? 

You can change many of the current CLI flags on a running cluster by editing the cluster spec later, but not the etcd volume. Once it has been created, it has to stay the way it is. 
So it's better to give people the option to properly encrypt their etcd volumes and use a sane volume size from the beginning when they start creating their first clusters imperatively. 

Since there even is already an encryption setting (--encrypt-etcd-storage), it would make no sense to consciously omit the possibility of using a customer managed key for encryption.

**Comment by olemarkus** [comment]
These days, flags are only added if they are needed for end-to-end testing. Test infra doesn't accept cluster specs, so we need flags there.

You can change any part of the spec before doing the first `kops update cluster <cluster> --yes`.

**Comment by skieffer** [comment]
I wound up here while trying to figure out how to change the size of the etcd volumes.

Even if an `--etcd-volume-size` flag won't be added, it would be extremely helpful to add the `volumeSize` field to the default cluster yaml.

In other words, when a new user does `kops edit cluster`, instead of seeing this:

    etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
      - instanceGroup: master-us-east-2a
        name: a

they should see this:

    etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
      - instanceGroup: master-us-east-2a
        name: a
        volumeSize: 20

Personally, this would have saved me a lot of digging.

Or maybe this is a slippery slope? Once you add one default value, you have to add them all?
If that's the feeling, then how about just adding a helpful comment line at the top of the cluster yaml, like this:

    # Many more fields may be defined. See [the API](https://kops.sigs.k8s.io/cluster_spec/#the-cluster-resource).
