### ISSUE TITLE
How can I add another node to the cluster without updating other values? (kops cli version difference)

### ISSUE THREAD

**Issue by KristianWindsor** [kubernetes/kops#9117]
My cluster is still on v1.14.6 (yes, I plan to update it, but I can't at the moment).

I need to add a few more nodes, just a simple change to the instance group.

But when I try to apply this change, kops tries to upgrade the entire cluster from v1.14.6 to v1.16.2. How can I disable this automatic K8s upgrade?

**Comment by MoShitrit** [comment]
Hey @KristianWindsor !
So looks like there are a few issues that I think may occur here, let's address each of them in separate: 
1. Are you using the same `kops` binary now that you used the last time you interacted with this cluster? Generally- if you use a newer `kops` binary- you may expect things like that to happen. If you wish to maintain your cluster in its same state- make sure to use the same `kops` binary.

2. Which commands exactly did you run? I'm not 100% on that, but I don't think kops would change your k8s version unless you ran either `kops edit cluster` and modified the value of `spec.kubernetesVersion`, or you ran `kops upgrade cluster` which would have the same effect, along with updating the AMIs for the instance groups.

And lastly- to address your main concern, if all you wish is to increase the number of nodes in your cluster without changing anything else- You can do any of the following:
1. `kops edit ig <ig_name, eg. nodes>`, modify `minSize` and `maxSize` to the number you want. This will ensure that the number of nodes never changes.
2. `kops edit ig `kops edit ig <ig_name, eg. nodes>`, modify `maxSize` to a higher number than what you wish, then simple go to aws ec2 console -> autoscale groups -> find the one you want and update the `desired` field, to the number to want.
3. This will be a more dynamic way, if you wish to do that- you may use something like [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) which would scale nodes up and down for you (within the range you set to it) based on the current load in your cluster (scale up when pods can't schedule due to lack of resources, scale down when possible, read the docs in the mentioned link for more info).

**Comment by KristianWindsor** [comment]
Thanks for the help @MoShitrit!

Turns out that this problem was caused by me updating the kops cli version. 

Apparently I used kops v1.10.0 to create the cluster, and I saw this behavior using v1.16.2. Reverting back to [v1.10.0](https://github.com/kubernetes/kops/releases/tag/1.10.0) solved this.

And kops was actually not trying to upgrade the Kubernetes version. I mistook the kops cli version change with the k8s version change:
```
+ protokubeImage:
+   hash: f9c59c8184d7e216e6c8930ba595c6c4bc000de152823201e70921548e9c810c
-   hash: 139d69230bb029a419ca8e5a9be2f406d8e685c4
+   name: protokube:1.16.2
-   name: protokube:1.10.0
+   sources:
+   - https://artifacts.k8s.io/binaries/kops/1.16.2/images/protokube.tar.gz
+   - https://github.com/kubernetes/kops/releases/download/v1.16.2/images-protokube.tar.gz
+   - https://kubeupv2.s3.amazonaws.com/kops/1.16.2/images/protokube.tar.gz
-   source: https://kubeupv2.s3.amazonaws.com/kops/1.10.0/images/protokube.tar.gz
```

**Comment by KristianWindsor** [comment]
Updated the issue title to better reflect the problem

**Comment by MoShitrit** [comment]
Awesome, glad it worked out @KristianWindsor ! 😄

**Comment by johngmyers** [comment]
Specify the version of Kubernetes you want in the cluster spec.
