### ISSUE TITLE
Feature Request: Offline install / Support private registry

### ISSUE THREAD

**Issue by iusergii** [kubernetes/kops#9143]
Add an option to deploy/upgrade cluster from a private registry. There are many case which becomes quite crucial for many customer:
* No external access from environment.
* Recent outage of public registry.
* Security scan.

**Comment by rifelpet** [comment]
I believe Kops can already support overriding most if not all resources that it pulls externally. We may just need to add documentation around how to do it, and address the remaining gaps.

Grepping through the code I believe these are the environment variables that would need to be overridden:
```
KOPS_BASE_URL
S3_ENDPOINT
NODEUP_URL
PROTOKUBE_IMAGE
SKIP_PACKAGE_UPDATE
```

Some of the documentation on how to [test a local kops build](https://kops.sigs.k8s.io/development/adding_a_feature/#testing) might be relevant too, since it involves customizing the location that certain assets are pulled from

**Comment by iusergii** [comment]
@rifelpet thank you for point this out.  Is there any way to find out artifacts used by kops? 
I guess this might change in future. Having a Doc for this would be a very helpful.

**Comment by johngmyers** [comment]
There's also the "assets phase". One of our juniors was able to get our tooling to use it, but I haven't been able to extract documentation.

**Comment by rifelpet** [comment]
Off the top of my head:

* protokube is a tar file representing an exported docker image. currently hosted in an s3 bucket (not the cluster state store)
* nodeup a binary downloaded from a variety of places including github.com and an s3 bucket

KOPS_BASE_URL will override both of those. See [urls.go](https://github.com/kubernetes/kops/blob/66228c5c477e2ac051077c795070a7438d76e73c/upup/pkg/fi/cloudup/urls.go) for specifics including the expected relative paths within the base url: 

* For all of the docker images (k8s components, kops-controller, etcd-manager, CNI providers, etc.) you can set the registryMirrors API field for the docker daemon. the [aws china docs](https://github.com/kubernetes/kops/blob/71761bf3270689c9dc5fd400d427982eebc67bbe/docs/aws-china.md#customize-cluster-configuration) mention how to do this.

* nodeup installs packages for docker among other things. I believe Kops can support skipping the docker installation but I'm not sure if it can skip other packages as well. You may be able to use [hooks](https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#hooks) to update your package repo configuration to use a mirrored repo instead of upstream. The [SKIP_PACKAGE_UPDATE](https://github.com/kubernetes/kops/blob/298f79659a2bd9c1d6548c6c95b335b5e29e6466/upup/pkg/fi/nodeup/nodetasks/update_packages.go#L63) env var may help too. You may want to consider baking all of the required packages into an AMI. I haven't tested any of this though so YMMV.

**Comment by johngmyers** [comment]
I think for his use case the assets phase is more appropriate. KOPS_BASE_URL et. al. are for substituting assets built elsewhere for the officially built ones.

**Comment by christianjoun** [comment]
I have successfully implemented the “assets phase” for my organization.  

The feature is not that heavily documented, but it’s totally doable.  https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#containerregistry is what documentation there is; what's missing is the section on fileRepository. https://github.com/kubernetes/kops/blob/master/pkg/assets/builder.go is the section of code showing fileRepository.  

To setup a cluster (new or existing), you need to edit the cluster spec and add assets section as shown below.  Afterwards, you can run the assets phase like so (translate go-code to cli command line)

kops update cluster --phase assets --name example.com --state stateBucket --v 9

  assets:
    containerRegistry: somecontainerandbinaryregistry/docker/example.com/v1
    fileRepository: https://somecontainerandbinaryregistry/docker/example.com/v1

The behavior is such that if you 

- specify an s3 bucket, the assets phase will upload to the s3 bucket for you. You will need to do a rolling update after that. You can verify everything is working by looking at all the images in your cluster.  If you are using aws, you will see new user_data launch scripts for master/nodes using the new assets.

- specify a non-dns name, ie `my-local-folder`, the assets will be downloaded to your local directory.  You can upload them where you like, and edit the cluster spec once more to point there and do a rolling update

- specify an http address, I believe it just outputs in the logs what the paths should be; in our case we parse that and upload the binaries / images to the locations it asked and then do a rolling update

You might need a --force on the rolling-update & if you are using older then 1.14.0 kops / kubernetes, then channels/addons could still be pointing externally: see https://github.com/kubernetes/kops/issues/7410.

Let me know if you're having any difficulty.

**Comment by iusergii** [comment]
Thank you @christianjoun, I will have a try.

**Comment by MoShitrit** [comment]
There's also a partial guide here which we used at a previous job behind a corp proxy with _very_ limited access to the internet and were able to get to work with some adjustments (this was two years ago, so I can't remember the small changes we did. They were pretty straightforward though).
Worth a shot, let me know if it worked 😄 
@iusergii 
https://kops.sigs.k8s.io/aws-china/#offline-mode

**Comment by ari-becker** [comment]
/remove-lifecycle rotten

Particularly important now with Docker Hub starting to rate-limit public access.

**Comment by johngmyers** [comment]
I'm thinking there should be a toolbox command that runs the assets phase, giving the option of output in either json or yaml. Without a `--dryrun` flag it would copy the assets.

**Comment by blang** [comment]
We are basically in the same situation and are in the process to copy all the images to our private registry.
Specifying the container registry seems to work fine, but the search for all needed images is quite tedious.
```yaml
spec:
  assets:
    containerRegistry: example.com/registry
```

**The open question i have is, at which point do those image tags change?** The process of acquiring all images and their respective tags is currently done by hand looking at `/etc/kubernetes/manifests` etc.

**Comment by johngmyers** [comment]
#11700 moved the existing asset copying out of `kops update cluster --phase assets` to a new `kops get assets` command. #11654 added documentation.
/close
