### ISSUE TITLE
FR: command line arguments to specify master and node volume size and type

### ISSUE THREAD

**Issue by zytek** [kubernetes/kops#924]
It would be easier to play with kops if you could specify master and node instance groups rootVolumeSize and rootVolumeType from command line.

**Comment by chrislovecnm** [comment]
I would be opening to adding a yaml component for this if we don't have it. We have a lot of cli flags already ;)

Is it not in the full cluster spec?

**Comment by zytek** [comment]
Could you elaborate on 'yaml component' and 'full cluster spec' ? I'm new to kops. ;-)

**Comment by brandoncole** [comment]
The RootVolumeSize for the Masters and Nodes is configurable:

https://github.com/kubernetes/kops/search?utf8=%E2%9C%93&q=RootVolumeSize

But the workflow today requires you to edit a cluster using these steps:

https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#change-the-instance-type-in-an-instance-group

If you know what size your root volumes should be prior to creation, it'd be nice to have the ability to specify the sizes upfront rather than imposing an interactive edit cycle.  Maybe some ideal flags would be:

```
kops create cluster --master-volume-type=gp2 \
                    --master-volume-size=20 \
                    --node-volume-type=gp2 \
                    --node-volume-size=500 \
                    ...
```

@chrislovecnm @justinsb Is the alternative to pass in a file like this from the command line, if so how?

https://github.com/kubernetes/kops/blob/master/tests/integration/minimal-141/in.yaml

**Comment by zytek** [comment]
To reduce number of CLI flags kops could have an option to create cluster from templates, so that options not specified as CLI flag could be taken from template.

Either way I would love to be able to create cluster using one command invocation without editi step. This could be automated off-kops by manually uploading 'empty' kops state to S3 with templating functionalities, but I'd prefer to have that baked into kops.

**Comment by chrislovecnm** [comment]
> To reduce number of CLI flags kops could have an option to create cluster from templates, so that options not specified as CLI flag could be taken from template.

We have `kops create -f myyamlfile.yaml` already :)

**Comment by kris-nova** [comment]
Albeit `kops create -f` is only in `1.5.X`+ ...

**Comment by zytek** [comment]
That seems to fulfil my use case. Closing it. Thanks!
