### ISSUE TITLE
Add Support for new c5a AWS instance types

### ISSUE THREAD

**Issue by coolstang** [kubernetes/kops#9281]
- Add c5a AWS instance types to the supported list.

I can help with a PR if you like but I wouldn't know where to start to test and validate the change.  The code does look trivial to update.

**Comment by johngmyers** [comment]
It depends on what the failures are. You probably need to run `hack/update-expected.sh`.

**Comment by coolstang** [comment]
I had the wrong go version installed so I adjusted it and build and tests now pass so I can put up the PR as soon as the feature request gets approved, and I complete the contributor process.

**Comment by coolstang** [comment]
I have the work for this complete, can I get this item assigned to me so I can put up a MR?

**Comment by rifelpet** [comment]
/assign @coolstang

though I should point out that we recently merged https://github.com/kubernetes/kops/pull/8856 which removes the need for a hardcoded list of instance types. Those changes are in master (kops 1.19) so I think it would be best to have your PR target the release-1.18 branch so that we can add support for these types in kops 1.18. If there is anything special needed to handle these instance types beyond adding their entries to the large list of instance types, those special cases would need to be added to master in a separate PR.

**Comment by coolstang** [comment]
I signed it

**Comment by fred-vogt** [comment]
@coolstang, @rifelpet - I'd love this to be available in the 1.18.0 release.

AWS seems to be a bit behind schedule releasing these AMD instances: 
* [Jeff Bar announcement (18-Nov-2019) -  c5a, c5ad](https://aws.amazon.com/blogs/aws/in-the-works-new-amd-powered-compute-optimized-ec2-instances-c5a-c5ad/)
* seems that `c5ad` instances still have not been released ~ 6.5 months later

If this gets into the 1.18 release branch I'd like to test `c5a` and `c5ad` instance types as possible kops masters.

**Comment by coolstang** [comment]
I'm going to put up a MR for 1.17 and 1.16 release branches as well.

**Comment by coolstang** [comment]
Merged into 1.18.
