### ISSUE TITLE
bring-up speed: log times for slow tasks

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#939]
One of the initial node up tasks is taking 30 seconds.  We should log when a task takes more than 5 (?) seconds.

I suspect it is apt-get update, but would be good to confirm.

**Comment by justinsb** [comment]
Incidentally: I did confirm that it is apt-get update that is the slow task.  Not that that particularly changes this issue.

**Comment by chrislovecnm** [comment]
Well actually here is the thing. I don't think we should be running apt-get update ;) We need to install stable components that we know and have burned in. Updating an image on deployment leaves us open for stuff going boom because it is untested. My vote is to bake more into the base image and harden that image.

Don't do apt-get update or auto sec updates. We can leave it as an option, but I cannot run it like that in production.

@kris-nova thoughts?

**Comment by chrislovecnm** [comment]
@justinsb we need to put into place a job that builds and e2e tests a new image probably every week or two. Thoughts?
