### ISSUE TITLE
Scale instance group into specific subnets

### ISSUE THREAD

**Issue by asmith60** [kubernetes/kops#968]
Right now you can specify a list of zones for an instance group:

```yaml
zones:
  - us-east-1a
  - us-east-1c
  - us-east-1d
```

**Is there a way to specify a list of subnets for an instance group?** As an AWS user I am looking for something that maps to the  [VPCZoneIdentifier](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-vpczoneidentifier) property of an ASG.

**Comment by natewarr** [comment]
+1

**Comment by justinsb** [comment]
Not entirely sure I understand.  I don't think we allow you to create multiple subnets in a particular zone right now, so a zone uniquely identifies a subnet.

What we call zones right now will probably be renamed to subnets at some stage in the future, because that's actually what they are.  But you'll note that AWS makes the same mistake :-)

**Comment by natewarr** [comment]
This is a serious design limitation. I cannot see how one can achieve a "well architected deployment" according to AWS with the limitation of a single subnet per AZ. AWS's use of the property used is simply a backward compatibility before they supported advanced networking. New architectures tend to require these advanced features.

**Comment by justinsb** [comment]
We have a nice new schema coming in 1.5 that allows you to specify subnets.

**Comment by justinsb** [comment]
Going to close, as this is fixed on the master branch.  Coming soon to a released kops near you :-)
