### ISSUE TITLE
[aws] Mounting and using instance store volume

### ISSUE THREAD

**Issue by sajal** [kubernetes/kops#987]
I would like to use the free storage provided by EC2 on certain instance types. Example c3.2xlarge has 2 x 80 GB SSD.

On my pods id like to mount emptyDir{} (or hostDir ) which would make use of these disks. Bonus points if I can RAID0 multiple volumes.

The reason for asking is I have an IO intensive application and I am trying to get away with not paying(in both latency and money) for EBS. I will likely end up using EBS, but curious to know if this is possible with kops.

**Comment by justinsb** [comment]
You can't right now, I'm afraid.  It actually caused some problems before, purely because there's no GCE equivalent, so it didn't get as much testing in e2e or stress tests (e.g. with garbage collection).  It also seems that AWS is moving away from instance storage.  But I agree that using emptyDir or hostDir would be a good use.

We're tracking it as #429, so I'm going to close this one as a dup, but feel free to comment further on that issue if you think there's anything important to add.
