### ISSUE TITLE
Do not set insecureBindAddress on kubeAPIServer by default

### ISSUE THREAD

**Issue by djablonski-moia** [kubernetes/kops#9889]
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

The default value for `insecureBindAddress` on the `kubeAPIServer` is currently `127.0.0.1`. According to CIS Kubenetes Benchmark (1.2.18 in v1.5.1), this should not be set at all.
My expectation would therefore be that this flag is not set at all by default.

Alternatively, it should at least be possible to override this, which currently is also not possible, because overriding with an empty value does not work.

**2. Feel free to provide a design supporting your feature request.**

None

**Comment by olemarkus** [comment]
This may be a leftover from when the apiserver health check required the insecure port. We'll see if this can be removed.

**Comment by olemarkus** [comment]
Just looked a bit at this. We can skip adding the flag to the kube-apiserver binary, but the logs will still show it set to 127.0.0.1 as that is the default. Since we explicitly set --insecure-port=0 kube-apiserver will anyway not bind the insecure server.

I may do a PR on the flag, but it will be purely cosmetic.

**Comment by djablonski-moia** [comment]
Thanks a lot! For auditing, it will greatly help, even if it's just cosmetic 😄
